import { icebergEdgeReferenceId, icebergReferenceInputs } from './iceberg-reference';
import type { ToolcraftComponentAcceptance, ToolcraftTransferMode } from './acceptance/types';
import { appSchema } from './app-schema';
import { icebergParameters, icebergTarget } from './iceberg-controls';
import { icebergSettingsExportActionValue, icebergSettingsExportTarget } from './iceberg-settings-export';
export { appProductReadiness, appControlSectionInventory } from './iceberg-inventory';
export const appTransferMode: ToolcraftTransferMode = { mode:'new-toolcraft-app', animationIntent:{mode:'timeline-playback',loopDuration:{seconds:1.2,source:'product-derived',evidence:'A 1.2-second cycle keeps the requested plate separation fast while leaving enough time to read the inertial settle.'}}, referenceInputs:icebergReferenceInputs };
const proof=(testName:string,budget:'standard'|'extended-io'='standard')=>({file:'e2e/product-iceberg.spec.ts' as const,testName,budget});
const parameterProof=(p:typeof icebergParameters[number])=>({
  ...proof(`browser: iceberg ${p.key} changes visible relief live`),
  file:p.section==='engraving'?'e2e/product-iceberg-engraving.spec.ts' as const:p.section==='patterns'?'e2e/product-iceberg-patterns.spec.ts' as const:'e2e/product-iceberg.spec.ts' as const,
});
const common={automated:true,fixture:'Default reference-inspired iceberg',automatedTestName:'iceberg schema preserves procedural parameter contracts'};
export const appAcceptance: readonly ToolcraftComponentAcceptance[] = [
  { ...common,id:'renderer.timeline',kind:'runtime',componentType:'timeline',evidence:'timeline-output',timelineCoverage:'playback',timelineLoopProof:{direction:'forward-only',durationChange:'reproved-after-edit',reversePlayback:'forbidden',seam:'first-last-match'},timelinePlaybackCoverage:'all-playback-behavior',userAction:'Play, pause, scrub, edit duration and toggle loop in the runtime Timeline.',expectedObservable:'At time zero the base is closed; playback quickly separates four plates to the Plate gap value and the current frame remains available to image export.',browser:{file:'e2e/product-iceberg-animation.spec.ts',testName:'browser: iceberg timeline animates closed base into separated plates',budget:'standard'} },
  { ...common,id:'settings.export',target:icebergSettingsExportTarget,kind:'control',componentType:'actions',evidence:'exported-bytes',actionCoverage:[icebergSettingsExportActionValue],userAction:'Click Export Settings.',expectedObservable:'A JSON v3 settings file downloads with the current controls, camera, canvas and timeline state.',browser:{file:'e2e/product-iceberg-settings.spec.ts',testName:'browser: iceberg exports current application settings',budget:'standard'} },
  { ...common, id:'iceberg.engravingEnabled', target:'iceberg.engravingEnabled', kind:'control', componentType:'switch', interactionId:'edit-engravingEnabled', evidence:'rendered-pixels', userAction:'Enable engraving, adjust tonal strokes, then disable it.', expectedObservable:'Only rock shading becomes horizontal engraved ink; the cube grid and geometry remain unchanged, and disabling restores the original image.', browser:{file:'e2e/product-iceberg-engraving.spec.ts',testName:'browser: iceberg engraving preserves cube and original material',budget:'standard'} },
  ...icebergParameters.map(p=>({ ...common,id:icebergTarget(p.key),target:icebergTarget(p.key),kind:'control' as const,componentType:'slider',interactionId:`edit-${p.key}`,evidence:'rendered-pixels' as const, userAction:`Drag ${p.label} while holding the pointer.`, expectedObservable:p.help,browser:parameterProof(p), ...(p.key === 'seamJagged' ? { motionReferenceCoverage: [{ referenceId: icebergEdgeReferenceId, behaviorId: 'local-fracture' }] } : {}) })),
  ...['rockColor','iceColor'].map(key=>({...common,id:icebergTarget(key),target:icebergTarget(key),kind:'control' as const,componentType:'color',evidence:'rendered-pixels' as const,userAction:'Edit the surface hex color.',expectedObservable:'The corresponding rock or ice surface changes color.',browser:proof(`browser: iceberg ${key} changes surface pixels`)})),
  { ...common,id:'iceberg.orbit',target:'view.orbit',kind:'canvas-handle',componentType:'orientationGizmo',interactionId:'iceberg-orbit',evidence:'product-output',userAction:'Rotate by gizmo and direct model drag, snap, undo, reset and pan.',expectedObservable:'All sides rotate with shared pose, while viewport navigation stays separate.',canvasHandle:{testId:'toolcraft-orientation-gizmo',writesTarget:'view.orbit',outputObservable:'Lit iceberg pixels'},orientationGizmoCoverage:'all-required-orientation-gizmo-behavior',browser:{...proof('browser: iceberg orbit shares pose history and clean export'),file:'e2e/product-iceberg-orbit.spec.ts' as const} },
  { ...common,id:'background.include',target:'export.includeBackground',kind:'control',componentType:'switch',evidence:'product-output',backgroundOutputCoverage:'all-required-background-output',userAction:'Disable and restore Background, export transparent PNG and check Infinity dependency.',expectedObservable:'Runtime backdrop disappears; PNG has alpha; Infinity follows the background switch.',browser:{...proof('browser: iceberg background matches preview and artifact'),file:'e2e/product-iceberg-background.spec.ts' as const} },
  { ...common,id:'background.color',target:'appearance.background',kind:'control',componentType:'color',evidence:'product-output',userAction:'Edit Background color with Background on.',expectedObservable:'Runtime backdrop changes behind transparent foreground.',browser:{...proof('browser: iceberg background matches preview and artifact'),file:'e2e/product-iceberg-background.spec.ts' as const} },
  { ...common,id:'iceberg.backing',target:'canvas.renderScale',kind:'runtime',componentType:'slider',evidence:'product-output',renderScaleCoverage:{kind:'selected-backing-pixels',states:['interaction','playback','steady']},userAction:'Change resolution scale, drag a live parameter, play the timeline and observe settled backing.',expectedObservable:'Selected CSS × DPR × scale pixels exist during drag, playback and after settling.',browser:{...proof('browser: iceberg selected backing survives interaction'),file:'e2e/product-iceberg-backing.spec.ts' as const} },
  { ...common,id:'iceberg.infinity',target:'canvas.infinity',kind:'runtime',componentType:'canvas',evidence:'viewport-side-effect',infinityCanvasCoverage:'mode-continuity-and-restoration',userAction:'Toggle Infinity twice after changing output dimensions and panning.',expectedObservable:'Same scene, backing and view survive; finite sizing restores.',browser:{...proof('browser: iceberg infinity preserves scene and crop'),file:'e2e/product-iceberg-infinity.spec.ts' as const} },
  { ...common,id:'export.image.artifact',target:'actions.output',kind:'control',componentType:'panelActions',evidence:'exported-bytes',actionCoverage:['export.png','export.video'],exportArtifactCoverage:'all-required-image-export-behavior',userAction:'Export the configured image or video artifact.',expectedObservable:'The runtime downloads the requested image or animated video with its selected format and dimensions.',browser:{...proof('browser: iceberg image export has selected pixels and format','extended-io'),file:'e2e/product-iceberg-export.spec.ts' as const} },
  ...['format','resolution'].map(key=>({...common,id:`export.image.${key}`,target:`export.image.${key}`,kind:'control' as const,componentType:'select',evidence:'exported-bytes' as const,optionCoverage:'each-visible-item' as const,userAction:'Select an image artifact setting and export.',expectedObservable:'Selected format and dimensions are decoded from actual download.',browser:{...proof('browser: iceberg image export has selected pixels and format','extended-io'),file:'e2e/product-iceberg-export.spec.ts' as const}})),
  { ...common,id:'export.video.artifact',target:'actions.output',kind:'control',componentType:'panelActions',evidence:'exported-bytes',actionCoverage:['export.png','export.video'],exportArtifactCoverage:'all-required-video-export-behavior',userAction:'Choose video settings and export the timeline animation.',expectedObservable:'The downloaded video has the selected container and size, the exact timeline duration and 30 FPS timestamps, and visibly changes from the closed block to separated plates.',browser:{file:'e2e/product-iceberg-video-export.spec.ts',testName:'browser: iceberg video export encodes the complete plate animation',budget:'extended-io'} },
  ...['format','resolution'].map(key=>({...common,id:`export.video.${key}`,target:`export.video.${key}`,kind:'control' as const,componentType:'select',evidence:'exported-bytes' as const,optionCoverage:'each-visible-item' as const,userAction:'Select a video artifact setting and export.',expectedObservable:'The selected video format or output size is reflected by the runtime export action and decoded artifact.',browser:{file:'e2e/product-iceberg-video-export.spec.ts' as const,testName:'browser: iceberg video export encodes the complete plate animation',budget:'extended-io' as const}})),
  { ...common,id:'iceberg.infinity-export',target:'actions.output',kind:'runtime',componentType:'export',evidence:'exported-bytes',infinityCanvasCoverage:'scene-bounds-image-export',userAction:'Enable Infinity and export PNG.',expectedObservable:'Artifact crops to canonical product scene bounds.',browser:{...proof('browser: iceberg infinity preserves scene and crop'),file:'e2e/product-iceberg-infinity.spec.ts' as const} },
  { ...common,id:'iceberg.infinity-video-export',target:'actions.output',kind:'runtime',componentType:'export',evidence:'exported-bytes',infinityCanvasCoverage:'scene-bounds-video-export',userAction:'Export the same timeline once in finite mode and once with Infinity enabled.',expectedObservable:'Infinity video uses one union of the product bounds across the complete frame schedule while finite video retains the artboard dimensions.',browser:{file:'e2e/product-iceberg-video-export.spec.ts',testName:'browser: iceberg video export encodes the complete plate animation',budget:'extended-io'} },
  { ...common,id:'persistence.reload',target:'canvas.size.width',kind:'runtime',componentType:'persistence',evidence:'persistence-state',persistenceCoverage:'reload',persistenceSlices:appSchema.persistence.storage==='localStorage'?appSchema.persistence.include:[],userAction:'Edit canvas, values and panel workspace and reload.',expectedObservable:'Exact canvas, values and panel slices restore after real reload.',browser:{file:'e2e/app-persistence.spec.ts',testName:'browser: app restores exact canvas, values, and panel workspace slices after reload',budget:'extended-io'} },
];
