import { waveDefaultValues } from "./wave-default-values";

export const lightDefaults = {
  ambient: waveDefaultValues["light.ambient"],
  azimuth: waveDefaultValues["light.azimuth"],
  color: waveDefaultValues["light.color"],
  elevation: waveDefaultValues["light.elevation"],
  groundColor: waveDefaultValues["light.groundColor"],
  intensity: waveDefaultValues["light.intensity"],
  shadowSoftness: waveDefaultValues["light.shadowSoftness"],
  shadows: waveDefaultValues["light.shadows"],
  skyColor: waveDefaultValues["light.skyColor"],
} as const;

const lightReason =
  "Lighting edits update retained lights, material response, and the next full-quality frame.";

export const lightSection = {
  controls: {
    azimuth: {
      applicability: { mode: "always" },
      defaultValue: lightDefaults.azimuth,
      label: "Azimuth",
      max: 180,
      min: -180,
      performanceReason: lightReason,
      performanceRole: "responsiveness",
      semanticGroup: "sun",
      sliderValueKind: "continuous",
      target: "light.azimuth",
      type: "slider",
      unit: "°",
    },
    elevation: {
      applicability: { mode: "always" },
      defaultValue: lightDefaults.elevation,
      label: "Elevation",
      max: 90,
      min: -90,
      performanceReason: lightReason,
      performanceRole: "responsiveness",
      semanticGroup: "sun",
      sliderValueKind: "continuous",
      target: "light.elevation",
      type: "slider",
      unit: "°",
    },
    intensity: {
      applicability: { mode: "always" },
      defaultValue: lightDefaults.intensity,
      label: "Intensity",
      max: 5,
      min: 0,
      performanceReason: lightReason,
      performanceRole: "responsiveness",
      semanticGroup: "sun",
      sliderValueKind: "continuous",
      step: 0.05,
      target: "light.intensity",
      type: "slider",
    },
    color: {
      applicability: { mode: "always" },
      defaultValue: lightDefaults.color,
      label: "Sun",
      performanceReason: lightReason,
      performanceRole: "responsiveness",
      semanticGroup: "sun",
      target: "light.color",
      type: "color",
    },
    shadows: {
      applicability: { mode: "always" },
      defaultValue: lightDefaults.shadows,
      description: "Casts sun shadows between ribs; off keeps the sun as pure directional shading.",
      label: "Cast shadows",
      performanceReason: lightReason,
      performanceRole: "responsiveness",
      semanticGroup: "shadow",
      target: "light.shadows",
      type: "switch",
    },
    shadowSoftness: {
      applicability: {
        all: [{ equals: true, target: "light.shadows" }],
        mode: "conditional",
      },
      defaultValue: lightDefaults.shadowSoftness,
      label: "Shadow softness",
      max: 20,
      min: 0,
      performanceReason: lightReason,
      performanceRole: "responsiveness",
      semanticGroup: "shadow",
      sliderValueKind: "continuous",
      step: 0.5,
      target: "light.shadowSoftness",
      type: "slider",
    },
    ambient: {
      applicability: { mode: "always" },
      defaultValue: lightDefaults.ambient,
      label: "Ambient",
      max: 4,
      min: 0,
      performanceReason: lightReason,
      performanceRole: "responsiveness",
      semanticGroup: "ambient",
      sliderValueKind: "continuous",
      step: 0.05,
      target: "light.ambient",
      type: "slider",
    },
    skyColor: {
      applicability: { mode: "always" },
      defaultValue: lightDefaults.skyColor,
      label: "Sky",
      performanceReason: lightReason,
      performanceRole: "responsiveness",
      semanticGroup: "ambient-colors",
      target: "light.skyColor",
      type: "color",
    },
    groundColor: {
      applicability: { mode: "always" },
      defaultValue: lightDefaults.groundColor,
      label: "Ground",
      performanceReason: lightReason,
      performanceRole: "responsiveness",
      semanticGroup: "ambient-colors",
      target: "light.groundColor",
      type: "color",
    },
  },
  id: "light",
  title: "Light",
} as const;
