import { waveDefaultValues } from "./wave-default-values";

export const postDefaults = {
  aperture: waveDefaultValues["post.aperture"],
  bloom: waveDefaultValues["post.bloom"],
  bloomThreshold: waveDefaultValues["post.bloomThreshold"],
  depthOfField: waveDefaultValues["post.depthOfField"],
  exposure: waveDefaultValues["post.exposure"],
  focus: waveDefaultValues["post.focus"],
  occlusion: waveDefaultValues["post.occlusion"],
  occlusionRadius: waveDefaultValues["post.occlusionRadius"],
} as const;

const postReason =
  "Post-processing edits update retained pass uniforms and the next full-quality frame without rebuilding geometry.";

const focusApplicability = {
  all: [{ equals: true, target: "post.depthOfField" }],
  mode: "conditional",
} as const;

export const postSection = {
  controls: {
    exposure: {
      applicability: { mode: "always" },
      defaultValue: postDefaults.exposure,
      label: "Exposure",
      max: 3,
      min: 0.2,
      performanceReason: postReason,
      performanceRole: "responsiveness",
      semanticGroup: "tone",
      sliderValueKind: "continuous",
      step: 0.05,
      target: "post.exposure",
      type: "slider",
    },
    bloom: {
      applicability: { mode: "always" },
      defaultValue: postDefaults.bloom,
      label: "Bloom",
      max: 1,
      min: 0,
      performanceReason: postReason,
      performanceRole: "responsiveness",
      semanticGroup: "bloom",
      sliderValueKind: "continuous",
      step: 0.01,
      target: "post.bloom",
      type: "slider",
    },
    bloomThreshold: {
      applicability: { mode: "always" },
      defaultValue: postDefaults.bloomThreshold,
      label: "Bloom threshold",
      max: 1,
      min: 0,
      performanceReason: postReason,
      performanceRole: "responsiveness",
      semanticGroup: "bloom",
      sliderValueKind: "continuous",
      step: 0.01,
      target: "post.bloomThreshold",
      type: "slider",
    },
    occlusion: {
      applicability: { mode: "always" },
      defaultValue: postDefaults.occlusion,
      label: "Occlusion",
      max: 100,
      min: 0,
      performanceReason: postReason,
      performanceRole: "responsiveness",
      semanticGroup: "occlusion",
      sliderValueKind: "continuous",
      target: "post.occlusion",
      type: "slider",
      unit: "%",
    },
    occlusionRadius: {
      applicability: { mode: "always" },
      defaultValue: postDefaults.occlusionRadius,
      label: "AO radius",
      max: 4,
      min: 0.2,
      performanceReason: postReason,
      performanceRole: "responsiveness",
      semanticGroup: "occlusion",
      sliderValueKind: "continuous",
      step: 0.05,
      target: "post.occlusionRadius",
      type: "slider",
    },
    depthOfField: {
      applicability: { mode: "always" },
      defaultValue: postDefaults.depthOfField,
      description: "Blurs ribs away from the focus distance with a bokeh pass.",
      label: "Depth of field",
      performanceReason: postReason,
      performanceRole: "responsiveness",
      semanticGroup: "focus",
      target: "post.depthOfField",
      type: "switch",
    },
    focus: {
      applicability: focusApplicability,
      defaultValue: postDefaults.focus,
      label: "Focus distance",
      max: 120,
      min: 1,
      performanceReason: postReason,
      performanceRole: "responsiveness",
      semanticGroup: "focus",
      sliderValueKind: "continuous",
      step: 0.5,
      target: "post.focus",
      type: "slider",
    },
    aperture: {
      applicability: focusApplicability,
      defaultValue: postDefaults.aperture,
      label: "Aperture",
      max: 5,
      min: 0,
      performanceReason: postReason,
      performanceRole: "responsiveness",
      semanticGroup: "focus",
      sliderValueKind: "continuous",
      step: 0.05,
      target: "post.aperture",
      type: "slider",
    },
  },
  id: "post",
  title: "Post-processing",
} as const;
