export type HeroStructureShape = "dome" | "vault";

export type HeroRange = readonly [number, number];

export const structureDefaults = {
  arc: [...waveDefaultValues["structure.arc"]] as HeroRange,
  count: waveDefaultValues["structure.count"],
  domeLength: waveDefaultValues["structure.domeLength"],
  radius: waveDefaultValues["structure.radius"],
  shape: waveDefaultValues["structure.shape"] as HeroStructureShape,
  spacing: waveDefaultValues["structure.spacing"],
  twist: waveDefaultValues["structure.twist"],
  wave: waveDefaultValues["structure.wave"],
  waveLength: waveDefaultValues["structure.waveLength"],
} as const;

const geometryReason =
  "This value rebuilds the single merged rib geometry at the selected rib count.";
const deformationReason =
  "This value updates retained rib-deformation uniforms without rebuilding the merged geometry.";

export const structureSection = {
  controls: {
    shape: {
      applicability: { mode: "always" },
      defaultValue: structureDefaults.shape,
      label: "Shape",
      options: [
        { label: "Vault", value: "vault" },
        { label: "Dome", value: "dome" },
      ],
      performanceReason: geometryReason,
      performanceRole: "responsiveness",
      semanticGroup: "form",
      target: "structure.shape",
      type: "segmented",
    },
    radius: {
      applicability: { mode: "always" },
      defaultValue: structureDefaults.radius,
      label: "Radius",
      max: 100,
      min: 8,
      performanceReason: geometryReason,
      performanceRole: "responsiveness",
      semanticGroup: "form",
      sliderValueKind: "continuous",
      step: 0.5,
      target: "structure.radius",
      type: "slider",
    },
    domeLength: {
      applicability: {
        all: [{ equals: "dome", target: "structure.shape" }],
        mode: "conditional",
      },
      defaultValue: structureDefaults.domeLength,
      description: "Sets the ellipsoidal dome length along the vault axis.",
      label: "Dome length",
      max: 300,
      min: 30,
      performanceReason: geometryReason,
      performanceRole: "responsiveness",
      semanticGroup: "form",
      sliderValueKind: "continuous",
      target: "structure.domeLength",
      type: "slider",
    },
    arc: {
      applicability: { mode: "always" },
      defaultValue: structureDefaults.arc,
      description: "Sets the visible start and end angles of every swept rib.",
      label: "Arc",
      max: 150,
      min: -150,
      performanceReason: geometryReason,
      performanceRole: "responsiveness",
      semanticGroup: "form",
      step: 1,
      target: "structure.arc",
      type: "rangeSlider",
      unit: "°",
    },
    spacing: {
      applicability: { mode: "always" },
      defaultValue: structureDefaults.spacing,
      label: "Spacing",
      max: 4,
      min: 0.5,
      performanceReason: geometryReason,
      performanceRole: "responsiveness",
      semanticGroup: "rhythm",
      sliderValueKind: "continuous",
      step: 0.05,
      target: "structure.spacing",
      type: "slider",
    },
    count: {
      applicability: { mode: "always" },
      defaultValue: structureDefaults.count,
      description:
        "Controls structure length and geometry cost; low counts can reveal the honest end of the vault.",
      label: "Count",
      max: 400,
      min: 40,
      performanceReason:
        "Rib count linearly changes merged geometry, shadow, and shading workload.",
      performanceRole: "workload",
      semanticGroup: "rhythm",
      sliderValueKind: "continuous",
      step: 10,
      target: "structure.count",
      type: "slider",
    },
    twist: {
      applicability: { mode: "always" },
      defaultValue: structureDefaults.twist,
      description: "Rotates successive rib planes around the vertical axis.",
      label: "Twist",
      max: 4,
      min: -4,
      performanceReason: deformationReason,
      performanceRole: "responsiveness",
      semanticGroup: "deform",
      sliderValueKind: "continuous",
      step: 0.1,
      target: "structure.twist",
      type: "slider",
      unit: "°",
    },
    wave: {
      applicability: { mode: "always" },
      defaultValue: structureDefaults.wave,
      description: "Offsets the rib sweep sinusoidally along the vault axis.",
      label: "Wave",
      max: 10,
      min: 0,
      performanceReason: deformationReason,
      performanceRole: "responsiveness",
      semanticGroup: "deform",
      sliderValueKind: "continuous",
      step: 0.1,
      target: "structure.wave",
      type: "slider",
    },
    waveLength: {
      applicability: { mode: "always" },
      defaultValue: structureDefaults.waveLength,
      label: "Wavelength",
      max: 150,
      min: 8,
      performanceReason: deformationReason,
      performanceRole: "responsiveness",
      semanticGroup: "deform",
      sliderValueKind: "continuous",
      target: "structure.waveLength",
      type: "slider",
    },
  },
  id: "structure",
  title: "Structure",
} as const;
import { waveDefaultValues } from "./wave-default-values";
