export const waveDefaultValues = {
  "appearance.background": "#FFFFFF",
  "camera.fov": 71,
  "camera.height": -11.5,
  "camera.pitch": 35,
  "camera.position": {
    x: -0.12,
    y: -0.21,
  },
  "camera.roll": 31,
  "camera.yaw": -62,
  "canvas.renderScale": 2,
  "export.includeBackground": true,
  "haze.blend": "normal",
  "haze.glowColor": "#4049ED",
  "haze.glowPosition": {
    x: -0.93,
    y: -0.75,
  },
  "haze.glowRadius": 1.15,
  "haze.glowStrength": 100,
  "haze.gradient": {
    angle: 135,
    gradientType: "linear",
    stops: [
      {
        color: "#5D82CF",
        opacity: 88,
        position: "0%",
      },
      {
        color: "#8FA9DC",
        opacity: 40,
        position: "26%",
      },
      {
        color: "#FFFFFF",
        opacity: 0,
        position: "52%",
      },
    ],
  },
  "haze.strength": 100,
  "light.ambient": 1.9,
  "light.azimuth": -48,
  "light.color": "#F58700",
  "light.elevation": -71,
  "light.groundColor": "#FDE1B0",
  "light.intensity": 4.1,
  "light.shadows": false,
  "light.shadowSoftness": 12.5,
  "light.skyColor": "#DCE0EA",
  "masks.enabled": true,
  "masks.items": [
    {
      enabled: true,
      feather: 100,
      opacity: 100,
      position: {
        x: 0.23,
        y: 0.32,
      },
      radius: 21,
      rotation: -5.5,
      stretch: 1.8,
    },
    {
      enabled: true,
      feather: 82,
      opacity: 45,
      position: {
        x: 0.73,
        y: 0.22,
      },
      radius: 24,
      rotation: 0,
      stretch: 1,
    },
    {
      position: {
        x: -0.27,
        y: 0.23,
      },
      radius: 15.5,
      stretch: 2.67,
      rotation: 134,
      feather: 100,
      opacity: 78,
      enabled: true,
    },
  ],
  "masks.preview": false,
  "material.clearcoat": 1,
  "material.clearcoatRoughness": 0.14,
  "material.color": "#FCEAE4",
  "material.roughness": 0.44,
  "motion.amount": 3,
  "motion.breathSeconds": 60,
  "motion.cameraDrift": 66,
  "motion.coherence": 44,
  "motion.hazeDrift": 75,
  "motion.lightBreath": 41,
  "motion.lightSway": 20,
  "motion.phase": 0,
  "motion.smoothness": 43,
  "motion.sunColorB": "#FFF1D6",
  "motion.twistSway": 2,
  "motion.warmthDrift": 35,
  "motion.waveTravel": 1,
  "post.aperture": 0.8,
  "post.bloom": 0.16,
  "post.bloomThreshold": 0.46,
  "post.depthOfField": true,
  "post.exposure": 0.7,
  "post.focus": 20,
  "post.occlusion": 13,
  "post.occlusionRadius": 2.3,
  "rib.corner": 0.5,
  "rib.depth": 1.05,
  "rib.taperSide": "end",
  "rib.taperStart": 0.32,
  "rib.taperTip": 1,
  "rib.width": 1.05,
  "sky.envIntensity": 2.2,
  "sky.fogColor": "#BAC4EE",
  "sky.fogFar": 391,
  "sky.fogNear": 100,
  "sky.gradient": {
    angle: 0,
    gradientType: "linear",
    stops: [
      {
        color: "#E3DED9",
        opacity: 100,
        position: "0%",
      },
      {
        color: "#F2F4FD",
        opacity: 100,
        position: "50%",
      },
      {
        color: "#85868E",
        opacity: 100,
        position: "100%",
      },
    ],
  },
  "sky.lightGradient": {
    angle: 90,
    gradientType: "linear",
    stops: [
      {
        color: "#6F8ED3",
        opacity: 100,
        position: "31%",
      },
      {
        color: "#F5D7B2",
        opacity: 100,
        position: "100%",
      },
      {
        color: "#EAA839",
        opacity: 100,
        position: "64%",
      },
    ],
  },
  "structure.arc": [-150, 150],
  "structure.count": 310,
  "structure.domeLength": 180,
  "structure.radius": 19.5,
  "structure.shape": "dome",
  "structure.spacing": 1.15,
  "structure.twist": 0.7,
  "structure.wave": 2.8,
  "structure.waveLength": 56,
} as const;

export type WaveDefaultValues = typeof waveDefaultValues;
