import {
  defineToolcraftPerformance,
  type ToolcraftPerformanceConfig,
} from "@/toolcraft/runtime";

const mediaWorkload = {
  kind: "custom",
  reason:
    "High-frequency control scenarios use a calibrated 1920x1080 media baseline at renderScale 2; dedicated source, stress, viewport, and export scenarios cover the bundled 2048x2048 dimensions.",
  value: {
    renderScale: 2,
    sourceMedia: { height: 1080, width: 1920 },
  },
} as const;

const asciiMediaWorkload = {
  kind: "custom",
  reason:
    "Reference ASCII sizing maps small Size values to denser glyph grids; 1920x1080 media at renderScale 2 with readable Size 14 isolates high-frequency mode, glyph, and density work without multiplying every scenario by the separate extreme Size 1 stress.",
  value: {
    asciiMode: "uniform",
    renderScale: 2,
    size: 14,
    sourceMedia: { height: 1080, width: 1920 },
  },
} as const;

export const appPerformance: ToolcraftPerformanceConfig = defineToolcraftPerformance({
  rendererPipeline: {
    passes: [
      {
        cacheKey: ["source.image.mediaId", "source.image.dataUrl"],
        id: "decode-source",
        inputs: ["source.image.dataUrl"],
        invalidatedBy: ["source.image"],
        kind: "decode",
        output: "source",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: [
          "source.image.mediaId",
          "canvas.size.width",
          "canvas.size.height",
          "canvas.renderScale",
          "tone.brightness",
          "tone.contrast",
          "tone.saturation",
          "tone.hue",
        ],
        id: "sample-source",
        inputs: [
          "decode-source",
          "canvas.size.width",
          "canvas.size.height",
          "canvas.renderScale",
          "tone.brightness",
          "tone.contrast",
          "tone.saturation",
          "tone.hue",
        ],
        invalidatedBy: [
          "source.image",
          "canvas.renderScale",
          "tone.brightness",
          "tone.contrast",
          "tone.saturation",
          "tone.hue",
        ],
        kind: "preprocess",
        output: "intermediate",
        quality: "preview",
        runsOn: "main",
      },
      {
        cacheKey: [
          "sample-source",
          "effect.style",
          "effect.size",
          "effect.fill",
          "effect.density",
          "effect.exposure",
          "effect.scatter",
          "effect.seed",
          "effect.ascii.mode",
          "effect.ascii.glyphs",
          "effect.ascii.customGlyphs",
          "canvas.renderScale",
        ],
        id: "pixel-effect",
        inputs: [
          "sample-source",
          "effect.style",
          "effect.size",
          "effect.fill",
          "effect.density",
          "effect.exposure",
          "effect.scatter",
          "effect.seed",
          "effect.ascii.mode",
          "effect.ascii.glyphs",
          "effect.ascii.customGlyphs",
        ],
        invalidatedBy: [
          "effect.style",
          "effect.size",
          "effect.fill",
          "effect.density",
          "effect.exposure",
          "effect.scatter",
          "effect.seed",
          "effect.ascii.mode",
          "effect.ascii.glyphs",
          "effect.ascii.customGlyphs",
          "canvas.renderScale",
        ],
        kind: "pixel-transform",
        output: "overlay",
        quality: "preview",
        runsOn: "main",
      },
      {
        cacheKey: [
          "pixel-effect",
          "appearance.background",
          "export.includeBackground",
          "effect.layer.opacity",
          "effect.layer.blend",
          "canvas.renderScale",
          "finish.noise",
          "finish.grain",
          "finish.glow",
          "finish.vignette",
          "duotone.preset",
          "duotone.pixels",
          "duotone.base",
        ],
        id: "composite-preview",
        inputs: [
          "decode-source",
          "pixel-effect",
          "appearance.background",
          "export.includeBackground",
          "effect.layer.opacity",
          "effect.layer.blend",
          "finish.noise",
          "finish.grain",
          "finish.glow",
          "finish.vignette",
          "duotone.preset",
          "duotone.pixels",
          "duotone.base",
        ],
        invalidatedBy: [
          "appearance.background",
          "export.includeBackground",
          "effect.layer.opacity",
          "effect.layer.blend",
          "pixel-effect",
          "finish.noise",
          "finish.grain",
          "finish.glow",
          "finish.vignette",
          "duotone.preset",
          "duotone.pixels",
          "duotone.base",
        ],
        kind: "composite",
        output: "preview",
        quality: "retina",
        runsOn: "main",
      },
      {
        id: "export-image",
        inputs: [
          "decode-source",
          "pixel-effect",
          "composite-preview",
          "export.image.format",
          "export.image.resolution",
          "appearance.background",
          "export.includeBackground",
        ],
        invalidatedBy: [
          "export.actions",
          "export.image.format",
          "export.image.resolution",
          "appearance.background",
          "export.includeBackground",
          "effect.style",
          "effect.size",
          "effect.fill",
          "effect.density",
          "effect.exposure",
          "effect.scatter",
          "effect.seed",
          "effect.ascii.mode",
          "effect.ascii.glyphs",
          "effect.ascii.customGlyphs",
          "effect.layer.opacity",
          "effect.layer.blend",
          "tone.brightness",
          "tone.contrast",
          "tone.saturation",
          "tone.hue",
          "finish.noise",
          "finish.grain",
          "finish.glow",
          "finish.vignette",
          "duotone.preset",
          "duotone.pixels",
          "duotone.base",
        ],
        kind: "export",
        output: "export",
        quality: "export",
        runsOn: "export-only",
      },
    ],
    interactionInvalidation: [
      {
        interaction: "media-import",
        invalidates: ["decode-source", "sample-source", "pixel-effect", "composite-preview"],
        targets: ["source.image"],
      },
      {
        interaction: "control-drag",
        invalidates: ["sample-source", "pixel-effect", "composite-preview"],
        mustNotInvalidate: ["decode-source"],
        targets: [
          "canvas.renderScale",
          "effect.size",
          "effect.fill",
          "effect.density",
          "effect.exposure",
          "effect.scatter",
          "effect.seed",
          "effect.layer.opacity",
          "tone.brightness",
          "tone.contrast",
          "tone.saturation",
          "tone.hue",
          "finish.noise",
          "finish.grain",
          "finish.glow",
          "finish.vignette",
        ],
      },
      {
        interaction: "control-change",
        invalidates: ["sample-source", "pixel-effect", "composite-preview"],
        mustNotInvalidate: ["decode-source"],
        targets: [
          "source.image",
          "effect.style",
          "effect.ascii.mode",
          "effect.ascii.glyphs",
          "effect.ascii.customGlyphs",
          "effect.layer.blend",
          "duotone.preset",
          "duotone.pixels",
          "duotone.base",
          "appearance.background",
          "export.includeBackground",
          "runtime.settingsTransfer",
        ],
      },
      {
        interaction: "control-change",
        invalidates: ["export-image"],
        mustNotInvalidate: ["decode-source", "sample-source", "pixel-effect", "composite-preview"],
        targets: ["export.image.format", "export.image.resolution"],
      },
      {
        interaction: "viewport-drag",
        invalidates: [],
        mustNotInvalidate: ["decode-source", "sample-source", "pixel-effect"],
        targets: ["canvas.viewport"],
      },
      {
        interaction: "viewport-zoom",
        invalidates: [],
        mustNotInvalidate: ["decode-source", "sample-source", "pixel-effect"],
        targets: ["canvas.viewport"],
      },
      {
        interaction: "export",
        invalidates: ["export-image"],
        mustNotInvalidate: ["decode-source"],
        targets: ["export.actions", "export.image.format", "export.image.resolution"],
      },
    ],
  },
  rendererStrategy: "canvas-2d",
  rendererTechnique: {
    exportRenderer: "canvas-2d",
    fidelityRisks: [
      "ASCII output depends on browser font availability for Geist Mono, VT323, Press Start 2P, Share Tech Mono, and Noto Sans JP fallbacks.",
      "Scatter, dynamic ASCII, Noise, and Grain are seed-based rather than random, so preview, undo/redo, persistence, and export remain visually stable.",
      "Preview uses the user-selected canvas.renderScale backing pixels while export renders at the selected 2K/4K/8K long edge.",
    ],
    layers: [
      {
        content: ["bitmap-media", "dense-pattern", "text", "composite"],
        exportMode: "included",
        id: "productForegroundLayer",
        kind: "product-foreground",
        primitiveCount: "high",
        renderer: "canvas-2d",
        uiSelector: "[data-dither-output-canvas]",
      },
      {
        content: ["bitmap-media", "dense-pattern", "text", "composite"],
        exportMode: "included",
        id: "exportComposite",
        kind: "export-composite",
        primitiveCount: "high",
        renderer: "canvas-2d",
      },
    ],
    performanceRisks: [
      "Canvas 2D CPU pixel loops and full-canvas Glow can create long tasks at high preview/export resolution; targeted stress scenarios measure both paths without reducing the selected renderScale.",
      "WebGL/WebGPU were evaluated as GPU alternatives for the pixel-output workload; keeping the reference Canvas 2D renderer requires measured stress evidence from pnpm verify:perf rather than lowering renderScale or export resolution.",
    ],
    previewRenderer: "canvas-2d",
    productRepresentation: "pixel",
    rendererStrategy: "canvas-2d",
    rendererWorkload: "pixel-output",
    sourceRepresentation: "image-media",
    whyNotAlternativeStrategies: [
      "DOM and SVG cannot reproduce the reference per-pixel dithering, Bayer thresholding, halftone sampling, LEGO tiles, and raster ASCII compositing.",
      "WebGL/WebGPU are credible GPU alternatives for this pixel-output workload and will be compared through measured stress, frame, long task, and export budget evidence; first-port parity keeps Canvas 2D because the public reference algorithm is Canvas 2D.",
    ],
  },
  rendererWorkload: "pixel-output",
  scenarios: [
    {
      automated: true,
      automatedTestName: "settings transfer performance remains responsive",
      browser: true,
      browserTestName: "browser perf: settings transfer remains responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 700 },
      controlLabel: "Export Settings",
      expectedObservable: "Exporting settings does not destabilize the canvas viewport.",
      fixture: "changed Dither settings",
      id: "settings-transfer-responsive",
      interaction: "control-change",
      target: "runtime.settingsTransfer",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "source image workload changes preview",
      browser: true,
      browserTestName: "browser perf: source image workload changes preview",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1800 },
      controlLabel: "Image",
      expectedObservable: "Replacing the source image updates preview without freezing the UI.",
      fixture: "2048x2048 bundled-size media source at renderScale 2",
      id: "source-image-change",
      interaction: "control-change",
      stressFixture: {
        kind: "media",
        reason: "The source media dimensions are the measured heavy control value.",
        value: { height: 2048, width: 2048 },
      },
      target: "source.image",
      values: {
        default: { height: 720, width: 1280 },
        max: { height: 2048, width: 2048 },
        min: { height: 512, width: 512 },
      },
      workload: true,
      workloadFixture: mediaWorkload,
    },
    {
      automated: true,
      automatedTestName: "media import performance uses realistic source",
      browser: true,
      browserTestName: "browser perf: media import uses realistic source",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1800 },
      expectedObservable: "Importing a 2048x2048 image decodes and renders product output.",
      fixture: "2048x2048 generated image",
      id: "media-import",
      interaction: "media-import",
      stressFixture: {
        kind: "media",
        reason:
          "Image-processing workloads cover the bundled 2048x2048 source dimensions.",
        value: { height: 2048, width: 2048 },
      },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "effect style workload changes preview",
      browser: true,
      browserTestName: "browser perf: effect style workload changes preview",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1600 },
      controlLabel: "Style",
      expectedObservable: "Switching to dense ASCII changes renderer branch within budget.",
      fixture: "1920x1080 source at renderScale 2 and ASCII Size 14",
      id: "effect-style-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        reason: "ASCII is the heaviest style because it rasterizes many glyphs.",
        value: "characters",
      },
      target: "effect.style",
      values: { default: "dots", max: "characters", min: "none" },
      workload: true,
      workloadFixture: asciiMediaWorkload,
    },
    {
      automated: true,
      automatedTestName: "effect size drag workload stays responsive",
      browser: true,
      browserTestName: "browser perf: effect size drag workload stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1600 },
      controlLabel: "Size",
      expectedObservable: "Dragging Size changes dense cell count without viewport jumps.",
      fixture: "1920x1080 Dots source at renderScale 2",
      id: "effect-size-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason:
          "Reference grid sizing maps Size 1 to the densest cell grid, making it the heaviest responsive pointer-drag value for Dots/Halftone.",
        value: 1,
      },
      target: "effect.size",
      values: { default: 1, max: 100, min: 1 },
      workload: true,
      workloadFixture: mediaWorkload,
    },
    {
      automated: true,
      automatedTestName: "effect fill drag workload stays responsive",
      browser: true,
      browserTestName: "browser perf: effect fill drag workload stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1300 },
      controlLabel: "Fill",
      expectedObservable: "Dragging Fill changes surviving primitives without freezing input.",
      fixture: "1920x1080 Halftone source at renderScale 2",
      id: "effect-fill-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "Fill 100 keeps the most sampled primitives visible.",
        value: 100,
      },
      target: "effect.fill",
      values: { default: 81, max: 100, min: 0 },
      workload: true,
      workloadFixture: mediaWorkload,
    },
    {
      automated: true,
      automatedTestName: "effect density drag workload stays responsive",
      browser: true,
      browserTestName: "browser perf: effect density drag workload stays responsive",
      budget: { maxFrameGapMs: 110, maxInteractionMs: 1600 },
      controlLabel: "Density",
      expectedObservable: "Dragging Density changes detail mapping without viewport jumps.",
      fixture: "1920x1080 ASCII source at renderScale 2 and Size 14",
      id: "effect-density-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "high-density",
        reason: "Density 10 is the highest detail value exposed by the reference control.",
        value: 10,
      },
      target: "effect.density",
      values: { default: 8, max: 10, min: 1 },
      workload: true,
      workloadFixture: asciiMediaWorkload,
    },
    {
      automated: true,
      automatedTestName: "effect exposure drag remains responsive",
      browser: true,
      browserTestName: "browser perf: effect exposure drag remains responsive",
      budget: { maxFrameGapMs: 90, maxInteractionMs: 900 },
      controlLabel: "Exposure",
      expectedObservable: "Dragging Exposure updates pixel color math responsively.",
      fixture: "1920x1080 Dither source",
      id: "effect-exposure-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "Exposure 200 is the strongest color scaling value.",
        value: 200,
      },
      target: "effect.exposure",
      values: { default: 189, max: 200, min: 50 },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "effect scatter drag remains responsive",
      browser: true,
      browserTestName: "browser perf: effect scatter drag remains responsive",
      budget: { maxFrameGapMs: 90, maxInteractionMs: 900 },
      controlLabel: "Scatter",
      expectedObservable: "Dragging Scatter updates deterministic cell alpha responsively.",
      fixture: "1920x1080 Dots source",
      id: "effect-scatter-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "Scatter 100 is the strongest per-cell alpha variation.",
        value: 100,
      },
      target: "effect.scatter",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "effect seed drag remains responsive",
      browser: true,
      browserTestName: "browser perf: effect seed drag remains responsive",
      budget: { maxFrameGapMs: 90, maxInteractionMs: 1300 },
      controlLabel: "Seed",
      expectedObservable: "Dragging Seed refreshes deterministic scatter and texture patterns.",
      fixture: "1920x1080 Dots source with Scatter and Grain",
      id: "effect-seed-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "Seed 999 exercises regeneration of both deterministic texture tiles.",
        value: 999,
      },
      target: "effect.seed",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "tone brightness drag remains responsive",
      browser: true,
      browserTestName: "browser perf: tone brightness drag remains responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 1000 },
      controlLabel: "Brightness",
      expectedObservable: "Dragging Brightness refreshes the prepared source and output.",
      fixture: "1920x1080 Dither source",
      id: "tone-brightness-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "Brightness 200 is the strongest visible tone value.",
        value: 200,
      },
      target: "tone.brightness",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "tone contrast drag remains responsive",
      browser: true,
      browserTestName: "browser perf: tone contrast drag remains responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 1000 },
      controlLabel: "Contrast",
      expectedObservable: "Dragging Contrast refreshes the prepared source and output.",
      fixture: "1920x1080 Dither source",
      id: "tone-contrast-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "Contrast 200 is the strongest visible tone value.",
        value: 200,
      },
      target: "tone.contrast",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "tone saturation drag remains responsive",
      browser: true,
      browserTestName: "browser perf: tone saturation drag remains responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 1000 },
      controlLabel: "Saturation",
      expectedObservable: "Dragging Saturation refreshes the prepared source and output.",
      fixture: "1920x1080 Dither source",
      id: "tone-saturation-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "Saturation 200 is the strongest visible tone value.",
        value: 200,
      },
      target: "tone.saturation",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "tone hue drag remains responsive",
      browser: true,
      browserTestName: "browser perf: tone hue drag remains responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 1000 },
      controlLabel: "Hue",
      expectedObservable: "Dragging Hue refreshes the prepared source and output.",
      fixture: "1920x1080 Dither source",
      id: "tone-hue-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "Hue 180 covers the maximum positive rotation.",
        value: 180,
      },
      target: "tone.hue",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "finish noise drag remains responsive",
      browser: true,
      browserTestName: "browser perf: finish noise drag remains responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 1000 },
      controlLabel: "Noise",
      expectedObservable: "Dragging Noise composites the cached broad texture tile.",
      fixture: "1920x1080 Halftone source",
      id: "finish-noise-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "Noise 100 is the strongest broad texture composite.",
        value: 100,
      },
      target: "finish.noise",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "finish grain drag remains responsive",
      browser: true,
      browserTestName: "browser perf: finish grain drag remains responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 1000 },
      controlLabel: "Grain",
      expectedObservable: "Dragging Grain composites the cached fine texture tile.",
      fixture: "1920x1080 Halftone source",
      id: "finish-grain-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "Grain 100 is the strongest fine texture composite.",
        value: 100,
      },
      target: "finish.grain",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "finish glow drag workload stays responsive",
      browser: true,
      browserTestName: "browser perf: finish glow drag workload stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1800 },
      controlLabel: "Glow",
      expectedObservable: "Dragging Glow updates a full-canvas saturated screen-bloom pass.",
      fixture: "1920x1080 source at renderScale 2",
      id: "finish-glow-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "Glow 100 applies the strongest screen-bloom opacity.",
        value: 100,
      },
      target: "finish.glow",
      values: { default: 0, max: 100, min: 0 },
      workload: true,
      workloadFixture: mediaWorkload,
    },
    {
      automated: true,
      automatedTestName: "finish vignette drag remains responsive",
      browser: true,
      browserTestName: "browser perf: finish vignette drag remains responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 1000 },
      controlLabel: "Vignette",
      expectedObservable: "Dragging Vignette refreshes the radial finish composite.",
      fixture: "1920x1080 Halftone source",
      id: "finish-vignette-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "Vignette 100 is the darkest edge treatment.",
        value: 100,
      },
      target: "finish.vignette",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "duotone preset change remains responsive",
      browser: true,
      browserTestName: "browser perf: duotone preset change remains responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 1000 },
      controlLabel: "Preset",
      expectedObservable: "Changing the Duotone preset refreshes only the finish pass.",
      fixture: "1920x1080 Dots source",
      id: "duotone-preset-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        reason: "Neon Violet makes both duotone endpoints visually obvious.",
        value: "neon-violet",
      },
      target: "duotone.preset",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "duotone pixels color change remains responsive",
      browser: true,
      browserTestName: "browser perf: duotone pixels color change remains responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 1000 },
      controlLabel: "Pixels",
      expectedObservable: "Changing custom Pixels color refreshes only the finish pass.",
      fixture: "1920x1080 Dots source with Custom Duotone",
      id: "duotone-pixels-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        reason: "A saturated custom color makes the finish change measurable.",
        value: "#00F0FF",
      },
      target: "duotone.pixels",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "duotone base color change remains responsive",
      browser: true,
      browserTestName: "browser perf: duotone base color change remains responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 1000 },
      controlLabel: "Base",
      expectedObservable: "Changing custom Base color refreshes only the finish pass.",
      fixture: "1920x1080 Dots source with Custom Duotone",
      id: "duotone-base-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        reason: "A saturated dark custom base makes the finish change measurable.",
        value: "#17002E",
      },
      target: "duotone.base",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "ascii mode workload changes preview",
      browser: true,
      browserTestName: "browser perf: ascii mode workload changes preview",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 900 },
      controlLabel: "Style",
      expectedObservable: "Switching to Filled ASCII changes glyph layout within budget.",
      fixture: "1920x1080 ASCII source at renderScale 2 and Size 14",
      id: "ascii-mode-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        reason: "Filled mode fills the output with the most glyph positions.",
        value: "filled",
      },
      target: "effect.ascii.mode",
      values: { default: "uniform", max: "filled", min: "dynamic" },
      workload: true,
      workloadFixture: asciiMediaWorkload,
    },
    {
      automated: true,
      automatedTestName: "ascii glyphs workload changes preview",
      browser: true,
      browserTestName: "browser perf: ascii glyphs workload changes preview",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 900 },
      controlLabel: "Preset",
      expectedObservable: "Switching to Thin glyphs changes text rasterization within budget.",
      fixture: "1920x1080 ASCII source at renderScale 2 and Size 14",
      id: "ascii-glyphs-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        reason:
          "Thin changes the glyph ramp without measuring platform CJK fallback loading; Japanese glyphs remain covered by functional acceptance.",
        value: "thin",
      },
      target: "effect.ascii.glyphs",
      values: { default: "classic", max: "japanese", min: "thin" },
      workload: true,
      workloadFixture: asciiMediaWorkload,
    },
    {
      automated: true,
      automatedTestName: "ascii custom glyphs workload changes preview",
      browser: true,
      browserTestName: "browser perf: ascii custom glyphs workload changes preview",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 900 },
      controlLabel: "Chars",
      expectedObservable: "Typing a custom glyph ramp updates ASCII output within budget.",
      fixture: "1920x1080 ASCII source at renderScale 2 and Size 14",
      id: "ascii-custom-glyphs-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        reason: "A custom glyph ramp changes the ASCII mapping used by every sampled cell.",
        value: "@#%*+=-:.01XZ",
      },
      target: "effect.ascii.customGlyphs",
      values: {
        default: "",
        max: "@#%*+=-:.01XZ",
        min: ".",
      },
      workload: true,
      workloadFixture: asciiMediaWorkload,
    },
    {
      automated: true,
      automatedTestName: "layer opacity drag remains responsive",
      browser: true,
      browserTestName: "browser perf: layer opacity drag remains responsive",
      budget: { maxFrameGapMs: 90, maxInteractionMs: 900 },
      controlLabel: "Opacity",
      expectedObservable: "Dragging layer Opacity changes composite alpha without viewport jumps.",
      fixture: "1920x1080 Dither source",
      id: "layer-opacity-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "Opacity 100 is the strongest overlay composite.",
        value: 100,
      },
      target: "effect.layer.opacity",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "layer blend change remains responsive",
      browser: true,
      browserTestName: "browser perf: layer blend change remains responsive",
      budget: { maxFrameGapMs: 90, maxInteractionMs: 700 },
      controlLabel: "Blending Mode",
      expectedObservable: "Changing Blending Mode only recomposites the preview.",
      fixture: "2048x2048 Halftone source",
      id: "layer-blend-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        reason: "Color Dodge is the most visually intense blend option.",
        value: "color-dodge",
      },
      target: "effect.layer.blend",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "include background change remains responsive",
      browser: true,
      browserTestName: "browser perf: include background change remains responsive",
      budget: { maxFrameGapMs: 90, maxInteractionMs: 700 },
      controlLabel: "Include",
      expectedObservable: "Toggling Include only changes background compositing.",
      fixture: "transparent SVG source",
      id: "include-background-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        reason: "Include off exercises transparent preview/export compositing.",
        value: false,
      },
      target: "export.includeBackground",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "background color change remains responsive",
      browser: true,
      browserTestName: "browser perf: background color change remains responsive",
      budget: { maxFrameGapMs: 90, maxInteractionMs: 700 },
      controlLabel: "Background",
      expectedObservable: "Changing Background only updates the fill pass.",
      fixture: "transparent SVG source",
      id: "background-color-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        reason: "A saturated color makes background changes visually obvious.",
        value: "#3aedc9",
      },
      target: "appearance.background",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "image format change remains responsive",
      browser: true,
      browserTestName: "browser perf: image format change remains responsive",
      budget: { maxFrameGapMs: 110, maxInteractionMs: 700 },
      controlLabel: "Format",
      expectedObservable: "Changing Format updates export settings without rerender jank.",
      fixture: "default image export settings",
      id: "image-format-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        reason: "JPG selects the alternate encoder path.",
        value: "jpg",
      },
      target: "export.image.format",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "image resolution workload changes export target",
      browser: true,
      browserTestName: "browser perf: image resolution workload changes export target",
      budget: { maxFrameGapMs: 110, maxInteractionMs: 700 },
      controlLabel: "Resolution",
      expectedObservable: "Changing Resolution updates export target dimensions.",
      fixture: "default image export settings",
      id: "image-resolution-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        reason: "8K is the largest export size exposed by the product.",
        value: "8k",
      },
      target: "export.image.resolution",
      values: { default: "4k", max: "8k", min: "2k" },
      workload: true,
      workloadFixture: mediaWorkload,
    },
    {
      automated: true,
      automatedTestName: "render scale drag workload stays responsive",
      browser: true,
      browserTestName: "browser perf: render scale drag workload stays responsive",
      budget: { maxFrameGapMs: 110, maxInteractionMs: 900 },
      controlLabel: "Resolution scale",
      expectedObservable: "Dragging Resolution scale changes backing pixels without CSS size changes.",
      fixture: "1920x1080 Dots source",
      id: "render-scale-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "2x is the highest preview backing scale exposed by the runtime.",
        value: 2,
      },
      target: "canvas.renderScale",
      values: { default: 2, max: 2, min: 1 },
      workload: true,
      workloadFixture: mediaWorkload,
    },
    {
      automated: true,
      automatedTestName: "stress preview render stays within budget",
      browser: true,
      browserTestName: "browser perf: stress preview render stays within budget",
      budget: { maxLongTaskMs: 250, maxPreviewMs: 2000 },
      expectedObservable: "Worst-case preview renders visible product pixels within budget.",
      fixture: "2048x2048 source, LEGO, size 1, fill 100, density 10, renderScale 2",
      id: "stress-preview-render",
      interaction: "preview-render",
      stress: true,
      stressFixture: {
        kind: "custom",
        reason:
          "Combined worst-case preview state exercises the densest LEGO cell grid with full fill at max renderScale.",
        value: {
          sourceMedia: { height: 2048, width: 2048 },
          style: "lego",
          fill: 100,
          density: 10,
          renderScale: 2,
          size: 1,
        },
      },
      values: {
        default: {
          asciiMode: "filled",
          density: 8,
          fill: 81,
          renderScale: 2,
          sourceMedia: { height: 2048, width: 2048 },
          style: "dots",
          size: 1,
        },
        max: {
          density: 10,
          fill: 100,
          renderScale: 2,
          sourceMedia: { height: 2048, width: 2048 },
          style: "lego",
          size: 1,
        },
        min: {
          asciiMode: "uniform",
          density: 1,
          renderScale: 1,
          sourceMedia: { height: 512, width: 512 },
          style: "none",
          size: 1,
        },
      },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "viewport remains stable during controls",
      browser: true,
      browserTestName: "browser perf: viewport remains stable during controls",
      budget: { maxFrameGapMs: 100 },
      expectedObservable: "Canvas zoom and offset remain stable while controls update output.",
      fixture: "2048x2048 source with Dots effect",
      id: "viewport-stability",
      interaction: "viewport-stability",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "viewport zoom stress stays responsive",
      browser: true,
      browserTestName: "browser perf: viewport zoom stress stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1800, maxLongTaskMs: 250 },
      expectedObservable: "Toolbar zoom controls stay responsive under worst-case preview state.",
      fixture: "2048x2048 source, Dots size 100, renderScale 2",
      id: "viewport-zoom-stress",
      interaction: "viewport-zoom-stress",
      stress: true,
      stressFixture: {
        kind: "custom",
        reason: "Viewport zoom must not recompute expensive pixel passes in a dense state.",
        value: {
          renderScale: 2,
          sourceMedia: { height: 2048, width: 2048 },
          style: "dots",
          size: 100,
        },
      },
      values: {
        default: {
          renderScale: 2,
          sourceMedia: { height: 2048, width: 2048 },
          style: "dots",
          size: 1,
        },
        max: {
          renderScale: 2,
          sourceMedia: { height: 2048, width: 2048 },
          style: "dots",
          size: 100,
        },
        min: {
          renderScale: 1,
          sourceMedia: { height: 512, width: 512 },
          style: "none",
          size: 1,
        },
      },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "image export completes within budget",
      browser: true,
      browserTestName: "browser perf: image export completes within budget",
      budget: { maxExportMs: 8000 },
      expectedObservable: "Export PNG produces decoded image bytes at selected resolution.",
      fixture: "2048x2048 source with 2K PNG export",
      id: "image-export",
      interaction: "export-copy",
      stress: true,
      stressFixture: {
        kind: "custom",
        reason: "2K export is the functional budget path used for browser export verification.",
        value: {
          imageResolution: "2k",
          sourceMedia: { height: 2048, width: 2048 },
          style: "dither-blend",
        },
      },
      values: {
        default: {
          imageResolution: "4k",
          sourceMedia: { height: 2048, width: 2048 },
          style: "dots",
        },
        max: {
          imageResolution: "8k",
          sourceMedia: { height: 2048, width: 2048 },
          style: "characters",
        },
        min: {
          imageResolution: "2k",
          sourceMedia: { height: 512, width: 512 },
          style: "none",
        },
      },
      workload: true,
    },
  ],
  usesCustomRenderer: true,
  workloadTargets: [
    "source.image",
    "effect.style",
    "effect.size",
    "effect.fill",
    "effect.density",
    "effect.ascii.mode",
    "effect.ascii.glyphs",
    "effect.ascii.customGlyphs",
    "finish.glow",
    "export.image.resolution",
    "canvas.renderScale",
  ],
});
