import type { ToolcraftComponentAcceptance } from "../acceptance/types";

export const frozenMeltAcceptance = [
  {
    automated: true,
    automatedTestName: "melt.enabled locks model orbit and reveals brush settings",
    browser: true,
    browserTestName: "browser: Melt brush locks model orbit and reveals settings",
    componentType: "switch",
    evidence: "product-output",
    expectedObservable:
      "Turning Paint melt on by switch or M reveals thermal controls, hides the orientation gizmo, and changes a model hit from orbit ownership to melt ownership.",
    fixture: "uploaded asymmetric OBJ with visible frozen geometry",
    id: "melt.enabled",
    kind: "control",
    target: "melt.enabled",
    userAction:
      "Turn Paint melt on, toggle it both ways with M, then drag the visible model and inspect the shared pose.",
  },
  {
    automated: true,
    automatedTestName: "melt.heat changes thermal deposition strength",
    browser: true,
    browserTestName: "browser: Heat changes melt strength",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable:
      "The same pointer sample at higher Heat produces a clearer and moderately wider melted core.",
    fixture: "uploaded asymmetric OBJ painted at two separated surface points",
    id: "melt.heat",
    kind: "control",
    target: "melt.heat",
    userAction: "Paint equal samples at low and high Heat and compare the resulting openings.",
    visibilityCoverage: ["hidden", "visible"],
  },
  {
    automated: true,
    automatedTestName: "melt.radius changes geometry brush footprint",
    browser: true,
    browserTestName: "browser: Radius changes melt footprint",
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Radius changes both the textless geometry cursor and the object-space heated footprint.",
    fixture: "uploaded asymmetric OBJ with a centered brush hover and stroke",
    id: "melt.radius",
    kind: "control",
    target: "melt.radius",
    userAction: "Change Radius, hover the same surface point, and paint once.",
    visibilityCoverage: ["hidden", "visible"],
  },
  {
    automated: true,
    automatedTestName: "melt.structure changes thermal edge breakup",
    browser: true,
    browserTestName: "browser: Structure changes melt edge breakup",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable:
      "Structure changes the multi-scale irregularity of the local melt threshold without moving the stroke.",
    fixture: "uploaded asymmetric OBJ with one persistent melt stroke",
    id: "melt.structure",
    kind: "control",
    target: "melt.structure",
    userAction: "Paint once, then compare low and high Structure on the same thermal field.",
    visibilityCoverage: ["hidden", "visible"],
  },
  {
    automated: true,
    automatedTestName: "melt.refreeze changes thermal cooling",
    browser: true,
    browserTestName: "browser: Refreeze cools painted heat over time",
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable:
      "Positive Refreeze reduces the painted temperature and restores ice over time, while zero keeps it stable.",
    fixture: "uploaded asymmetric OBJ with one heated surface region",
    id: "melt.refreeze",
    kind: "control",
    target: "melt.refreeze",
    userAction: "Paint once at zero and positive Refreeze and compare the field after a delay.",
    visibilityCoverage: ["hidden", "visible"],
  },
  {
    automated: true,
    automatedTestName: "melt.refreezeMode changes cooling start time",
    browser: true,
    browserTestName: "browser: Refreeze mode controls cooling start time",
    componentType: "segmented",
    evidence: "product-output",
    expectedObservable:
      "Drawing cools the thermal field while the pointer remains held; Release pauses cooling until pointer-up and then restores ice.",
    fixture: "uploaded asymmetric OBJ with one held heated surface contact",
    id: "melt.refreezeMode",
    kind: "control",
    optionCoverage: ["during-stroke", "after-release"],
    target: "melt.refreezeMode",
    userAction:
      "Hold a melt contact in each mode and compare temperature before and after pointer-up.",
    visibilityCoverage: ["hidden", "visible"],
  },
  {
    actionCoverage: ["melt.refreeze-all"],
    automated: true,
    automatedTestName: "melt.action clears only the thermal field",
    browser: true,
    browserTestName: "browser: Refreeze action clears painted melt",
    componentType: "actions",
    evidence: "rendered-pixels",
    expectedObservable:
      "Refreeze removes painted heat immediately while preserving source, material, global thaw, and brush settings.",
    fixture: "uploaded asymmetric OBJ with one persistent painted melt region",
    id: "melt.action",
    kind: "control",
    target: "melt.action",
    userAction: "Paint a region, click Refreeze, and compare the frozen pixels and unchanged controls.",
    visibilityCoverage: ["hidden", "visible"],
  },
  {
    automated: true,
    automatedTestName: "melt.paint deposits continuous object-space heat",
    browser: true,
    browserTestName: "browser: geometry drag paints a continuous thermal reveal",
    componentType: "canvas-interaction",
    evidence: "rendered-pixels",
    expectedObservable:
      "A captured primary drag across visible geometry deposits gap-free object-space heat; a miss leaves the field unchanged and remains available to canvas pan.",
    fixture: "uploaded asymmetric OBJ with a fully frozen mask",
    id: "melt.paint",
    kind: "runtime",
    target: "melt.enabled",
    userAction: "Enable Paint melt, drag across the model, then drag in empty canvas.",
  },
  {
    automated: true,
    automatedTestName: "melt.edgeOverlap finds a partial projected brush intersection",
    browser: true,
    browserTestName: "browser: brush fringe melts the intersecting object edge",
    componentType: "canvas-interaction",
    evidence: "rendered-pixels",
    expectedObservable:
      "A pointer center outside the silhouette still melts the object when the projected brush disk overlaps it, while a completely separated disk leaves the field unchanged.",
    fixture: "uploaded asymmetric OBJ with minimum and maximum brush radii",
    id: "melt.edge-overlap",
    kind: "runtime",
    target: "melt.enabled",
    userAction:
      "Establish an outside miss at minimum Radius, enlarge Radius, and paint from the same pointer position.",
  },
] satisfies readonly ToolcraftComponentAcceptance[];
