import { defineToolcraft } from "@/toolcraft/runtime";

const responsiveness = (reason: string) => ({
  performanceReason: reason,
  performanceRole: "responsiveness" as const,
});

const workload = (reason: string) => ({
  performanceReason: reason,
  performanceRole: "workload" as const,
});

export const appSchema = defineToolcraft({
  canvas: {
    draggable: true,
    enabled: true,
    renderScale: true,
    size: { height: 1080, unit: "px", width: 1920 },
    sizing: { mode: "editable-output" },
    upload: false,
  },
  export: {
    png: { background: "include" },
  },
  panels: {
    controls: {
      sections: [
        {
          controls: {
            variations: {
              actions: [
                { icon: "shuffle", label: "Randomize look", value: "randomize-look" },
                { icon: "wand-sparkles", label: "Randomize colors", value: "randomize-colors" },
              ],
              label: false,
              target: "panel.variations",
              type: "actions",
            },
          },
          title: "Variations",
        },
        {
          controls: {
            form: {
              defaultValue: "circle",
              description: "Chooses the deformation family for the single centered mosaic object.",
              label: "Form",
              options: [
                { label: "Circle", value: "circle" },
                { label: "Flower", value: "flower" },
                { label: "Pinch", value: "pinch" },
                { label: "Vortex", value: "vortex" },
              ],
              orderRole: "mode",
              target: "shape.form",
              type: "select",
              ...responsiveness("Form rebuilds one bounded point field with a different deterministic contour."),
            },
            bend: {
              defaultValue: 26,
              description: "Moves from a restrained contour to a pronounced motion-safe radial deformation.",
              label: "Bend",
              max: 100,
              min: 0,
              orderRole: "primary",
              step: 1,
              target: "shape.bend",
              type: "slider",
              unit: "%",
              ...responsiveness("Bend updates the existing point positions without changing vertex count."),
            },
            rotation: {
              defaultValue: 249,
              description: "Rotates the authored contour in its own plane without changing the 3D view or animation phase.",
              label: "Contour angle",
              max: 360,
              min: 0,
              orderRole: "spatial",
              step: 1,
              target: "shape.rotation",
              type: "slider",
              unit: "°",
              ...responsiveness("Rotation transforms the cached point field at a fixed vertex count."),
            },
            orientation: {
              defaultValue: {
                position: [-1.15, 0.9, 4.75],
                up: [0, 1, 0],
              },
              description: "The starter canvas gizmo and direct object drag share this 3D orientation pose.",
              keyframeable: false,
              label: false,
              orderRole: "spatial",
              target: "view.orbit",
              type: "orientationGizmo",
              ...responsiveness("3D orientation updates camera-basis uniforms without rebuilding geometry."),
            },
            depth: {
              defaultValue: 42,
              description: "Changes both the center-to-edge contour profile and the physical static relief.",
              label: "Depth",
              max: 100,
              min: 0,
              orderRole: "strength",
              step: 1,
              target: "shape.depth",
              type: "slider",
              unit: "%",
              ...responsiveness("Depth remaps the radial deformation profile at a fixed workload."),
            },
            repeats: {
              defaultValue: 12,
              description: "Sets the number of repeated bends, petals, pinches, vortex ridges, or arc segments.",
              label: "Repeats",
              max: 12,
              min: 2,
              orderRole: "detail",
              step: 1,
              target: "shape.repeats",
              type: "slider",
              variant: "discrete",
              ...responsiveness("Repeats changes contour frequency without increasing the point count."),
            },
          },
          title: "Shape",
        },
        {
          controls: {
            radiusRange: {
              defaultValue: [2, 93],
              description: "Sets the inner and outer boundaries of the concentric field as a share of the available object radius.",
              label: "Ring radius",
              max: 100,
              min: 0,
              orderRole: "primary",
              step: 1,
              target: "volume.radiusRange",
              type: "rangeSlider",
              unit: "%",
              ...workload("Ring radius changes the number and distribution of points inside the bounded full-radius field."),
            },
            zSpread: {
              defaultValue: 31,
              description: "Scales authored thickness from an exactly flat field to an extra-deep, softly bounded relief.",
              label: "Z spread",
              max: 160,
              min: 0,
              orderRole: "spatial",
              step: 1,
              target: "volume.zSpread",
              type: "slider",
              unit: "%",
              ...responsiveness("Z spread updates bounded vertex depth without changing the point count."),
            },
            zBend: {
              defaultValue: -9,
              description: "Bends the main Z dome inward or outward; zero removes the dome while preserving ridge and twist detail.",
              label: "Z bend",
              max: 100,
              min: -100,
              orderRole: "spatial",
              step: 1,
              target: "volume.zBend",
              type: "slider",
              unit: "%",
              ...responsiveness("Z bend reverses the primary dome through one vertex-shader uniform without rebuilding geometry."),
            },
            zTwist: {
              defaultValue: 22,
              description: "Adds a signed multi-turn helical depth field; negative and positive values have opposite handedness.",
              label: "Z twist",
              max: 100,
              min: -100,
              orderRole: "spatial",
              step: 1,
              target: "volume.zTwist",
              type: "slider",
              unit: "%",
              ...responsiveness("Z twist updates the cached vertex depth at a fixed point count."),
            },
            perspective: {
              defaultValue: 84,
              description: "Moves from near-orthographic projection to bounded close-camera foreshortening.",
              label: "Perspective",
              max: 100,
              min: 0,
              orderRole: "strength",
              step: 1,
              target: "volume.perspective",
              type: "slider",
              unit: "%",
              ...responsiveness("Perspective updates one projection uniform without rebuilding geometry."),
            },
          },
          title: "Volume",
        },
        {
          controls: {
            layout: {
              defaultValue: "rings",
              description: "Restructures the same bounded point budget into rings, a sunflower spiral, galaxy arms, or broken arcs.",
              label: "Layout",
              options: [
                { label: "Rings", value: "rings" },
                { label: "Sunflower", value: "phyllotaxis" },
                { label: "Spiral arms", value: "spiral" },
                { label: "Arcs", value: "arcs" },
              ],
              orderRole: "mode",
              target: "pattern.layout",
              type: "select",
              ...responsiveness("Layout redistributes the same bounded ring-derived point budget without exceeding the tested rings workload."),
            },
            density: {
              defaultValue: 88,
              description: "Changes the number of concentric paths and dot samples in the single mosaic form.",
              label: "Density",
              max: 100,
              min: 18,
              orderRole: "primary",
              step: 1,
              target: "pattern.density",
              type: "slider",
              ...workload("Density changes vertex count and rebuilds the procedural geometry buffer."),
            },
            dotSize: {
              defaultValue: 6,
              label: "Dot size",
              max: 18,
              min: 2,
              orderRole: "detail",
              step: 0.5,
              target: "pattern.dotSize",
              type: "slider",
              unit: "px",
              ...workload("Dot size changes point coverage and ring sampling pitch across the complete field."),
            },
            arms: {
              defaultValue: 2,
              description: "Sets how many galaxy arms share the same bounded point budget.",
              label: "Arms",
              max: 8,
              min: 2,
              orderRole: "detail",
              step: 1,
              target: "pattern.arms",
              type: "slider",
              variant: "discrete",
              visibleWhen: { equals: "spiral", target: "pattern.layout" },
              ...responsiveness("Arms redistribute the fixed spiral point budget without increasing vertex count."),
            },
            arcFill: {
              defaultValue: 33,
              description: "Sets how much of each ring the dashed arcs cover; segment count follows Repeats.",
              label: "Arc coverage",
              max: 90,
              min: 15,
              orderRole: "detail",
              step: 1,
              target: "pattern.arcFill",
              type: "slider",
              unit: "%",
              visibleWhen: { equals: "arcs", target: "pattern.layout" },
              ...responsiveness("Arc coverage can only reduce the bounded ring workload; full coverage equals the tested rings case."),
            },
            seed: {
              defaultValue: 6,
              description: "Selects a deterministic color scatter and angular variation.",
              label: "Seed",
              max: 24,
              min: 1,
              orderRole: "detail",
              step: 1,
              target: "pattern.seed",
              type: "slider",
              variant: "discrete",
              ...responsiveness("Seed deterministically rebuilds the existing vertex buffer without increasing workload."),
            },
          },
          title: "Dot Field",
        },
        {
          controls: {
            shape: {
              defaultValue: "disc",
              description: "Draws every sample as a disc, hollow ring, square, diamond, or tangential streak.",
              label: "Dot shape",
              options: [
                { label: "Disc", value: "disc" },
                { label: "Ring", value: "ring" },
                { label: "Square", value: "square" },
                { label: "Diamond", value: "diamond" },
                { label: "Streak", value: "streak" },
              ],
              orderRole: "mode",
              target: "style.dotShape",
              type: "select",
              ...responsiveness("Dot shape switches one fragment-shader mask uniform without rebuilding geometry."),
            },
            taper: {
              defaultValue: -59,
              description: "Grades dot footprint across the field: negative enlarges the core, positive enlarges the rim.",
              label: "Taper",
              max: 100,
              min: -100,
              orderRole: "strength",
              step: 1,
              target: "style.taper",
              type: "slider",
              unit: "%",
              ...responsiveness("Size profile scales points through one vertex-shader uniform without rebuilding geometry."),
            },
            glow: {
              defaultValue: 0,
              description: "Blends additive neon halos around every dot; zero keeps the flat opaque look.",
              label: "Glow",
              max: 100,
              min: 0,
              orderRole: "strength",
              step: 1,
              target: "style.glow",
              type: "slider",
              unit: "%",
              ...responsiveness("Glow switches blend state and one halo uniform at the tested maximum point coverage."),
            },
          },
          title: "Dot Style",
        },
        {
          controls: {
            preset: {
              defaultValue: "ember",
              description: "Applies a curated five-color palette; Custom keeps the editable colors below.",
              label: "Preset",
              options: [
                { label: "Custom", value: "custom" },
                { label: "Neon", value: "neon" },
                { label: "Ember", value: "ember" },
                { label: "Pastel candy", value: "candy" },
                { label: "Sunset", value: "sunset" },
                { label: "Deep sea", value: "sea" },
                { label: "Forest", value: "forest" },
                { label: "Ultraviolet", value: "ultraviolet" },
                { label: "Monochrome", value: "mono" },
              ],
              orderRole: "mode",
              target: "palette.preset",
              type: "select",
              ...responsiveness("Preset repacks vertex colors from a curated palette and preserves geometry."),
            },
            base: {
              defaultValue: "#173A78",
              label: "Base navy",
              orderRole: "color",
              target: "palette.base",
              type: "color",
              visibleWhen: { equals: "custom", target: "palette.preset" },
              ...responsiveness("Palette changes update packed vertex colors and preserve geometry."),
            },
            bright: {
              defaultValue: "#F2F7FF",
              label: "Bright ice",
              orderRole: "color",
              target: "palette.bright",
              type: "color",
              visibleWhen: { equals: "custom", target: "palette.preset" },
              ...responsiveness("Palette changes update packed vertex colors and preserve geometry."),
            },
            cyan: {
              defaultValue: "#19D9EA",
              label: "Cyan",
              orderRole: "color",
              target: "palette.cyan",
              type: "color",
              visibleWhen: { equals: "custom", target: "palette.preset" },
              ...responsiveness("Palette changes update packed vertex colors and preserve geometry."),
            },
            violet: {
              defaultValue: "#B967E8",
              label: "Violet",
              orderRole: "color",
              target: "palette.violet",
              type: "color",
              visibleWhen: { equals: "custom", target: "palette.preset" },
              ...responsiveness("Palette changes update packed vertex colors and preserve geometry."),
            },
            warm: {
              defaultValue: "#FF9B38",
              label: "Warm accent",
              orderRole: "color",
              target: "palette.warm",
              type: "color",
              visibleWhen: { equals: "custom", target: "palette.preset" },
              ...responsiveness("Palette changes update packed vertex colors and preserve geometry."),
            },
          },
          layoutGroups: [
            { columns: 2, controls: ["base", "bright"], layout: "inline" },
            { columns: 2, controls: ["cyan", "violet"], layout: "inline" },
          ],
          title: "Mosaic Palette",
        },
        {
          controls: {
            mode: {
              defaultValue: "spiral",
              description: "Chooses how the palette spreads across the field: radial bands, gradient, sectors, spiral, depth shading, noise patches, or duotone.",
              label: "Mode",
              options: [
                { label: "Bands", value: "bands" },
                { label: "Gradient", value: "gradient" },
                { label: "Sectors", value: "sectors" },
                { label: "Spiral", value: "spiral" },
                { label: "Depth", value: "depth" },
                { label: "Patches", value: "patches" },
                { label: "Duotone", value: "duotone" },
              ],
              orderRole: "mode",
              target: "palette.colorMode",
              type: "select",
              ...responsiveness("Color mode repacks vertex colors deterministically and preserves geometry."),
            },
            highlight: {
              defaultValue: 95,
              description: "Moves the mode-aware bright emphasis: band radius, gradient pivot, sector count, spiral turns, depth contrast, or patch scale.",
              label: "Highlight",
              max: 100,
              min: 0,
              orderRole: "primary",
              step: 1,
              target: "palette.highlight",
              type: "slider",
              unit: "%",
              ...responsiveness("Highlight repacks vertex colors at a fixed vertex count during live drag."),
            },
            accents: {
              defaultValue: 100,
              description: "Scales the scattered warm and violet spark population from none to dense confetti.",
              label: "Accents",
              max: 100,
              min: 0,
              orderRole: "detail",
              step: 1,
              target: "palette.accents",
              type: "slider",
              unit: "%",
              ...responsiveness("Accent density repacks vertex colors at a fixed vertex count during live drag."),
            },
          },
          title: "Coloring",
        },
        {
          controls: {
            type: {
              defaultValue: "ripple",
              description: "Chooses how timeline progress deforms the authored mosaic form.",
              label: "Type",
              options: [
                { label: "Ripple", value: "ripple" },
                { label: "Breathe", value: "breathe" },
                { label: "Twist", value: "twist" },
                { label: "Orbit", value: "orbit" },
                { label: "Flow", value: "flow" },
                { label: "Sweep", value: "sweep" },
                { label: "Pulse", value: "pulse" },
              ],
              orderRole: "mode",
              target: "motion.type",
              type: "select",
              ...responsiveness("Motion type switches shader equations without rebuilding geometry."),
            },
            speed: {
              defaultValue: 2,
              description: "Sets the number of complete animation cycles in one seamless timeline loop.",
              label: "Speed",
              max: 6,
              min: 1,
              orderRole: "primary",
              step: 1,
              target: "motion.speed",
              type: "slider",
              variant: "discrete",
              ...responsiveness("Speed updates the timeline phase uniform and preserves the seamless integer-cycle loop."),
            },
            strength: {
              defaultValue: 46,
              description: "Controls the principal mode-aware planar travel from still to expressive displacement.",
              label: "Amount",
              max: 100,
              min: 0,
              orderRole: "strength",
              step: 1,
              target: "motion.strength",
              type: "slider",
              unit: "%",
              ...responsiveness("Amount updates a WebGL displacement uniform during live drag."),
            },
            wavelength: {
              defaultValue: 29,
              description: "Moves from broad low-frequency motion to tightly repeated spatial waves, beams, and fronts.",
              label: "Frequency",
              max: 100,
              min: 0,
              orderRole: "detail",
              step: 1,
              target: "motion.wavelength",
              type: "slider",
              unit: "%",
              ...responsiveness("Frequency updates the mode-aware spatial phase uniform during live drag."),
            },
          },
          title: "Motion",
        },
        {
          controls: {
            zMotion: {
              defaultValue: 34,
              description: "Sets independent front-to-back travel, from planar motion to deep axial movement.",
              label: "Z motion",
              max: 100,
              min: 0,
              orderRole: "spatial",
              step: 1,
              target: "motion.zMotion",
              type: "slider",
              unit: "%",
              ...responsiveness("Z motion updates the axial displacement uniform during live playback."),
            },
            coreOpening: {
              defaultValue: 56,
              description: "Opens the inner boundary with a concentrated outward pulse that remains distinct from overall Amount.",
              label: "Core opening",
              max: 100,
              min: 0,
              orderRole: "strength",
              step: 1,
              target: "motion.coreOpening",
              type: "slider",
              unit: "%",
              ...responsiveness("Core opening updates a radial force uniform without rebuilding geometry."),
            },
            damping: {
              defaultValue: 23,
              description: "Moves from field-wide motion to a sharply core-localized energy envelope.",
              label: "Falloff",
              max: 100,
              min: 0,
              orderRole: "detail",
              step: 1,
              target: "motion.damping",
              type: "slider",
              unit: "%",
              ...responsiveness("Falloff updates an exponential attenuation uniform without rebuilding vertices."),
            },
            turbulence: {
              defaultValue: 25,
              description: "Adds an independent tangential travel path rather than another radial amplitude.",
              label: "Drift",
              max: 100,
              min: 0,
              orderRole: "advanced",
              step: 1,
              target: "motion.turbulence",
              type: "slider",
              unit: "%",
              ...responsiveness("Drift updates a tangential displacement uniform during playback."),
            },
            ballWeight: {
              defaultValue: 21,
              description: "Adds size-dependent lag, reduced response, downward gravity bias, deeper settling, and heavier point scale.",
              label: "Ball weight",
              max: 100,
              min: 0,
              orderRole: "advanced",
              step: 1,
              target: "motion.ballWeight",
              type: "slider",
              unit: "%",
              ...responsiveness("Ball weight updates deterministic per-point inertia and depth-settling uniforms."),
            },
            sparkle: {
              defaultValue: 22,
              description: "Makes individual dots twinkle in brightness and size with deterministic per-dot phases.",
              label: "Sparkle",
              max: 100,
              min: 0,
              orderRole: "advanced",
              step: 1,
              target: "motion.sparkle",
              type: "slider",
              unit: "%",
              ...responsiveness("Sparkle updates one twinkle uniform evaluated per vertex without rebuilding geometry."),
            },
          },
          title: "Dynamics",
        },
        {
          controls: {
            include: {
              defaultValue: true,
              label: "Include",
              orderRole: "mode",
              target: "export.includeBackground",
              type: "switch",
              ...responsiveness("Background inclusion changes preview clear alpha and PNG compositing."),
            },
            background: {
              defaultValue: "#241814",
              label: false,
              orderRole: "color",
              target: "appearance.background",
              type: "color",
              ...responsiveness("Background color updates the WebGL clear color and export composite."),
            },
          },
          layoutGroups: [
            { columns: 2, controls: ["include", "background"], layout: "inline" },
          ],
          title: "Background",
        },
        {
          controls: {
            format: {
              defaultValue: "png",
              label: "Format",
              options: [
                { label: "PNG", value: "png" },
                { label: "JPG", value: "jpg" },
              ],
              orderRole: "mode",
              target: "export.image.format",
              type: "select",
              ...responsiveness("Image format changes the final encoded file type only."),
            },
            resolution: {
              defaultValue: "4k",
              label: "Resolution",
              options: [
                { label: "2K", value: "2k" },
                { label: "4K", value: "4k" },
                { label: "8K", value: "8k" },
              ],
              orderRole: "detail",
              target: "export.image.resolution",
              type: "select",
              ...workload("Selected image resolution controls final export pixel dimensions up to an 8K long edge."),
            },
          },
          layoutGroups: [
            { columns: 2, controls: ["format", "resolution"], layout: "inline" },
          ],
          title: "Image Export",
        },
        {
          controls: {
            format: {
              defaultValue: "mp4",
              label: "Format",
              options: [
                { label: "MP4", value: "mp4" },
                { label: "WebM", value: "webm" },
              ],
              orderRole: "mode",
              target: "export.video.format",
              type: "select",
              ...responsiveness("Video format selects the supported browser recorder container with safe fallback."),
            },
            resolution: {
              defaultValue: "current",
              label: "Resolution",
              options: [
                { label: "Current", value: "current" },
                { label: "4K", value: "4k" },
              ],
              orderRole: "detail",
              target: "export.video.resolution",
              type: "select",
              ...workload("Video resolution changes frame backing dimensions up to encoder-safe 4K."),
            },
          },
          layoutGroups: [
            { columns: 2, controls: ["format", "resolution"], layout: "inline" },
          ],
          title: "Video Export",
        },
        {
          actionGroup: "primary",
          controls: {
            exports: {
              actions: [
                { icon: "upload-simple", label: "Export Video", value: "export-video" },
                { icon: "upload-simple", label: "Export PNG", value: "export-png" },
              ],
              label: false,
              target: "panel.exports",
              type: "panelActions",
            },
          },
        },
      ],
      title: "Kinetic Circle",
    },
    timeline: {
      defaultDurationSeconds: 8,
      enabled: true,
      mode: "playback",
    },
  },
  persistence: {
    include: ["values", "canvas", "panels", "timeline"],
    key: "toolcraft:kinetic-circle:state:v7",
    storage: "localStorage",
    version: 7,
  },
  settingsTransfer: {
    appId: "kinetic-circle",
    enabled: "auto",
    fileName: "kinetic-circle-settings.json",
  },
  toolbar: {
    history: true,
    radar: true,
    theme: true,
    zoom: true,
  },
});
