import {
  defineToolcraftPerformance,
  type ToolcraftPerformanceConfig,
  type ToolcraftPerformanceScenario,
} from "@/toolcraft/runtime";

const automatedTestName = "requires valid performance coverage for declared workload scenarios";

const volumetricStressValue = {
  ballWeight: 100,
  coreOpening: 100,
  density: 100,
  dotSize: 18,
  glow: 100,
  perspective: 100,
  radiusRange: [0, 100],
  renderScale: 2,
  sparkle: 100,
  speed: 6,
  strength: 100,
  turbulence: 100,
  wavelength: 100,
  zMotion: 100,
  zBend: 100,
  zSpread: 160,
  zTwist: 100,
} as const;

const fullRangeProfile = (
  target: string,
  hardLimit: unknown,
  metric: "custom" | "numeric-max",
) => ({
  hardLimit,
  metric,
  smoothTarget: hardLimit,
  smoothTargetRatio: 1,
  target,
  userFacingRange: "fully-guaranteed" as const,
});

function responsivenessScenario({
  controlLabel,
  id,
  interaction,
  target,
  uiSelector,
}: {
  controlLabel?: string;
  id: string;
  interaction: "control-change" | "control-drag";
  target: string;
  uiSelector?: string;
}): ToolcraftPerformanceScenario {
  return {
    automated: true,
    automatedTestName,
    browser: true,
    browserTestName: `browser perf: kinetic circle ${id}`,
    budget:
      interaction === "control-drag"
        ? { maxFrameGapMs: 100, maxInteractionMs: 700 }
        : { maxFrameGapMs: 100, maxInteractionMs: 700 },
    controlLabel,
    expectedObservable: `${target} changes live rendered output without freezing input or moving the viewport.`,
    fixture: "Default one-circle mosaic at the selected 2× resolution scale.",
    id,
    interaction,
    target,
    uiSelector,
    workload: false,
  };
}

const ordinaryControlScenarios: ToolcraftPerformanceScenario[] = [
  responsivenessScenario({
    controlLabel: "Form",
    id: "shape-form-change",
    interaction: "control-change",
    target: "shape.form",
  }),
  responsivenessScenario({
    controlLabel: "Bend",
    id: "shape-bend-drag",
    interaction: "control-drag",
    target: "shape.bend",
  }),
  responsivenessScenario({
    controlLabel: "Depth",
    id: "shape-depth-drag",
    interaction: "control-drag",
    target: "shape.depth",
  }),
  responsivenessScenario({
    controlLabel: "Repeats",
    id: "shape-repeats-drag",
    interaction: "control-drag",
    target: "shape.repeats",
  }),
  responsivenessScenario({
    controlLabel: "Contour angle",
    id: "shape-rotation-drag",
    interaction: "control-drag",
    target: "shape.rotation",
  }),
  ...[
    ["volume-z-spread-drag", "volume.zSpread", "Z spread"],
    ["volume-z-bend-drag", "volume.zBend", "Z bend"],
    ["volume-z-twist-drag", "volume.zTwist", "Z twist"],
    ["volume-perspective-drag", "volume.perspective", "Perspective"],
  ].map(([id, target, controlLabel]) =>
    responsivenessScenario({ controlLabel, id, interaction: "control-drag", target }),
  ),
  {
    automated: true,
    automatedTestName,
    browser: true,
    browserTestName:
      "browser perf: kinetic circle orientation-handle-drag",
    budget: { maxFrameGapMs: 100, maxInteractionMs: 700, maxLongTaskMs: 220 },
    expectedObservable:
      "Dragging the starter orientation handle reprojects the relief through uniforms without rebuilding geometry or moving the viewport.",
    fixture:
      "Density-100 playing relief at 2× resolution scale with the starter orientation gizmo visible.",
    id: "orientation-handle-drag",
    interaction: "mask-drag",
    target: "view.orbit",
    uiSelector: "[data-testid=\"toolcraft-orientation-gizmo\"]",
    workload: false,
  },
  responsivenessScenario({
    controlLabel: "Seed",
    id: "seed-drag",
    interaction: "control-drag",
    target: "pattern.seed",
  }),
  ...[
    ["layout-change", "pattern.layout", "Layout"],
    ["dot-shape-change", "style.dotShape", "Dot shape"],
    ["palette-preset-change", "palette.preset", "Preset"],
    ["color-mode-change", "palette.colorMode", "Mode"],
  ].map(([id, target, controlLabel]) =>
    responsivenessScenario({ controlLabel, id, interaction: "control-change", target }),
  ),
  ...[
    ["arms-drag", "pattern.arms", "Arms"],
    ["arc-fill-drag", "pattern.arcFill", "Arc coverage"],
    ["taper-drag", "style.taper", "Taper"],
    ["glow-drag", "style.glow", "Glow"],
    ["highlight-drag", "palette.highlight", "Highlight"],
    ["accents-drag", "palette.accents", "Accents"],
    ["sparkle-drag", "motion.sparkle", "Sparkle"],
  ].map(([id, target, controlLabel]) =>
    responsivenessScenario({ controlLabel, id, interaction: "control-drag", target }),
  ),
  ...[
    ["palette-base-change", "palette.base", "Base navy"],
    ["palette-bright-change", "palette.bright", "Bright ice"],
    ["palette-cyan-change", "palette.cyan", "Cyan"],
    ["palette-violet-change", "palette.violet", "Violet"],
    ["palette-warm-change", "palette.warm", "Warm accent"],
    ["background-include-change", "export.includeBackground", "Include"],
    ["background-color-change", "appearance.background", "Background"],
    ["image-format-change", "export.image.format", "Format"],
    ["video-format-change", "export.video.format", "Format"],
    ["motion-type-change", "motion.type", "Type"],
    ["infinity-canvas-change", "canvas.infinity", "Infinity canvas"],
  ].map(([id, target, controlLabel]) =>
    responsivenessScenario({ controlLabel, id, interaction: "control-change", target }),
  ),
  ...[
    ["speed-drag", "motion.speed", "Speed"],
    ["strength-drag", "motion.strength", "Amount"],
    ["wavelength-drag", "motion.wavelength", "Frequency"],
    ["damping-drag", "motion.damping", "Falloff"],
    ["turbulence-drag", "motion.turbulence", "Drift"],
    ["z-motion-drag", "motion.zMotion", "Z motion"],
    ["core-opening-drag", "motion.coreOpening", "Core opening"],
    ["ball-weight-drag", "motion.ballWeight", "Ball weight"],
  ].map(([id, target, controlLabel]) =>
    responsivenessScenario({ controlLabel, id, interaction: "control-drag", target }),
  ),
];

const workloadControlScenarios: ToolcraftPerformanceScenario[] = [
  {
    automated: true,
    automatedTestName,
    browser: true,
    browserTestName:
      "browser perf: kinetic circle volume-radius-range-drag",
    budget: { maxFrameGapMs: 90, maxInteractionMs: 700, maxLongTaskMs: 220 },
    controlLabel: "Ring radius",
    expectedObservable:
      "Dragging both real Ring radius thumbs to the full 0–100% span updates the center opening, outer boundary, vertex count, and pixels live.",
    fixture: "Full 0–100% radial span at Density 100 and 2× resolution scale.",
    id: "volume-radius-range-drag",
    interaction: "control-drag",
    stress: true,
    stressFixture: {
      kind: "max-value",
      loadProfile: fullRangeProfile(
        "volume.radiusRange",
        [0, 100],
        "custom",
      ),
      reason:
        "The full radial span creates the largest useful number of sampled paths.",
      value: [0, 100],
    },
    target: "volume.radiusRange",
    values: { default: [2, 93], max: [0, 100], min: [94, 100] },
    workload: true,
    workloadFixture: {
      kind: "custom",
      loadProfile: fullRangeProfile(
        "volume-radius-baseline",
        { density: 100, renderScale: 2 },
        "custom",
      ),
      reason:
        "Maximum density and backing scale are the independent heavy baseline for rebuilding the full radial field.",
      value: { density: 100, renderScale: 2 },
    },
  },
  {
    automated: true,
    automatedTestName,
    browser: true,
    browserTestName: "browser perf: kinetic circle density-control-drag",
    budget: { maxFrameGapMs: 90, maxInteractionMs: 700, maxLongTaskMs: 220 },
    controlLabel: "Density",
    expectedObservable: "The real Density thumb reaches 100 and vertex count plus pixels change during drag.",
    fixture: "Density 100 at 2× resolution scale.",
    id: "density-control-drag",
    interaction: "control-drag",
    stress: true,
    stressFixture: {
      kind: "high-density",
      loadProfile: fullRangeProfile("pattern.density", 100, "numeric-max"),
      reason: "100 is the exposed maximum and creates the largest useful vertex buffer.",
      value: 100,
    },
    target: "pattern.density",
    values: { default: 88, max: 100, min: 18 },
    workload: true,
    workloadFixture: {
      kind: "custom",
      loadProfile: fullRangeProfile("mosaic-preview-baseline", { renderScale: 2 }, "custom"),
      reason: "The maximum point field must remain responsive at the selected 2× backing scale.",
      value: { renderScale: 2 },
    },
  },
  {
    automated: true,
    automatedTestName,
    browser: true,
    browserTestName: "browser perf: kinetic circle dot-size-control-drag",
    budget: { maxFrameGapMs: 90, maxInteractionMs: 700, maxLongTaskMs: 220 },
    controlLabel: "Dot size",
    expectedObservable: "The real Dot size thumb reaches 18px and point coverage changes during drag.",
    fixture: "Dot size 18px on a density-100 field at 2× resolution scale.",
    id: "dot-size-control-drag",
    interaction: "control-drag",
    stress: true,
    stressFixture: {
      kind: "max-value",
      loadProfile: fullRangeProfile("pattern.dotSize", 18, "numeric-max"),
      reason: "18px is the largest exposed point coverage and ring-pitch value.",
      value: 18,
    },
    target: "pattern.dotSize",
    values: { default: 6, max: 18, min: 2 },
    workload: true,
    workloadFixture: {
      kind: "custom",
      loadProfile: fullRangeProfile(
        "dot-size-preview-baseline",
        { density: 100, renderScale: 2 },
        "custom",
      ),
      reason: "Maximum point count and backing scale create the independent heavy baseline.",
      value: { density: 100, renderScale: 2 },
    },
  },
  {
    automated: true,
    automatedTestName,
    browser: true,
    browserTestName: "browser perf: kinetic circle image-export-8k",
    budget: { maxFrameGapMs: 100, maxInteractionMs: 700, maxLongTaskMs: 250 },
    controlLabel: "Resolution",
    expectedObservable: "Selecting 8K updates the image export resolution while the dense preview remains responsive.",
    fixture: "8K still resolution selection at density 100.",
    id: "image-export-8k",
    interaction: "control-change",
    stress: true,
    stressFixture: {
      kind: "max-value",
      loadProfile: fullRangeProfile("export.image.resolution", "8k", "custom"),
      reason: "8K is the largest exposed still export resolution.",
      value: "8k",
    },
    target: "export.image.resolution",
    values: { default: "4k", max: "8k", min: "2k" },
    workload: true,
    workloadFixture: {
      kind: "high-density",
      loadProfile: fullRangeProfile("pattern.density", 100, "numeric-max"),
      reason: "Still export must include the maximum procedural vertex buffer.",
      value: 100,
    },
  },
  {
    automated: true,
    automatedTestName,
    browser: true,
    browserTestName: "browser perf: kinetic circle video-export-4k",
    budget: { maxFrameGapMs: 100, maxInteractionMs: 700, maxLongTaskMs: 250 },
    controlLabel: "Resolution",
    expectedObservable: "Selecting 4K updates the video export resolution while the dense preview remains responsive.",
    fixture: "4K video resolution selection at density 100.",
    id: "video-export-4k",
    interaction: "control-change",
    stress: true,
    stressFixture: {
      kind: "max-value",
      loadProfile: fullRangeProfile("export.video.resolution", "4k", "custom"),
      reason: "4K is the largest exposed video resolution.",
      value: "4k",
    },
    target: "export.video.resolution",
    values: { default: "current", max: "4k", min: "current" },
    workload: true,
    workloadFixture: {
      kind: "custom",
      loadProfile: fullRangeProfile(
        "video-export-baseline",
        { density: 100, renderScale: 2 },
        "custom",
      ),
      reason: "Maximum dot count and backing scale create the independent heavy encoder-preview baseline.",
      value: { density: 100, renderScale: 2 },
    },
  },
];

const rendererScenarios: ToolcraftPerformanceScenario[] = [
  {
    automated: true,
    automatedTestName,
    browser: true,
    browserTestName: "browser perf: kinetic circle dense-preview-render",
    budget: { maxLongTaskMs: 220, maxPreviewMs: 1200, maxRenderMs: 700 },
    expectedObservable: "One authored circle renders at maximum density with non-empty pixels and a 2× backing size.",
    fixture: "Full radial span, maximum static and animated Z depth, Perspective 100, Ball weight 100, Density 100, Dot size 18px, Amount/Drift/Frequency 100, Speed 6, resolution scale 2, and 1920×1080 canvas.",
    id: "dense-preview-render",
    interaction: "preview-render",
    stress: true,
    stressFixture: {
      kind: "custom",
      loadProfile: fullRangeProfile(
        "dense-preview",
        volumetricStressValue,
        "custom",
      ),
      reason: "This combines the full radial field, largest point count and point coverage, static and animated Z depth, projection, inertia, maximum frequency/drift, loop speed, backing scale, and displacement amplitude.",
      value: volumetricStressValue,
    },
    workload: false,
  },
  {
    automated: true,
    automatedTestName,
    browser: true,
    browserTestName: "browser perf: kinetic circle export-actions",
    budget: { maxExportMs: 8000, maxLongTaskMs: 250 },
    expectedObservable: "Export PNG produces selected-resolution bytes and Export Video reports frame progress without freezing the panel.",
    fixture: "2K PNG and one-second Current-resolution video at default density.",
    id: "export-actions",
    interaction: "export-copy",
    target: "panel.exports",
    uiSelector: "button:has-text(\"Export PNG\")",
    workload: false,
  },
  {
    automated: true,
    automatedTestName,
    browser: true,
    browserTestName: "browser perf: kinetic circle variations-actions",
    budget: { maxFrameGapMs: 100, maxInteractionMs: 700, maxLongTaskMs: 220 },
    expectedObservable:
      "Randomize look rebuilds one bounded geometry buffer and repaints without freezing input or moving the viewport.",
    fixture: "Default mosaic; click Randomize look and Randomize colors once each.",
    id: "variations-actions",
    interaction: "control-change",
    target: "panel.variations",
    uiSelector: "button:has-text(\"Randomize look\")",
    workload: false,
  },
  {
    automated: true,
    automatedTestName,
    browser: true,
    browserTestName: "browser perf: kinetic circle timeline-playback",
    budget: { maxFrameGapMs: 90, maxLongTaskMs: 220 },
    expectedObservable: "Play playback advances phase and pixels while vertex count remains stable.",
    fixture: "Maximum volumetric state at 2× resolution scale during real timeline playback.",
    id: "timeline-playback",
    interaction: "timeline-playback",
    stress: true,
    stressFixture: {
      kind: "custom",
      loadProfile: fullRangeProfile("timeline-playback", volumetricStressValue, "custom"),
      reason: "Playback at the maximum point count, 3D displacement, projection, inertia, and backing scale is the heaviest normal animation.",
      value: volumetricStressValue,
    },
    target: "timeline.playback",
    uiSelector: "[data-slot=\"timeline-playback\"]",
    workload: false,
  },
  {
    automated: true,
    automatedTestName,
    browser: true,
    browserTestName: "browser perf: kinetic circle animation-viewport-drag",
    budget: { maxFrameGapMs: 100, maxInteractionMs: 700, maxLongTaskMs: 220 },
    expectedObservable: "Offset follows the pointer, playback state stays unchanged, and latest frame resumes after release.",
    fixture: "Maximum volumetric mosaic physically dragged during playback at 2× resolution scale.",
    id: "animation-viewport-drag",
    interaction: "animation-viewport-drag",
    stress: true,
    stressFixture: {
      kind: "custom",
      loadProfile: fullRangeProfile("animation-viewport-drag", volumetricStressValue, "custom"),
      reason: "This combines the maximum volumetric renderer and pointer-driven viewport path.",
      value: volumetricStressValue,
    },
    workload: false,
  },
  {
    automated: true,
    automatedTestName,
    browser: true,
    browserTestName: "browser perf: kinetic circle viewport-zoom-stress",
    budget: { maxFrameGapMs: 100, maxInteractionMs: 700, maxLongTaskMs: 220 },
    expectedObservable: "Real zoom changes viewport state without rebuilding geometry or changing playback state.",
    fixture: "Maximum volumetric state at 2× resolution scale while using toolbar zoom during playback.",
    id: "viewport-zoom-stress",
    interaction: "viewport-zoom-stress",
    stress: true,
    stressFixture: {
      kind: "custom",
      loadProfile: fullRangeProfile("viewport-zoom-stress", volumetricStressValue, "custom"),
      reason: "Zooming the heaviest 3D field verifies CSS viewport transforms retain geometry and shader caches.",
      value: volumetricStressValue,
    },
    workload: false,
  },
  {
    automated: true,
    automatedTestName,
    browser: true,
    browserTestName: "browser perf: kinetic circle viewport-stability",
    budget: { maxFrameGapMs: 100, maxInteractionMs: 700 },
    expectedObservable: "Control and timeline interactions do not jump canvas zoom or offset.",
    fixture: "Default field with slider, color, timeline, zoom, and radar interactions.",
    id: "viewport-stability",
    interaction: "viewport-stability",
    target: "canvas.viewport",
    workload: false,
  },
];

export const appPerformance: ToolcraftPerformanceConfig = defineToolcraftPerformance({
  browserCheckPolicy: {
    fallbackRunner: "playwright",
    fallbackWhen: ["agent-browser-unavailable", "ci"],
    preferredRunner: "agent-browser",
  },
  rendererPipeline: {
    interactionInvalidation: [
      {
        interaction: "control-drag",
        invalidates: ["geometry-build", "gpu-preview"],
        mustNotInvalidate: ["shader-program", "export-frame"],
        targets: [
          "shape.bend",
          "shape.depth",
          "shape.repeats",
          "shape.rotation",
          "volume.radiusRange",
          "volume.zSpread",
          "volume.zTwist",
          "pattern.density",
          "pattern.dotSize",
          "pattern.seed",
          "pattern.arms",
          "pattern.arcFill",
          "palette.highlight",
          "palette.accents",
        ],
      },
      {
        interaction: "control-change",
        invalidates: ["geometry-build", "gpu-preview"],
        mustNotInvalidate: ["shader-program", "export-frame"],
        targets: [
          "shape.form",
          "pattern.layout",
          "palette.preset",
          "palette.colorMode",
          "palette.base",
          "palette.bright",
          "palette.cyan",
          "palette.violet",
          "palette.warm",
        ],
      },
      {
        interaction: "control-change",
        invalidates: ["gpu-preview"],
        mustNotInvalidate: ["geometry-build", "shader-program", "export-frame"],
        targets: [
          "motion.type",
          "style.dotShape",
          "canvas.infinity",
          "export.includeBackground",
          "appearance.background",
        ],
      },
      {
        interaction: "mask-drag",
        invalidates: ["gpu-preview"],
        mustNotInvalidate: ["geometry-build", "shader-program", "export-frame"],
        targets: ["view.orbit"],
      },
      {
        interaction: "control-change",
        invalidates: [],
        mustNotInvalidate: ["geometry-build", "shader-program", "gpu-preview", "export-frame"],
        targets: [
          "export.image.format",
          "export.video.format",
        ],
      },
      {
        interaction: "control-drag",
        invalidates: ["gpu-preview"],
        mustNotInvalidate: ["geometry-build", "shader-program", "export-frame"],
        targets: [
          "volume.perspective",
          "volume.zBend",
          "style.taper",
          "style.glow",
          "motion.speed",
          "motion.strength",
          "motion.wavelength",
          "motion.damping",
          "motion.turbulence",
          "motion.zMotion",
          "motion.coreOpening",
          "motion.ballWeight",
          "motion.sparkle",
        ],
      },
      {
        interaction: "animation-frame",
        invalidates: ["gpu-preview"],
        mustNotInvalidate: ["geometry-build", "shader-program", "export-frame"],
        targets: ["timeline.currentTimeSeconds"],
      },
      {
        interaction: "timeline-playback",
        invalidates: ["gpu-preview"],
        mustNotInvalidate: ["geometry-build", "shader-program", "export-frame"],
        targets: ["timeline.playback"],
      },
      {
        interaction: "viewport-drag",
        invalidates: [],
        mustNotInvalidate: ["geometry-build", "shader-program", "gpu-preview", "export-frame"],
        targets: ["canvas.offset"],
      },
      {
        interaction: "viewport-zoom",
        invalidates: [],
        mustNotInvalidate: ["geometry-build", "shader-program", "gpu-preview", "export-frame"],
        targets: ["canvas.zoom"],
      },
      {
        interaction: "export",
        invalidates: ["export-frame"],
        mustNotInvalidate: ["shader-program", "gpu-preview"],
        targets: ["export.image.resolution", "export.video.resolution"],
      },
    ],
    passes: [
      {
        cacheKey: [
          "canvas.size",
          "shape.*",
          "volume.radiusRange",
          "volume.zSpread",
          "volume.zTwist",
          "pattern.*",
          "palette.*",
        ],
        id: "geometry-build",
        inputs: [
          "canvas.size",
          "shape.*",
          "volume.radiusRange",
          "volume.zSpread",
          "volume.zTwist",
          "pattern.*",
          "palette.*",
        ],
        invalidatedBy: [
          "canvas.size",
          "shape.*",
          "volume.radiusRange",
          "volume.zSpread",
          "volume.zTwist",
          "pattern.*",
          "palette.*",
        ],
        kind: "vector-build",
        output: "intermediate",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: ["vertexShaderSource", "fragmentShaderSource", "webgl2.context"],
        id: "shader-program",
        inputs: ["vertexShaderSource", "fragmentShaderSource", "webgl2.context"],
        invalidatedBy: ["renderer.mount"],
        kind: "pixel-transform",
        output: "intermediate",
        quality: "full",
        runsOn: "gpu",
      },
      {
        cacheKey: [
          "geometry-build.buffer",
          "shader-program",
          "volume.perspective",
          "volume.zBend",
          "style.*",
          "motion.*",
          "view.orbit",
          "canvas.renderScale",
        ],
        id: "gpu-preview",
        inputs: [
          "geometry-build.buffer",
          "shader-program",
          "volume.perspective",
          "volume.zBend",
          "style.*",
          "motion.*",
          "view.orbit",
          "canvas.mode",
          "timeline.currentTimeSeconds",
          "canvas.renderScale",
        ],
        invalidatedBy: [
          "volume.perspective",
          "volume.zBend",
          "style.*",
          "motion.*",
          "view.orbit",
          "canvas.mode",
          "timeline.currentTimeSeconds",
          "canvas.renderScale",
          "export.includeBackground",
          "appearance.background",
        ],
        kind: "composite",
        output: "preview",
        quality: "retina",
        runsOn: "gpu",
      },
      {
        id: "export-frame",
        inputs: ["shape.*", "volume.*", "pattern.*", "palette.*", "style.*", "view.orbit", "geometry-build.buffer", "shader-program", "motion.*", "timeline.durationSeconds", "export.*"],
        invalidatedBy: ["shape.*", "volume.*", "motion.*", "view.orbit", "export.image.resolution", "export.video.resolution", "timeline.durationSeconds"],
        kind: "export",
        output: "export",
        quality: "export",
        runsOn: "export-only",
      },
    ],
  },
  rendererStrategy: "webgl",
  rendererTechnique: {
    exportRenderer: "media-recorder",
    fidelityRisks: [
      "GPU point-size limits vary; the exposed dot-size range remains modest and is tested at its maximum.",
      "Unsupported MP4 recording falls back to a supported WebM container without returning corrupt bytes.",
    ],
    layers: [
      {
        content: ["dense-pattern", "geometry", "shader"],
        exportMode: "included",
        id: "kinetic-mosaic-field",
        kind: "product-foreground",
        primitiveCount: "high",
        renderer: "webgl",
        uiSelector: "canvas[data-toolcraft-product-output]",
      },
      {
        content: ["handles"],
        exportMode: "excluded",
        id: "orientation-gizmo",
        kind: "editing-handles",
        primitiveCount: "low",
        renderer: "canvas-2d",
        uiSelector: "[data-testid=\"toolcraft-orientation-gizmo\"]",
      },
      {
        content: ["composite"],
        exportMode: "composited",
        id: "export-composite",
        kind: "export-composite",
        primitiveCount: "low",
        renderer: "canvas-2d",
      },
    ],
    performanceRisks: [
      "Full radial span, Density 100, maximum signed Z bend/spread/twist/motion, point inertia, 2× render scale, playback, and viewport interaction form the largest live workload.",
      "3D orientation and Perspective change camera uniforms and depth projection at the full point count; they must not rebuild geometry.",
      "Orientation orbit and continuous creative-slider drags temporarily lower only the live preview backing to 1× and must restore the selected full backing immediately on release.",
      "8K still and 4K video allocate large temporary backing canvases and are measured separately.",
    ],
    previewExportDifferenceReason:
      "Preview uses persistent WebGL at selected render scale; still export renders the same shader to selected pixels before standard Canvas 2D compositing; video renders deterministic timeline frames to an encoder canvas.",
    previewRenderer: "webgl",
    productRepresentation: "pixel",
    rendererStrategy: "webgl",
    rendererWorkload: "pixel-output",
    sourceRepresentation: "procedural-data",
    whyNotAlternativeStrategies: [
      "SVG/DOM would mutate thousands of nodes per frame.",
      "Canvas 2D would repeat thousands of CPU arc and transform calls per frame.",
      "WebGPU narrows browser availability without improving circular point-sprite fidelity for this bounded field.",
    ],
  },
  rendererWorkload: "pixel-output",
  scenarios: [
    ...workloadControlScenarios,
    ...ordinaryControlScenarios,
    ...rendererScenarios,
  ],
  usesCustomRenderer: true,
  workloadTargets: [
    "volume.radiusRange",
    "pattern.density",
    "pattern.dotSize",
    "export.image.resolution",
    "export.video.resolution",
  ],
});
