import {
  defineCreativeAppsKitPerformance,
  type CreativeAppsKitPerformanceConfig,
} from "@/creative-apps-kit/template-runtime";

const largeMessageFixture = Array.from({ length: 1_000 }, (_, index) =>
  `LINE ${String(index + 1).padStart(4, "0")} VESTABOARD FIELD FILLER TEXT`.padEnd(
    60,
    ".",
  ),
).join("\n");

export const appPerformance: CreativeAppsKitPerformanceConfig = defineCreativeAppsKitPerformance({
  rendererStrategy: "dom",
  rendererTechnique: {
    exportRenderer: "canvas-2d",
    fidelityRisks: [
      "Canvas 2D font metrics can differ slightly from DOM font rendering for the same font picker value.",
    ],
    layers: [
      {
        content: ["composite"],
        exportMode: "included",
        id: "backgroundLayer",
        kind: "background",
        primitiveCount: "low",
        renderer: "dom",
        uiSelector: '[data-testid="vestaboard-background-layer"]',
      },
      {
        content: ["geometry", "text"],
        exportMode: "included",
        id: "productForegroundLayer",
        kind: "product-foreground",
        primitiveCount: "high",
        renderer: "dom",
        uiSelector: '[data-testid="vestaboard-foreground-layer"]',
      },
      {
        content: ["geometry"],
        exportMode: "included",
        id: "edgeOverlayLayer",
        kind: "product-foreground",
        primitiveCount: "high",
        renderer: "dom",
        uiSelector: '[data-testid="vestaboard-edge-overlay-layer"]',
      },
      {
        content: ["composite"],
        exportMode: "composited",
        id: "exportComposite",
        kind: "export-composite",
        primitiveCount: "medium",
        renderer: "canvas-2d",
      },
    ],
    performanceRisks: [
      "Small target cell sizes can create a dense full-canvas grid and stress DOM layout.",
      "Large textarea input and output resizing rebuild the deterministic board model and can stress layout.",
      "Edge highlight opacity distribution and side mode repaint duplicate 1px edge overlay cells across the full DOM grid and Canvas 2D export.",
      "Timeline playback rebuilds the animated phrase frame from source and target messages on every rendered time update.",
      "Video export records a full timeline pass through Canvas 2D and MediaRecorder.",
      "Drum mode computes per-cell drum spin frames with jitter, variance, and wear on every animated frame.",
      "Trail draws a second ghost glyph per actively flipping cell in DOM preview and Canvas 2D export.",
      "Vibration re-applies the foreground layer transform on every animated frame.",
      "Sound synthesizes WebAudio flap clicks from per-frame character diffs and mixes an audio track into video export.",
    ],
    previewExportDifferenceReason:
      "Preview keeps native DOM text crisp while PNG export draws the same board model through the standard retina Canvas 2D helper.",
    previewRenderer: "dom",
    productRepresentation: "mixed",
    rendererStrategy: "dom",
    rendererWorkload: "text-output",
    sourceRepresentation: "mixed",
    whyNotAlternativeStrategies: [
      "SVG would add text measurement complexity without improving the static board layout.",
      "Canvas preview would rasterize semantic text and lose native preview fidelity.",
      "WebGL and WebGPU are unnecessary for a static text grid.",
    ],
  },
  rendererWorkload: "text-output",
  scenarios: [
    {
      automated: true,
      automatedTestName: "perf: vestaboard preview render stays under budget",
      browser: true,
      browserTestName: "browser perf: vestaboard preview render stays under budget",
      budget: { maxPreviewMs: 700 },
      expectedObservable: "The default full-canvas Vestaboard preview is visible without a slow initial render.",
      fixture: "default 1200 by 720 board",
      id: "preview-render",
      interaction: "preview-render",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: settings transfer export stays responsive",
      browser: true,
      browserTestName: "browser perf: settings transfer export stays responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 700 },
      expectedObservable:
        "Export Settings downloads the runtime settings JSON without freezing controls.",
      fixture: "default board settings transfer fixture",
      id: "settings-transfer-export",
      interaction: "control-change",
      target: "runtime.settingsTransfer",
      uiSelector: '[data-slot="panel-actions"]',
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: canvas width change stays responsive",
      browser: true,
      browserTestName: "browser perf: canvas width change stays responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 700 },
      controlLabel: "Canvas width",
      expectedObservable: "Changing Canvas width resizes output without freezing controls.",
      fixture: "large canvas width fixture",
      id: "canvas-width-change",
      interaction: "control-change",
      stressFixture: {
        kind: "large-canvas",
        reason: "A wider canvas increases product output dimensions and export surface.",
        value: 1800,
      },
      target: "canvas.size.width",
      values: { default: 1200, max: 1800, min: 640 },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: canvas height change stays responsive",
      browser: true,
      browserTestName: "browser perf: canvas height change stays responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 700 },
      controlLabel: "Canvas height",
      expectedObservable: "Changing Canvas height resizes output without freezing controls.",
      fixture: "large canvas height fixture",
      id: "canvas-height-change",
      interaction: "control-change",
      stressFixture: {
        kind: "large-canvas",
        reason: "A taller canvas increases product output dimensions and export surface.",
        value: 1200,
      },
      target: "canvas.size.height",
      values: { default: 720, max: 1200, min: 420 },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: tile width drag stays responsive",
      browser: true,
      browserTestName: "browser perf: tile width drag stays responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 800 },
      controlLabel: "Width",
      expectedObservable: "Dragging tile Width updates computed cell geometry and column count smoothly.",
      fixture: "wide tile fixture",
      id: "tile-width-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "high-density",
        reason: "Minimum target tile width creates the densest full-canvas grid.",
        value: 18,
      },
      target: "board.tile.width",
      values: { default: 48, max: 120, min: 18 },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: tile height drag stays responsive",
      browser: true,
      browserTestName: "browser perf: tile height drag stays responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 700 },
      controlLabel: "Height",
      expectedObservable: "Dragging tile Height updates computed cell geometry and row count smoothly.",
      fixture: "tall tile fixture",
      id: "tile-height-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "high-density",
        reason: "Minimum target tile height creates the densest full-canvas grid.",
        value: 24,
      },
      target: "board.tile.height",
      values: { default: 68, max: 150, min: 24 },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: tile gap drag stays responsive",
      browser: true,
      browserTestName: "browser perf: tile gap drag stays responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 700 },
      controlLabel: "Gap",
      expectedObservable: "Dragging tile Gap updates spacing and computed cell dimensions smoothly.",
      fixture: "large gap fixture",
      id: "tile-gap-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "high-density",
        reason: "Negative one pixel gap creates the tightest full-canvas overlap.",
        value: -1,
      },
      target: "board.tile.gap",
      values: { default: 8, max: 30, min: -1 },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: cell radius drag stays responsive",
      browser: true,
      browserTestName: "browser perf: cell radius drag stays responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 700 },
      controlLabel: "Radius",
      expectedObservable: "Dragging Radius repaints computed cell rounding smoothly.",
      fixture: "rounded cell fixture",
      id: "cell-radius-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "Maximum radius stresses rounded clipping and border painting.",
        value: 80,
      },
      target: "board.cell.radius",
      values: { default: 0, max: 80, min: 0 },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: cell fill color change stays responsive",
      browser: true,
      browserTestName: "browser perf: cell fill color change stays responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 600 },
      controlLabel: "Cell fill",
      expectedObservable: "Changing Cell fill color repaints cell backgrounds smoothly.",
      fixture: "cell fill color fixture",
      id: "cell-fill-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        reason: "A saturated cell fill color makes cell repaint visible across the grid.",
        value: { hex: "#2255FF" },
      },
      target: "board.cell.fill",
      values: {
        default: { hex: "#FFFFFF" },
        max: { hex: "#2255FF" },
        min: { hex: "#000000" },
      },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: cell fill opacity range drag stays responsive",
      browser: true,
      browserTestName: "browser perf: cell fill opacity range drag stays responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 700 },
      controlLabel: "Cell opacity",
      expectedObservable: "Dragging Cell opacity range updates seeded cell background alpha smoothly.",
      fixture: "cell fill opacity range fixture",
      id: "cell-fill-opacity-range-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "Full opacity range exercises the widest alpha distribution across cells.",
        value: [0, 100],
      },
      target: "board.cell.fillOpacityRange",
      values: { default: [0, 0], max: [0, 100], min: [0, 0] },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: cell fill seed drag stays responsive",
      browser: true,
      browserTestName: "browser perf: cell fill seed drag stays responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 700 },
      controlLabel: "Cell seed",
      expectedObservable: "Dragging Cell seed regenerates cell background alpha smoothly.",
      fixture: "cell fill seed fixture",
      id: "cell-fill-seed-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "Maximum seed value regenerates deterministic alpha for every computed cell.",
        value: 9999,
      },
      target: "board.cell.fillSeed",
      values: { default: 313, max: 9999, min: 1 },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: bottom opacity range drag stays responsive",
      browser: true,
      browserTestName: "browser perf: bottom opacity range drag stays responsive",
      budget: { maxFrameGapMs: 90, maxInteractionMs: 800 },
      controlLabel: "Bottom opacity",
      expectedObservable: "Dragging Bottom opacity range updates lower-edge alpha smoothly.",
      fixture: "bottom opacity range fixture",
      id: "bottom-opacity-range-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "Full bottom opacity range exercises the widest lower-edge alpha distribution across cells.",
        value: [0, 100],
      },
      target: "board.cell.bottomHighlightOpacityRange",
      values: { default: [0, 0], max: [0, 100], min: [0, 0] },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: bottom seed drag stays responsive",
      browser: true,
      browserTestName: "browser perf: bottom seed drag stays responsive",
      budget: { maxFrameGapMs: 90, maxInteractionMs: 800 },
      controlLabel: "Bottom seed",
      expectedObservable: "Dragging Bottom seed regenerates deterministic lower-edge alpha smoothly.",
      fixture: "bottom seed fixture",
      id: "bottom-seed-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "Maximum seed value regenerates bottom highlight values for every computed cell.",
        value: 9999,
      },
      target: "board.cell.bottomHighlightSeed",
      values: { default: 421, max: 9999, min: 1 },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: bottom fill canvas drag stays responsive",
      browser: true,
      browserTestName: "browser perf: bottom fill canvas drag stays responsive",
      budget: { maxFrameGapMs: 90, maxInteractionMs: 800 },
      controlLabel: "Fill canvas",
      expectedObservable: "Dragging Fill canvas changes highlighted edge cell coverage smoothly.",
      fixture: "bottom fill canvas fixture",
      id: "bottom-fill-canvas-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "Full Fill canvas draws bottom edge highlights on all selected overlay cells.",
        value: 100,
      },
      target: "board.cell.bottomHighlightFillCanvas",
      values: { default: 100, max: 100, min: 0 },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: cell border color opacity change stays responsive",
      browser: true,
      browserTestName: "browser perf: cell border color opacity change stays responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 800 },
      controlLabel: "Cell border",
      expectedObservable: "Changing Cell border color opacity repaints cell outlines smoothly.",
      fixture: "cell border color opacity fixture",
      id: "cell-border-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        reason: "Opaque cell border repaints every computed cell outline.",
        value: { hex: "#FF5500", opacity: 100 },
      },
      target: "board.cell.border",
      values: {
        default: { hex: "#FFFFFF", opacity: 28 },
        max: { hex: "#FF5500", opacity: 100 },
        min: { hex: "#FFFFFF", opacity: 0 },
      },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: large message change stays responsive",
      browser: true,
      browserTestName: "browser perf: large message change stays responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 1800 },
      controlLabel: "Message",
      expectedObservable: "Pasting a large message commits without blocking the board preview.",
      fixture: "large multiline message fixture",
      id: "message-large-text-change",
      interaction: "control-change",
      stressFixture: {
        kind: "large-text",
        minChars: 50_000,
        minLines: 1_000,
        reason: "The textarea is the only unbounded user text input and must handle large pasted text.",
        value: largeMessageFixture,
      },
      target: "board.text.message",
      values: { default: "", max: largeMessageFixture, min: "" },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: large target message change stays responsive",
      browser: true,
      browserTestName: "browser perf: large target message change stays responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 1800 },
      controlLabel: "Target message",
      expectedObservable:
        "Pasting a large target message commits without blocking the animated board preview.",
      fixture: "large multiline target message fixture",
      id: "target-message-large-text-change",
      interaction: "control-change",
      stressFixture: {
        kind: "large-text",
        minChars: 50_000,
        minLines: 1_000,
        reason:
          "The target textarea is the second unbounded user text input and drives phrase transform generation.",
        value: largeMessageFixture,
      },
      target: "board.text.targetMessage",
      values: { default: "", max: largeMessageFixture, min: "" },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: final hold drag stays responsive",
      browser: true,
      browserTestName: "browser perf: final hold drag stays responsive",
      budget: { maxFrameGapMs: 90, maxInteractionMs: 800 },
      controlLabel: "Final hold",
      expectedObservable:
        "Dragging Final hold updates the split phrase/background timeline progress smoothly.",
      fixture: "final hold split progress fixture",
      id: "final-hold-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason:
          "Maximum Final hold compresses the phrase transform into the smallest active window while the field keeps animating.",
        value: 8,
      },
      target: "board.text.finalHoldSeconds",
      values: { default: 0, max: 8, min: 0 },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: duration spread drag stays responsive",
      browser: true,
      browserTestName: "browser perf: duration spread drag stays responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 900 },
      controlLabel: "Duration spread",
      expectedObservable:
        "Dragging Duration spread updates outgoing phrase character overlap smoothly.",
      fixture: "parallel phrase duration spread fixture",
      id: "letter-duration-range-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason:
          "A wide duration spread exercises the broadest per-letter flicker timing distribution during playback.",
        value: [5, 95],
      },
      target: "board.text.letterDurationRange",
      values: { default: [14, 32], max: [5, 95], min: [5, 5] },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: letter speed drag stays responsive",
      browser: true,
      browserTestName: "browser perf: letter speed drag stays responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 900 },
      controlLabel: "Letter speed",
      expectedObservable:
        "Dragging Letter speed updates outgoing phrase character launch density smoothly.",
      fixture: "parallel phrase letter speed fixture",
      id: "letter-speed-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason:
          "Maximum letter speed stresses dense simultaneous outgoing letter flicker during playback.",
        value: 100,
      },
      target: "board.text.letterSpeed",
      values: { default: 55, max: 100, min: 1 },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: outgoing opacity range drag stays responsive",
      browser: true,
      browserTestName: "browser perf: outgoing opacity range drag stays responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 900 },
      controlLabel: "Outgoing opacity",
      expectedObservable:
        "Dragging Outgoing opacity updates flipping phrase character alpha smoothly.",
      fixture: "removing phrase character opacity fixture",
      id: "outgoing-opacity-range-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason:
          "A full outgoing opacity range stresses alpha updates on active removal characters.",
        value: [0, 100],
      },
      target: "board.text.outgoingOpacityRange",
      values: { default: [35, 100], max: [0, 100], min: [0, 0] },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: flash color count drag stays responsive",
      browser: true,
      browserTestName: "browser perf: flash color count drag stays responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 900 },
      controlLabel: "Flash colors",
      expectedObservable:
        "Dragging Flash colors enables animated phrase fill flashes without layout jank.",
      fixture: "main text flash color count fixture",
      id: "message-flash-color-count-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "Four active flash colors exercises all animated phrase fill palette slots.",
        value: 4,
      },
      target: "board.text.flashColorCount",
      values: { default: 0, max: 4, min: 0 },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: flash frequency drag stays responsive",
      browser: true,
      browserTestName: "browser perf: flash frequency drag stays responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 900 },
      controlLabel: "Flash frequency",
      expectedObservable:
        "Dragging Flash frequency changes animated phrase fill flash coverage smoothly.",
      fixture: "main text flash frequency fixture",
      id: "message-flash-frequency-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "Flash frequency 100 can fill every eligible animated phrase cell.",
        value: 100,
      },
      target: "board.text.flashFrequency",
      values: { default: 0, max: 100, min: 0 },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: flash palette color change stays responsive",
      browser: true,
      browserTestName: "browser perf: flash palette color change stays responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 700 },
      controlLabel: "Flash 1",
      expectedObservable:
        "Changing Flash 1 repaints animated phrase fill flashes smoothly.",
      fixture: "main text flash palette fixture",
      id: "message-flash-color-change",
      interaction: "control-change",
      target: "board.text.flashColor1",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: flash palette color 2 change stays responsive",
      browser: true,
      browserTestName: "browser perf: flash palette color 2 change stays responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 700 },
      controlLabel: "Flash 2",
      expectedObservable:
        "Changing Flash 2 repaints second-slot animated phrase fill flashes smoothly.",
      fixture: "main text flash palette fixture",
      id: "message-flash-color-2-change",
      interaction: "control-change",
      target: "board.text.flashColor2",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: flash palette color 3 change stays responsive",
      browser: true,
      browserTestName: "browser perf: flash palette color 3 change stays responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 700 },
      controlLabel: "Flash 3",
      expectedObservable:
        "Changing Flash 3 repaints third-slot animated phrase fill flashes smoothly.",
      fixture: "main text flash palette fixture",
      id: "message-flash-color-3-change",
      interaction: "control-change",
      target: "board.text.flashColor3",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: flash palette color 4 change stays responsive",
      browser: true,
      browserTestName: "browser perf: flash palette color 4 change stays responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 700 },
      controlLabel: "Flash 4",
      expectedObservable:
        "Changing Flash 4 repaints fourth-slot animated phrase fill flashes smoothly.",
      fixture: "main text flash palette fixture",
      id: "message-flash-color-4-change",
      interaction: "control-change",
      target: "board.text.flashColor4",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: main font picker change stays responsive",
      browser: true,
      browserTestName: "browser perf: main font picker change stays responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 1000 },
      controlLabel: "Main font",
      expectedObservable: "Changing main font size updates permanent phrase text without jank.",
      fixture: "large main font fixture",
      id: "main-font-picker-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        reason: "A large main font size stresses permanent phrase text layout and clipping.",
        value: {
          fontId: "inter",
          fontSize: 96,
          fontWeight: "900",
          letterSpacing: "widest",
          lineHeight: "loose",
        },
      },
      target: "board.text.messageTypography",
      values: {
        default: {
          fontId: "inter",
          fontSize: 34,
          fontWeight: "700",
          letterSpacing: "normal",
          lineHeight: "none",
        },
        max: {
          fontId: "inter",
          fontSize: 96,
          fontWeight: "900",
          letterSpacing: "widest",
          lineHeight: "loose",
        },
        min: {
          fontId: "inter",
          fontSize: 12,
          fontWeight: "400",
          letterSpacing: "tight",
          lineHeight: "none",
        },
      },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: background font picker change stays responsive",
      browser: true,
      browserTestName: "browser perf: background font picker change stays responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 1000 },
      controlLabel: "Background font",
      expectedObservable: "Changing background font size updates random field text without jank.",
      fixture: "large background font fixture",
      id: "background-font-picker-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        reason: "A large background font size stresses text layout across every filled random field cell.",
        value: {
          fontId: "inter",
          fontSize: 96,
          fontWeight: "900",
          letterSpacing: "widest",
          lineHeight: "loose",
        },
      },
      target: "field.typography",
      values: {
        default: {
          fontId: "inter",
          fontSize: 34,
          fontWeight: "700",
          letterSpacing: "normal",
          lineHeight: "none",
        },
        max: {
          fontId: "inter",
          fontSize: 96,
          fontWeight: "900",
          letterSpacing: "widest",
          lineHeight: "loose",
        },
        min: {
          fontId: "inter",
          fontSize: 12,
          fontWeight: "400",
          letterSpacing: "tight",
          lineHeight: "none",
        },
      },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: start fill drag stays responsive",
      browser: true,
      browserTestName: "browser perf: start fill drag stays responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 700 },
      controlLabel: "Start fill",
      expectedObservable: "Dragging Start fill changes first-frame random occupancy smoothly.",
      fixture: "start-frame random field fixture",
      id: "field-start-fill-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "Start fill 100 renders a character in every non-message cell at timeline start.",
        value: 100,
      },
      target: "field.fillStart",
      values: { default: 0, max: 100, min: 0 },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: end fill drag stays responsive",
      browser: true,
      browserTestName: "browser perf: end fill drag stays responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 700 },
      controlLabel: "End fill",
      expectedObservable: "Dragging End fill changes final-frame random occupancy smoothly.",
      fixture: "end-frame random field fixture",
      id: "field-end-fill-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "End fill 100 renders a character in every non-message cell at timeline end.",
        value: 100,
      },
      target: "field.fillEnd",
      values: { default: 42, max: 100, min: 0 },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: field duration range drag stays responsive",
      browser: true,
      browserTestName: "browser perf: field duration range drag stays responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 700 },
      controlLabel: "Field duration",
      expectedObservable: "Dragging Field duration changes background flip timing smoothly.",
      fixture: "animated random field duration fixture",
      id: "field-duration-range-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason:
          "A wide Field duration range keeps more changing background cells in flicker states during timeline playback.",
        value: [95, 95],
      },
      target: "field.durationRange",
      values: { default: [10, 45], max: [95, 95], min: [5, 5] },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: field speed drag stays responsive",
      browser: true,
      browserTestName: "browser perf: field speed drag stays responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 700 },
      controlLabel: "Field speed",
      expectedObservable: "Dragging Field speed changes background flicker rate smoothly.",
      fixture: "animated random field speed fixture",
      id: "field-speed-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason:
          "Maximum Field speed creates the highest active background flicker bucket count.",
        value: 100,
      },
      target: "field.speed",
      values: { default: 55, max: 100, min: 1 },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: flip mode change stays responsive",
      browser: true,
      browserTestName: "browser perf: flip mode change stays responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 900 },
      controlLabel: "Flip mode",
      expectedObservable:
        "Switching Flip mode swaps every animated cell between drum and random engines smoothly.",
      fixture: "animated phrase flip mode fixture",
      id: "flip-mode-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        reason:
          "Drum mode computes per-cell drum spins with jitter, variance, and wear for every animated cell.",
        value: "drum",
      },
      target: "board.flip.mode",
      values: { default: "random", max: "drum", min: "random" },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: wear drag stays responsive",
      browser: true,
      browserTestName: "browser perf: wear drag stays responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 900 },
      controlLabel: "Wear",
      expectedObservable:
        "Dragging Wear reshapes sticky drum spin timelines smoothly during playback.",
      fixture: "drum mode wear fixture",
      id: "flip-wear-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "Full wear inserts a sticky pause into every eligible drum spin.",
        value: 100,
      },
      target: "board.flip.wear",
      values: { default: 12, max: 100, min: 0 },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: trail drag stays responsive",
      browser: true,
      browserTestName: "browser perf: trail drag stays responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 900 },
      controlLabel: "Trail",
      expectedObservable:
        "Dragging Trail changes ghost glyph alpha for actively flipping cells smoothly.",
      fixture: "animated trail fixture",
      id: "flip-trail-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "Maximum trail draws a ghost glyph for every actively flipping cell.",
        value: 100,
      },
      target: "board.flip.trailOpacity",
      values: { default: 30, max: 100, min: 0 },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: vibration drag stays responsive",
      browser: true,
      browserTestName: "browser perf: vibration drag stays responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 900 },
      controlLabel: "Vibration",
      expectedObservable:
        "Dragging Vibration updates the sub-pixel board shake offset smoothly during playback.",
      fixture: "animated vibration fixture",
      id: "flip-shake-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason:
          "Maximum vibration recomputes the board offset on every animated frame with full amplitude.",
        value: 100,
      },
      target: "board.flip.shake",
      values: { default: 25, max: 100, min: 0 },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: sound toggle stays responsive",
      browser: true,
      browserTestName: "browser perf: sound toggle stays responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 700 },
      controlLabel: "Sound",
      expectedObservable:
        "Toggling Sound arms or disarms WebAudio flap clicks without freezing controls.",
      fixture: "sound switch fixture",
      id: "sound-toggle",
      interaction: "control-change",
      target: "board.sound.enabled",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: sound volume drag stays responsive",
      browser: true,
      browserTestName: "browser perf: sound volume drag stays responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 700 },
      controlLabel: "Volume",
      expectedObservable:
        "Dragging Volume changes the WebAudio master gain without renderer work.",
      fixture: "sound volume fixture",
      id: "sound-volume-drag",
      interaction: "control-drag",
      target: "board.sound.volume",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: uppercase toggle stays responsive",
      browser: true,
      browserTestName: "browser perf: uppercase toggle stays responsive",
      budget: { maxFrameGapMs: 90, maxInteractionMs: 800 },
      controlLabel: "Uppercase",
      expectedObservable:
        "Toggling Uppercase remaps the phrase text and rebuilds the board model smoothly.",
      fixture: "uppercase message fixture",
      id: "uppercase-toggle",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        reason:
          "Uppercase on remaps every Message and Target message character before layout.",
        value: true,
      },
      target: "board.text.uppercase",
      values: { default: false, max: true, min: false },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: text color change stays responsive",
      browser: true,
      browserTestName: "browser perf: text color change stays responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 600 },
      controlLabel: "Text",
      expectedObservable: "Changing Text color repaints characters without moving the viewport.",
      fixture: "text color fixture",
      id: "text-color-change",
      interaction: "control-change",
      target: "board.text.color",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: opacity range drag stays responsive",
      browser: true,
      browserTestName: "browser perf: opacity range drag stays responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 700 },
      controlLabel: "Opacity",
      expectedObservable: "Dragging Opacity range updates filler alpha smoothly.",
      fixture: "opacity range fixture",
      id: "opacity-range-drag",
      interaction: "control-drag",
      target: "field.opacityRange",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: seed drag stays responsive",
      browser: true,
      browserTestName: "browser perf: seed drag stays responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 700 },
      controlLabel: "Seed",
      expectedObservable: "Dragging Seed regenerates deterministic filler without jank.",
      fixture: "seed fixture",
      id: "seed-drag",
      interaction: "control-drag",
      target: "field.seed",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: background color change stays responsive",
      browser: true,
      browserTestName: "browser perf: background color change stays responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 600 },
      controlLabel: "Background",
      expectedObservable: "Changing Background color repaints preview without moving cells.",
      fixture: "background color fixture",
      id: "background-color-change",
      interaction: "control-change",
      target: "appearance.background",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: video format change stays responsive",
      browser: true,
      browserTestName: "browser perf: video format change stays responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 800 },
      controlLabel: "Format",
      expectedObservable: "Changing video Format updates the export setting without moving cells.",
      fixture: "video format fixture",
      id: "video-format-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        reason: "MP4 exercises the explicit non-default container option and fallback path.",
        value: "mp4",
      },
      target: "export.video.format",
      values: { default: "auto", max: "mp4", min: "webm" },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: video quality change stays responsive",
      browser: true,
      browserTestName: "browser perf: video quality change stays responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 800 },
      controlLabel: "Quality",
      expectedObservable: "Changing video Quality updates export scale settings responsively.",
      fixture: "video quality fixture",
      id: "video-quality-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        reason: "4K quality increases the eventual export canvas scale.",
        value: "4k",
      },
      target: "export.video.quality",
      values: { default: "high", max: "4k", min: "high" },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: include background toggle stays responsive",
      browser: true,
      browserTestName: "browser perf: include background toggle stays responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 500 },
      controlLabel: "Background",
      expectedObservable: "Toggling PNG background inclusion stays responsive.",
      fixture: "include background switch fixture",
      id: "include-background-toggle",
      interaction: "control-change",
      target: "export.includeBackground",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: export actions stay under budget",
      browser: true,
      browserTestName: "browser perf: export actions stay under budget",
      budget: { maxExportMs: 8000 },
      expectedObservable: "Export Video and Export PNG produce delivery bytes within budget.",
      fixture: "timeline export fixture",
      id: "export-actions",
      interaction: "export-copy",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: phrase animation frames stay under budget",
      browser: true,
      browserTestName: "browser perf: phrase animation frames stay under budget",
      budget: { maxFrameGapMs: 90, maxLongTaskMs: 160 },
      expectedObservable:
        "Playback-driven phrase animation samples visible frames without long tasks.",
      fixture: "phrase transform playback fixture",
      id: "phrase-animation-frames",
      interaction: "animation-frame",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: phrase animation viewport drag stays responsive",
      browser: true,
      browserTestName: "browser perf: phrase animation viewport drag stays responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 2000, maxLongTaskMs: 180 },
      expectedObservable:
        "Dragging the canvas viewport during playback keeps the animated board responsive.",
      fixture: "animated viewport drag fixture",
      id: "phrase-animation-viewport-drag",
      interaction: "animation-viewport-drag",
      stress: true,
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: vestaboard viewport stays stable",
      browser: true,
      browserTestName: "browser perf: vestaboard viewport stays stable",
      budget: { maxFrameGapMs: 80 },
      expectedObservable: "Control changes do not jump canvas zoom or offset.",
      fixture: "viewport stability fixture",
      id: "viewport-stability",
      interaction: "viewport-stability",
      target: "board.tile.width",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: vestaboard viewport zoom stress stays responsive",
      browser: true,
      browserTestName: "browser perf: vestaboard viewport zoom stress stays responsive",
      budget: { maxFrameGapMs: 90, maxInteractionMs: 900, maxLongTaskMs: 160 },
      expectedObservable: "Toolbar zoom stress keeps the text-output renderer responsive.",
      fixture: "zoom stress fixture",
      id: "viewport-zoom-stress",
      interaction: "viewport-zoom-stress",
      stress: true,
      workload: false,
    },
  ],
  usesCustomRenderer: true,
  workloadTargets: [
    "canvas.size.width",
    "canvas.size.height",
    "board.tile.width",
    "board.tile.height",
    "board.tile.gap",
    "board.cell.radius",
    "board.cell.fill",
    "board.cell.fillOpacityRange",
    "board.cell.fillSeed",
    "board.cell.bottomHighlightOpacityRange",
    "board.cell.bottomHighlightFillCanvas",
    "board.cell.bottomHighlightSeed",
    "board.cell.border",
    "board.text.message",
    "board.text.targetMessage",
    "board.text.finalHoldSeconds",
    "board.text.letterDurationRange",
    "board.text.letterSpeed",
    "board.text.outgoingOpacityRange",
    "board.text.flashColorCount",
    "board.text.flashFrequency",
    "board.text.messageTypography",
    "board.text.uppercase",
    "board.flip.mode",
    "board.flip.wear",
    "board.flip.trailOpacity",
    "board.flip.shake",
    "field.typography",
    "field.fillStart",
    "field.fillEnd",
    "field.durationRange",
    "field.speed",
    "export.video.quality",
  ],
});
