/**
 * Compatible product values from:
 * /Users/kusnizza/Downloads/grass-studio-settings (20).json
 *
 * Exported `{ hex }` colors are normalized to the string value expected by the
 * Toolcraft color controls. Canvas and transient timeline transport remain
 * schema-owned.
 */
export const grassStartStateV21 = {
  "preview.bladeCount": 6000,
  "preview.lawnBladeCount": 12000,
  "view.orientation": {
    position: [
      0.0924051962359733, 0.5138578798477916, 0.8663783001823914,
    ],
    up: [0, 1, 0],
  },
  "environment.preset": "sunrise",
  "environment.intensity": 250,
  "environment.rotationX": -11,
  "environment.rotation": 100,
  "environment.rotationZ": 133,
  "environment.visible": false,
  "environment.backgroundBlur": 30,
  "environment.keyColor": "#F2AB26",
  "environment.keyStrength": 197,
  "environment.fillColor": "#E57E43",
  "environment.fillStrength": 31,
  "environment.rimColor": "#DB831F",
  "environment.rimStrength": 172,
  "environment.exposure": 151,
  "environment.sunPatchEnabled": true,
  "environment.sunPatchScale": 1.2,
  "environment.sunPatchCoverage": 54,
  "environment.sunPatchSoftness": 61,
  "environment.sunPatchStrength": 156,
  "environment.sunPatchOffset": { x: "-0.12", y: "0.05" },
  "environment.sunPatchSeed": 50,
  "environment.sceneContrast": 200,
  "environment.sceneSaturation": 96,
  "environment.highlightWarmth": 75,
  "environment.shadowCoolness": 0,
  "field.width": 7,
  "field.depth": 5,
  "field.shapeRoundness": 95,
  "field.edgeIrregularity": 23,
  "field.showGround": true,
  "terrain.noiseOffset": [-10.576542541058394, 5.231356534090908],
  "terrain.noiseScale": 0.19,
  "terrain.detail": 5,
  "terrain.roughness": 43,
  "terrain.seed": 86,
  "terrain.heightLevels": [61, 87],
  "terrain.maxHeight": 1.9,
  "appearance.groundColor": "#86BD70",
  "surface.cloverColor": "#51D520",
  "surface.brightness": 214,
  "surface.receiveShadows": true,
  "surface.textureScale": 1.55,
  "surface.normalStrength": 150,
  "surface.roughness": 41,
  "surface.colorContrast": 119,
  "surface.colorSaturation": 55,
  "surface.cloverTextureScale": 0.85,
  "surface.cloverNormalStrength": 150,
  "surface.cloverRoughness": 32,
  "surface.cloverMaskOffset": [
    3.4748517335766413, -1.6354462594696968,
  ],
  "surface.cloverMaskScale": 0.44,
  "surface.cloverMaskDetail": 3,
  "surface.cloverMaskRoughness": 44,
  "surface.cloverMaskSeed": 41,
  "surface.cloverMaskLevels": [42, 62],
  "surface.bendEnabled": true,
  "surface.bendDepth": 0.05,
  "surface.bendWidth": 5,
  "surface.bendRoundness": 100,
  "surface.bendSmoothness": 7,
  "surface.edgeFadeWidth": 0,
  "surface.edgeFadeStrength": 10,
  "groundShadow.offsetY": -0.41,
  "groundShadow.offsetZ": 0.65,
  "groundShadow.scale": 73,
  "groundShadow.blur": 0.84,
  "groundShadow.color": "#0C1F0A",
  "groundShadow.strength": 48,
  "lawn.enabled": true,
  "lawn.densityMax": 36000,
  "lawn.distanceMin": 0.0075,
  "lawn.depthOffset": 0.025,
  "lawn.seed": 26,
  "lawn.distributionOffset": [-5.039433166058394, -0.845614346590909],
  "lawn.distributionScale": 0.18,
  "lawn.distributionDetail": 3,
  "lawn.distributionRoughness": 55,
  "lawn.distributionSeed": 37,
  "lawn.distributionLevels": [44, 87],
  "lawn.curveResolution": 5,
  "lawn.thickness": 0.015,
  "lawn.heightRange": [0.0585, 0.16],
  "lawn.taperEnd": 99,
  "lawn.tilt2d": -1,
  "lawn.use3d": true,
  "lawn.pbrRoughness": 91,
  "lawn.colorVariation": 88,
  "lawn.colorContrast": 167,
  "lawn.colorSaturation": 157,
  "lawn.bladeGradient": {
    angle: 90,
    gradientType: "linear",
    stops: [
      { color: "#1c3c29", opacity: 100, position: "27%" },
      { color: "#506b3f", opacity: 100, position: "77%" },
      { color: "#a6be66", opacity: 100, position: "100%" },
    ],
  },
  "lawn.instanceColor1": "#0D680F",
  "lawn.instanceColorWeight1": 46,
  "lawn.instanceColor2": "#538b32",
  "lawn.instanceColorWeight2": 53,
  "lawn.instanceColor3": "#78934d",
  "lawn.instanceColorWeight3": 60,
  "grass.enabled": true,
  "field.densityMax": 24000,
  "field.distanceMin": 0.02,
  "grass.depthOffset": -0.02,
  "field.seed": 149410,
  "field.distributionOffset": [8.427050068430662, 3.426609848484848],
  "field.distributionScale": 0.29,
  "field.distributionDetail": 1,
  "field.distributionRoughness": 90,
  "field.distributionSeed": 64,
  "field.distributionLevels": [50, 83],
  "field.alignToNormals": 82,
  "field.randomRotation": 100,
  "field.topFacingOnly": false,
  "field.topFacingCoverage": 83,
  "field.topFacingFade": 94,
  "blade.curveResolution": 8,
  "blade.thickness": 0.015,
  "blade.heightRange": [0.3, 0.6],
  "blade.taperEnd": 86,
  "blade.tilt2d": -43,
  "blade.use3d": true,
  "appearance.pbrRoughness": 100,
  "appearance.colorVariation": 59,
  "appearance.colorContrast": 131,
  "appearance.colorSaturation": 200,
  "appearance.bladeGradient": {
    angle: 90,
    gradientType: "linear",
    stops: [
      { color: "#0D5E2F", opacity: 100, position: "18%" },
      { color: "#09863E", opacity: 100, position: "56%" },
      { color: "#2ABE13", opacity: 100, position: "79%" },
      { color: "#CDF684", opacity: 100, position: "98%" },
    ],
  },
  "appearance.instanceColor1": "#3BD214",
  "appearance.instanceColorWeight1": 59,
  "appearance.instanceColor2": "#419315",
  "appearance.instanceColorWeight2": 69,
  "appearance.instanceColor3": "#0C691F",
  "appearance.instanceColorWeight3": 100,
  "scan.tufted.enabled": true,
  "scan.tufted.count": 1000,
  "scan.tufted.sizeRange": [0.45, 0.7],
  "scan.tufted.clumping": 70,
  "scan.tufted.seed": 71,
  "scan.tufted.surfaceOffset": 0.045,
  "scan.tufted.pbrTint": "#FFFFFF",
  "scan.tufted.pbrBrightness": 86,
  "scan.tufted.colorContrast": 108,
  "scan.tufted.colorSaturation": 200,
  "scan.tufted.pbrRoughness": 25,
  "scan.tufted.pbrNormalStrength": 78,
  "scan.wild.enabled": true,
  "scan.wild.count": 1000,
  "scan.wild.sizeRange": [0.819, 1.35],
  "scan.wild.clumping": 86,
  "scan.wild.seed": 29,
  "scan.wild.surfaceOffset": 0.035,
  "scan.wild.pbrTint": "#FFFFFF",
  "scan.wild.pbrBrightness": 169,
  "scan.wild.colorContrast": 96,
  "scan.wild.colorSaturation": 166,
  "scan.wild.pbrRoughness": 88,
  "scan.wild.pbrNormalStrength": 48,
  "scan.white.enabled": true,
  "scan.white.count": 1000,
  "scan.white.sizeRange": [0.493374, 0.819],
  "scan.white.clumping": 97,
  "scan.white.seed": 67,
  "scan.white.surfaceOffset": -0.035,
  "scan.white.pbrTint": "#FFFFFF",
  "scan.white.pbrBrightness": 165,
  "scan.white.colorContrast": 200,
  "scan.white.colorSaturation": 30,
  "scan.white.pbrRoughness": 73,
  "scan.white.pbrNormalStrength": 48,
  "scan.yellow.enabled": true,
  "scan.yellow.count": 1000,
  "scan.yellow.sizeRange": [0.493374, 0.585],
  "scan.yellow.clumping": 90,
  "scan.yellow.seed": 39,
  "scan.yellow.surfaceOffset": 0,
  "scan.yellow.pbrTint": "#FF8F85",
  "scan.yellow.pbrBrightness": 164,
  "scan.yellow.colorContrast": 98,
  "scan.yellow.colorSaturation": 131,
  "scan.yellow.pbrRoughness": 89,
  "scan.yellow.pbrNormalStrength": 48,
  "scan.rocks.enabled": true,
  "scan.rocks.count": 89,
  "scan.rocks.sizeRange": [0.585, 1.2],
  "scan.rocks.clumping": 1,
  "scan.rocks.seed": 75,
  "scan.rocks.surfaceOffset": -0.02,
  "scan.rocks.pbrTint": "#c9cdbd",
  "scan.rocks.shadowColor": "#E8D6C0",
  "scan.rocks.pbrBrightness": 23,
  "scan.rocks.colorContrast": 65,
  "scan.rocks.colorSaturation": 154,
  "scan.rocks.pbrRoughness": 49,
  "scan.rocks.pbrNormalStrength": 90,
  "scan.boulder.enabled": true,
  "scan.boulder.size": 1.55,
  "scan.boulder.seed": 51,
  "scan.boulder.surfaceOffset": -0.07,
  "scan.boulder.pbrTint": "#c5c9bd",
  "scan.boulder.shadowColor": "#E8CBB5",
  "scan.boulder.pbrBrightness": 149,
  "scan.boulder.colorContrast": 57,
  "scan.boulder.colorSaturation": 9,
  "scan.boulder.pbrRoughness": 81,
  "scan.boulder.pbrNormalStrength": 85,
  "butterflies.enabled": true,
  "butterflies.count": 18,
  "butterflies.sizeRange": [0.12, 0.24],
  "butterflies.seed": 29,
  "butterflies.heightRange": [0.4, 0.8],
  "butterflies.flightCycles": 3,
  "butterflies.wingCycles": 33,
  "butterflies.landingTime": 1.5,
  "wind.mode": "simulation",
  "wind.directionAngle": 0,
  "wind.swayStrength": 10,
  "wind.swayCycles": 2,
  "wind.swayVariation": 66,
  "wind.strength": 85,
  "wind.flow": 69,
  "wind.gustCycles": 3,
  "wind.gustWidth": 37,
  "wind.noiseStrength": 84,
  "wind.noiseScale": 3,
  "wind.noiseDetail": 73,
  "wind.seed": 17,
  "wind.rampUp": 2.25,
  "wind.release": 1.2,
  "wind.directionResponse": 0.45,
  "wind.audioVolume": 80,
  "wind.surfaceTiltLeft": 3,
  "wind.surfaceTiltRight": 3,
  "wind.surfaceTiltUp": 3,
  "wind.surfaceTiltDown": 3,
  "wind.surfaceTiltSmoothing": 2,
  "export.includeBackground": true,
  "scene.background": "#88BB77",
  "export.image.format": "png",
  "export.image.resolution": "4k",
  "export.video.format": "mp4",
  "export.video.resolution": "current",
} as const;
