import { grassStartStateV21 } from "./grass-start-state";

const grassFallbackDefaults = {
  "appearance.bladeGradient": {
    angle: 90,
    gradientType: "linear",
    stops: [
      { color: "#173a26", opacity: 100, position: "18%" },
      { color: "#789546", opacity: 100, position: "70%" },
      { color: "#eef29a", opacity: 100, position: "92%" },
    ],
  },
  "appearance.colorVariation": 42,
  "appearance.colorContrast": 108,
  "appearance.colorSaturation": 82,
  "appearance.groundColor": "#1fb235",
  "appearance.instanceColor1": "#315a2d",
  "appearance.instanceColor2": "#6f8f3f",
  "appearance.instanceColor3": "#a3ad58",
  "appearance.instanceColorWeight1": 45,
  "appearance.instanceColorWeight2": 35,
  "appearance.instanceColorWeight3": 20,
  "appearance.pbrRoughness": 86,
  "appearance.pbrSheen": 44,
  "appearance.textureMaskLevels": [99, 100],
  "appearance.textureMaskScale": 1.2,
  "appearance.textureMaskSeed": 17,
  "blade.curveResolution": 8,
  "blade.heightRange": [0.2, 0.58],
  "blade.taperEnd": 92,
  "blade.thickness": 0.015,
  "blade.tilt2d": 8,
  "blade.use3d": true,
  "butterflies.count": 18,
  "butterflies.enabled": true,
  "butterflies.flightCycles": 2,
  "butterflies.heightRange": [0.4, 1.15],
  "butterflies.landingTime": 0.75,
  "butterflies.seed": 29,
  "butterflies.sizeRange": [0.12, 0.24],
  "butterflies.wingCycles": 22,
  "export.image.format": "png",
  "export.image.resolution": "4k",
  "export.includeBackground": true,
  "export.video.format": "mp4",
  "export.video.resolution": "current",
  "environment.backgroundBlur": 30,
  "environment.exposure": 116,
  "environment.fillColor": "#0c7307",
  "environment.fillStrength": 44,
  "environment.highlightWarmth": 27,
  "environment.intensity": 250,
  "environment.keyColor": "#d18d00",
  "environment.keyStrength": 200,
  "environment.preset": "sunrise",
  "environment.rimColor": "#bd7500",
  "environment.rimStrength": 154,
  "environment.rotation": 109,
  "environment.rotationX": -23,
  "environment.rotationZ": 133,
  "environment.sceneContrast": 155,
  "environment.sceneSaturation": 100,
  "environment.shadowCoolness": 49,
  "environment.sunPatchCoverage": 54,
  "environment.sunPatchEnabled": true,
  "environment.sunPatchOffset": { x: "0.00", y: "0.00" },
  "environment.sunPatchScale": 0.5,
  "environment.sunPatchSeed": 50,
  "environment.sunPatchSoftness": 17,
  "environment.sunPatchStrength": 100,
  "environment.visible": false,
  "field.alignToNormals": 100,
  "field.depth": 5,
  "field.densityMax": 12_500,
  "field.distanceMin": 0.02,
  "field.edgeIrregularity": 7,
  "field.distributionDetail": 3,
  "field.distributionLevels": [0, 100],
  "field.distributionOffset": [0, 0],
  "field.distributionRoughness": 55,
  "field.distributionScale": 0.55,
  "field.distributionSeed": 23,
  "field.randomRotation": 64,
  "field.seed": 20,
  "field.shapeRoundness": 100,
  "field.showGround": true,
  "field.topFacingCoverage": 42,
  "field.topFacingFade": 65,
  "field.topFacingOnly": false,
  "field.width": 7,
  "grass.enabled": true,
  "grass.depthOffset": -0.02,
  "groundShadow.blur": 0.65,
  "groundShadow.color": "#000000",
  "groundShadow.offsetY": -0.18,
  "groundShadow.offsetZ": 0.25,
  "groundShadow.scale": 100,
  "groundShadow.strength": 55,
  "lawn.bladeGradient": {
    angle: 90,
    gradientType: "linear",
    stops: [
      { color: "#173527", opacity: 100, position: "0%" },
      { color: "#46663a", opacity: 100, position: "62%" },
      { color: "#9bbe61", opacity: 100, position: "100%" },
    ],
  },
  "lawn.colorVariation": 43,
  "lawn.colorContrast": 160,
  "lawn.colorSaturation": 96,
  "lawn.curveResolution": 4,
  "lawn.densityMax": 30_000,
  "lawn.depthOffset": -0.02,
  "lawn.distributionDetail": 3,
  "lawn.distributionLevels": [0, 1],
  "lawn.distributionOffset": [0, 0],
  "lawn.distributionRoughness": 55,
  "lawn.distributionScale": 0.42,
  "lawn.distributionSeed": 37,
  "lawn.distanceMin": 0.0075,
  "lawn.enabled": true,
  "lawn.heightRange": [0.08, 0.13],
  "lawn.instanceColor1": "#234c2d",
  "lawn.instanceColor3": "#73904b",
  "lawn.instanceColorWeight1": 46,
  "lawn.instanceColor2": "#47852e",
  "lawn.instanceColorWeight2": 62,
  "lawn.instanceColorWeight3": 60,
  "lawn.pbrRoughness": 81,
  "lawn.pbrSheen": 43,
  "lawn.seed": 31,
  "lawn.taperEnd": 90,
  "lawn.thickness": 0.012,
  "lawn.tilt2d": 8,
  "lawn.textureMaskLevels": [99, 100],
  "lawn.textureMaskScale": 3.5,
  "lawn.textureMaskSeed": 76,
  "lawn.use3d": true,
  "preview.bladeCount": 6000,
  "preview.lawnBladeCount": 12_000,
  "scene.background": "#000000",
  "scan.boulder.enabled": true,
  "scan.boulder.colorContrast": 94,
  "scan.boulder.colorSaturation": 65,
  "scan.boulder.seed": 23,
  "scan.boulder.size": 0.72,
  "scan.boulder.surfaceOffset": -0.12,
  "scan.boulder.pbrAoStrength": 100,
  "scan.boulder.pbrBrightness": 72,
  "scan.boulder.pbrNormalStrength": 85,
  "scan.boulder.pbrRoughness": 100,
  "scan.boulder.pbrTint": "#c5c9bd",
  "scan.boulder.shadowColor": "#ffffff",
  "scan.boulder.textureMaskLevels": [99, 100],
  "scan.boulder.textureMaskScale": 1.2,
  "scan.boulder.textureMaskSeed": 23,
  "scan.rocks.clumping": 33,
  "scan.rocks.colorContrast": 96,
  "scan.rocks.colorSaturation": 72,
  "scan.rocks.count": 18,
  "scan.rocks.enabled": true,
  "scan.rocks.pbrAoStrength": 100,
  "scan.rocks.pbrBrightness": 78,
  "scan.rocks.pbrNormalStrength": 90,
  "scan.rocks.pbrRoughness": 100,
  "scan.rocks.pbrTint": "#c8cdbc",
  "scan.rocks.shadowColor": "#ffffff",
  "scan.rocks.textureMaskLevels": [99, 100],
  "scan.rocks.textureMaskScale": 0.75,
  "scan.rocks.textureMaskSeed": 57,
  "scan.rocks.seed": 57,
  "scan.rocks.sizeRange": [0.4, 0.75],
  "scan.rocks.surfaceOffset": -0.015,
  "scan.tufted.clumping": 7,
  "scan.tufted.colorContrast": 108,
  "scan.tufted.colorSaturation": 200,
  "scan.tufted.count": 1000,
  "scan.tufted.enabled": true,
  "scan.tufted.pbrAoStrength": 79,
  "scan.tufted.pbrBacklight": 42,
  "scan.tufted.pbrBrightness": 93,
  "scan.tufted.pbrNormalStrength": 78,
  "scan.tufted.pbrRoughness": 25,
  "scan.tufted.pbrSheen": 15,
  "scan.tufted.pbrTint": "#ffffff",
  "scan.tufted.textureMaskLevels": [99, 100],
  "scan.tufted.textureMaskScale": 3.3,
  "scan.tufted.textureMaskSeed": 84,
  "scan.tufted.seed": 41,
  "scan.tufted.sizeRange": [0.35, 0.42],
  "scan.tufted.surfaceOffset": -0.05,
  "scan.white.clumping": 11,
  "scan.white.colorContrast": 98,
  "scan.white.colorSaturation": 90,
  "scan.white.count": 178,
  "scan.white.enabled": true,
  "scan.white.pbrAoStrength": 90,
  "scan.white.pbrBacklight": 25,
  "scan.white.pbrBrightness": 102,
  "scan.white.pbrNormalStrength": 48,
  "scan.white.pbrRoughness": 88,
  "scan.white.pbrSheen": 10,
  "scan.white.pbrTint": "#ffffff",
  "scan.white.textureMaskLevels": [99, 100],
  "scan.white.textureMaskScale": 0.8,
  "scan.white.textureMaskSeed": 48,
  "scan.white.seed": 48,
  "scan.white.sizeRange": [0.35, 0.55],
  "scan.white.surfaceOffset": 0.015,
  "scan.wild.clumping": 19,
  "scan.wild.colorContrast": 98,
  "scan.wild.colorSaturation": 139,
  "scan.wild.count": 402,
  "scan.wild.enabled": true,
  "scan.wild.pbrAoStrength": 78,
  "scan.wild.pbrBacklight": 36,
  "scan.wild.pbrBrightness": 105,
  "scan.wild.pbrNormalStrength": 48,
  "scan.wild.pbrRoughness": 88,
  "scan.wild.pbrSheen": 12,
  "scan.wild.pbrTint": "#3cff00",
  "scan.wild.textureMaskLevels": [99, 100],
  "scan.wild.textureMaskScale": 0.9,
  "scan.wild.textureMaskSeed": 53,
  "scan.wild.seed": 48,
  "scan.wild.sizeRange": [0.55, 0.85],
  "scan.wild.surfaceOffset": 0.005,
  "scan.yellow.clumping": 0,
  "scan.yellow.colorContrast": 98,
  "scan.yellow.colorSaturation": 88,
  "scan.yellow.count": 136,
  "scan.yellow.enabled": true,
  "scan.yellow.pbrAoStrength": 90,
  "scan.yellow.pbrBacklight": 25,
  "scan.yellow.pbrBrightness": 105,
  "scan.yellow.pbrNormalStrength": 48,
  "scan.yellow.pbrRoughness": 88,
  "scan.yellow.pbrSheen": 10,
  "scan.yellow.pbrTint": "#ffffff",
  "scan.yellow.textureMaskLevels": [99, 100],
  "scan.yellow.textureMaskScale": 0.8,
  "scan.yellow.textureMaskSeed": 79,
  "scan.yellow.seed": 79,
  "scan.yellow.sizeRange": [0.35, 0.5],
  "scan.yellow.surfaceOffset": 0.015,
  "surface.bendDepth": 0.75,
  "surface.bendEnabled": true,
  "surface.bendRoundness": 65,
  "surface.bendSmoothness": 85,
  "surface.bendWidth": 18,
  "surface.normalStrength": 115,
  "surface.cloverMaskDetail": 4,
  "surface.cloverMaskLevels": [42, 62],
  "surface.cloverMaskOffset": [0, 0],
  "surface.cloverMaskRoughness": 55,
  "surface.cloverMaskScale": 0.34,
  "surface.cloverMaskSeed": 41,
  "surface.cloverNormalStrength": 100,
  "surface.cloverRoughness": 100,
  "surface.cloverTextureScale": 1,
  "surface.cloverColor": "#1fb235",
  "surface.brightness": 100,
  "surface.colorContrast": 123,
  "surface.colorSaturation": 29,
  "surface.edgeFadeStrength": 100,
  "surface.edgeFadeWidth": 12,
  "surface.roughness": 81,
  "surface.receiveShadows": true,
  "surface.textureMaskLevels": [99, 100],
  "surface.textureMaskScale": 5.9,
  "surface.textureMaskSeed": 35,
  "surface.textureScale": 1.35,
  "terrain.detail": 4,
  "terrain.heightLevels": [0, 100],
  "terrain.maxHeight": 1.6,
  "terrain.noiseOffset": [2, 0],
  "terrain.noiseScale": 0.61,
  "terrain.roughness": 68,
  "terrain.seed": 4,
  "wind.directionResponse": 0.45,
  "wind.directionAngle": 0,
  "wind.audioVolume": 60,
  "wind.flow": 38,
  "wind.gustCycles": 2,
  "wind.gustWidth": 52,
  "wind.mode": "static",
  "wind.noiseDetail": 58,
  "wind.noiseScale": 1.7,
  "wind.noiseStrength": 62,
  "wind.rampUp": 0.75,
  "wind.release": 1.2,
  "wind.seed": 17,
  "wind.strength": 72,
  "wind.surfaceTiltDown": 1.25,
  "wind.surfaceTiltLeft": 1.25,
  "wind.surfaceTiltRight": 1.25,
  "wind.surfaceTiltSmoothing": 0.6,
  "wind.surfaceTiltUp": 1.25,
  "wind.swayCycles": 1,
  "wind.swayStrength": 16,
  "wind.swayVariation": 48,
  "view.orientation": {
    position: [0.05097369563810365, 0.46537960393646394, 0.8966735786187362],
    up: [0, 1, 0],
  },
} as const;

export const grassDefaults = {
  ...grassFallbackDefaults,
  ...grassStartStateV21,
} as const;

export type GrassImageFormat = "jpg" | "png";
export type GrassImageResolution = "2k" | "4k" | "8k";
export type GrassHdriPreset =
  | "alps"
  | "blendSunset"
  | "forest"
  | "golden"
  | "hardSun"
  | "meadow"
  | "overcast"
  | "sunrise";
export type GrassWindMode = "static" | "sway" | "wind" | "simulation";
export type GrassVideoFormat = "mp4" | "webm";
export type GrassVideoResolution = "4k" | "current";
