import type {
  CreativeAppsKitComponentContract,
  CreativeAppsKitLabelPolicy,
  CreativeAppsKitPanelPlacement,
  CreativeAppsKitPanelSnapEdge,
  CreativeAppsKitSectionLayout,
} from "./types";

export type * from "./types";

export const EFFECTS_EDITOR_COMPONENT_CONTRACTS = {
  slider: {
    ...control("slider", "Slider", "grouped", "required"),
    aiUsageRules: [
      "Slider step means numeric snapping only; it does not make the slider visually discrete by itself.",
      "Classify every stepped slider as stepped continuous or visual discrete before writing the schema.",
      'Small semantic integer domains such as rows, cols, gaps, jitter, counts, levels, bands, passes, points, tiles, and segments must use variant: "discrete".',
      'Finite animation step domains such as flip depth, character count, glyph steps, and frame steps must use variant: "discrete" when the marker count stays within the Creative Apps Kit visual budget.',
      "Large or precision stepped ranges such as speed, FPS, rate, duration, density, size, and intensity stay visually continuous even when they declare step.",
      "Related sliders may share an explicit two-column inline layout when they tune the same product entity or animation stage.",
      "Half-width inline discrete sliders have a tighter marker budget: show markers only up to 20 positions; above that, keep the slider usable but hide marker ticks.",
      "For a small named option set, prefer Select or Segmented instead of forcing a discrete Slider.",
      'Specs, plans, and app-schema tests must assert explicit discrete sliders render as variant: "discrete" with markers derived from min, max, and step.',
      'Browser verification can inspect [data-slot="slider"][data-variant="discrete"] plus slider markers to prove the Creative Apps Kit component variant rendered.',
      "Visual discrete sliders must still drag smoothly; browser performance tests should use expectCreativeAppsKitDiscreteSliderDragSmoothness for real pointer drag.",
      "Use schema disabled: true for unavailable sliders; do not recreate a disabled-looking slider with custom markup.",
      "Use disabledWhen for sliders that are only meaningful in some mode values, such as Fill level and Islands being disabled when Fill mode is Full.",
      "Do not leave a mode-dependent slider active while making the renderer ignore it; the UI must expose the unavailable state.",
    ],
  },
  rangeSlider: {
    ...control("rangeSlider", "RangeSlider", "grouped", "required"),
    aiUsageRules: [
      "Range slider step means numeric snapping only; it does not make the range slider visually discrete by itself.",
      "Classify every stepped range slider as stepped continuous or visual discrete before writing the schema.",
      'Small semantic integer domains such as rows, cols, gaps, jitter, counts, levels, bands, passes, points, tiles, and segments must use variant: "discrete".',
      'Finite animation step domains such as flip depth, character count, glyph steps, and frame steps must use variant: "discrete" when the marker count stays within the Creative Apps Kit visual budget.',
      "Large or precision stepped ranges such as speed, FPS, rate, duration, density, size, and intensity stay visually continuous even when they declare step.",
      "Related range sliders may share an explicit two-column inline layout when they tune the same product entity or animation stage.",
      "Half-width inline discrete range sliders have a tighter marker budget: show markers only up to 20 positions; above that, keep the slider usable but hide marker ticks.",
      'Specs, plans, and app-schema tests must assert explicit discrete range sliders render as variant: "discrete" with markers derived from min, max, and step.',
      "Visual discrete sliders must still drag smoothly; browser performance tests should use expectCreativeAppsKitDiscreteSliderDragSmoothness for real pointer drag.",
      "Use schema disabled: true for unavailable range sliders; do not recreate a disabled-looking range slider with custom markup.",
      "Use disabledWhen for range sliders that are only meaningful in some mode values; keep the value so it returns when the mode becomes relevant again.",
      "Do not leave a mode-dependent range slider active while making the renderer ignore it; the UI must expose the unavailable state.",
      "Acceptance must prove both rangeSlider.lower and rangeSlider.upper change the product output; testing one handle is not enough.",
    ],
  },
  select: control("select", "Select", "grouped", "required"),
  segmented: {
    ...control("segmented", "Segmented", "grouped", "required"),
    aiUsageRules: [
      "Use Segmented only for compact mode choices where every cell keeps its internal padding.",
      "If a segmented control is too wide, first shorten option labels; if the compact labels still exceed the width budget, use Select because it has the same selection mechanics without broken cells.",
      "Generated schemas should keep text segmented controls to at most four options, no option label longer than nine characters, and no more than twenty-four total option-label characters.",
      "Browser verification must treat collided, clipped, or paddingless segmented cells as a broken component and switch to shorter labels or Select.",
    ],
  },
  switch: {
    ...control("switch", "Switch", "grouped", "required"),
    aiUsageRules: [
      'Switch labels name the setting context only; do not prefix labels with "Enable" or "Disable" because the switch already communicates on/off behavior.',
      'Use labels such as "CRT", "Background", "Glow", or "Loop" instead of "Enable CRT" or "Disable background".',
    ],
  },
  checkbox: {
    ...control("checkbox", "Checkbox", "grouped", "required"),
    aiUsageRules: [
      'Checkbox labels name the setting context only; do not prefix labels with "Enable" or "Disable" because the checkbox already communicates enabled/selected state.',
      'Use labels such as "Transparent background", "Guides", or "Loop" instead of "Enable transparent background".',
    ],
  },
  colorOpacity: {
    ...control("colorOpacity", "ColorOpacity", "standalone", "component-owned"),
    aiUsageRules: [
      "Use ColorOpacity when one product entity needs both a color and an opacity value, such as text color, shadow color, glow color, overlay color, or stroke color.",
      "Do not split ColorOpacity into a separate Color plus Slider/Input for opacity; use type: \"colorOpacity\" so the color popover and percent input stay visually connected.",
      "Use one object value with hex and opacity. Renderers and exports must consume both parts.",
      "When one short numeric/text field and one ColorOpacity field configure the same entity, keep them in one two-column inline layout group.",
      "Mixed inline rows require visible labels on both controls; never pair a labeled numeric/text input with an unlabeled ColorOpacity field.",
      "Acceptance must prove colorOpacity.hex and colorOpacity.opacity both affect the product output; testing only the swatch or only runtime state is not enough.",
    ],
  },
  text: control("text", "TextInput", "grouped", "required"),
  rangeInput: {
    ...control("rangeInput", "RangeInput", "grouped", "required"),
    aiUsageRules: [
      "RangeInput is a compound control; acceptance must prove rangeInput.start and rangeInput.end both affect the product output.",
      "Do not accept a range input test that edits only the first field or only checks runtime state.",
    ],
  },
  actions: {
    ...control("actions", "Actions", "grouped", "required"),
    commands: ["controls.reset", "controls.apply"],
    stateMode: "command-only",
  },
  panelActions: {
    ...control("panelActions", "PanelActions", "standalone", "component-owned"),
    aiUsageRules: [
      "Use panelActions only for sticky footer product actions such as Generate, Export, Copy, or Download.",
      "Do not use panelActions for resetting controls; the controls panel header owns Reset controls.",
      "Handle product-specific panelActions through CreativeAppsKitApp onPanelAction.",
      "defineCreativeAppsKit hoists panelActions into the controls panel sticky footer automatically.",
      "Product-output apps must always include export in panelActions.",
      "Static or still-output apps include Export PNG as the primary footer action.",
      "Animated apps include Export Video as the primary footer action and Export PNG as a secondary footer action.",
      'Animated apps with Export Video must expose a separate "Video Export" controls section.',
      'The Video Export section must include format and quality controls such as targets "export.video.format" and "export.video.quality".',
      'Baseline browser video formats are "auto", "webm", and "mp4"; MOV or ProRes require an explicit custom encoder/transcoder and dedicated acceptance plus performance coverage.',
      "Video export code must choose the actual MIME/container through MediaRecorder.isTypeSupported or an equivalent encoder capability check, then fall back safely.",
      'Video quality must control exported dimensions or bitrate. Use high-quality output by default; "4K" is a quality target, not a hardcoded 3840x2160 canvas lock.',
      "Video export browser coverage must load the exported blob metadata and prove video.duration matches the edited runtime timeline duration; blobSize/blobType checks alone are not enough.",
      "Product-output apps must expose user-facing Background color and Include background controls, then pass the includeBackground runtime value to createCreativeAppsKitPngExportCanvas only for PNG alpha.",
      "PNG export must use createCreativeAppsKitPngExportCanvas so background transparency and retina sizing are applied consistently without making live preview, workspace canvas backing, or video transparent.",
      "Video export must keep product background and use getCreativeAppsKitRetinaExportSize for retina dimensions.",
      "Copy PNG can be a secondary action when clipboard output is useful, but copy does not replace export.",
      "Add Copy PNG as a secondary action only when the prompt/reference includes clipboard output or the product clearly benefits from paste/share workflows.",
      "Footer actions must be one compact horizontal group; do not split them into stacked full-width sections.",
      "If two footer actions are needed, render secondary/outline on the left and primary on the right.",
      "When an odd number of footer actions renders in two columns, the final unpaired action spans the full row width.",
    ],
    commands: ["controls.apply"],
    stateMode: "command-only",
  },
  palette: {
    ...control("palette", "Palette", "standalone", "component-owned"),
    aiUsageRules: [
      "Palette is a compound control; acceptance must prove palette.family and palette.shade both affect the product output.",
      "Do not accept a palette test that only changes a swatch preview without proving the renderer/export consumes the selected family and shade.",
    ],
  },
  vector: {
    ...control("vector", "Vector", "standalone", "component-owned"),
    aiUsageRules: [
      "If the controls panel contains exactly one vector control, the runtime renders the vector pad as a square.",
      "If the controls panel contains multiple vector controls, the runtime renders compact vector pads.",
      "Multiple vector controls should live in separate semantic sections unless they intentionally belong to the same entity with other related controls.",
      'Use variant: "whiteBalance" for temperature/tint pads: X maps cool blue to warm amber, Y maps green to magenta.',
      'Use variant: "colorBalance" for paired color-balance axes such as cyan/red and blue/yellow correction.',
      'Use variant: "chromaOffset" for RGB/chromatic offset vectors where the X/Y movement controls channel separation.',
      'Use variant: "toneBias" for split-tone, duotone, or color-grading vectors where both axes describe tone or hue bias.',
      'Use the default vector variant for spatial values such as position, offset, direction, focus, anchor, and light direction.',
      "Do not add custom vector sizing props in generated schemas; choose the number, variant, and section grouping from product need and let the runtime size the pads.",
      "Vector is a compound control; acceptance must prove vector.x and vector.y both affect the product output.",
    ],
  },
  color: {
    ...control("color", "Color", "standalone", "component-owned"),
    aiUsageRules: [
      "Color controls can be standalone color sections or grouped fields inside a semantic control section.",
      "First identify the semantic entity the color belongs to, such as Square 1, Square 2, Background, Object, Connector, Glow, Tone Mapping, Brand, or Export.",
      "Keep a color inside a section when it configures the same entity as nearby controls. Example: Square 1 (Right) contains Connections, Hover radius, and Color in one section.",
      "Use a standalone color section only when the color itself is the whole semantic section; the section title must describe the product role such as Background, Object, Connector, Accent, Gradient, or Brand.",
      "When color belongs to the same object or effect as nearby controls, keep it inside that section and use a field label such as Color, Fill, Stroke, Accent, or Connector above the input.",
      "The standalone default applies only to color-only sections; mixed semantic sections keep color grouped with nearby controls.",
      "Never use generic Color or Colors as a generated section title. If no meaningful color role exists and the colors are just basic colors, omit the section title.",
      "Do not split a grouped object section into a separate generated Color section; if the color role is unclear, ask the user before implementation.",
      "When one short numeric/text field and one Color field configure the same entity, keep them in one two-column inline layout group.",
      "Mixed inline rows require visible labels on both controls; never pair a labeled numeric/text input with an unlabeled Color field.",
      "Product-output apps always expose renderer-owned output background color as a schema color target such as appearance.background or scene.background.",
      "Preview, PNG export, and video export must read the runtime background color value instead of hardcoding that background in CSS, Canvas fillStyle, or WebGL clearColor. export.includeBackground controls only PNG alpha; it must not make live preview, workspace canvas backing, or video transparent.",
      "Render multiple related color fields in one section with at most two colors per row.",
    ],
  },
  gradient: {
    ...control("gradient", "Gradient", "standalone", "component-owned"),
    aiUsageRules: [
      "Gradient is a compound control; acceptance must prove gradient.gradientType, gradient.angle, gradient.stops.position, gradient.stops.color, and gradient.stops.opacity all affect the product output when visible.",
      "Do not accept a gradient test that edits only a stop color; Linear/Radial/Angular/Diamond selection, angle, stop position, stop color, and stop opacity must be wired or the control should be simplified.",
      "If the renderer intentionally supports only a subset of gradient behavior, do not use the full Gradient control; use simpler controls that match the renderer behavior.",
    ],
  },
  fontPicker: {
    ...control("fontPicker", "FontPicker", "standalone", "component-owned"),
    aiUsageRules: [
      "FontPicker owns the font preview select, virtualized font popup, category filters, search, preview loading, font-weight select, font-size input, letter-spacing slider, and line-height slider.",
      "Do not recreate FontPicker with a plain Select plus separate sliders; use type: \"fontPicker\" so the popup mechanics and footer controls stay intact.",
      "Use one object value with fontId, fontWeight, fontSize, letterSpacing, and lineHeight. Keep typography renderers wired to all five parts.",
      "Any product text controlled by FontPicker must render fontId, fontWeight, fontSize, letterSpacing, and lineHeight in preview and export; do not leave typography values as panel-only runtime state.",
      "FontPicker is a compound control; acceptance must prove fontPicker.fontId, fontPicker.fontWeight, fontPicker.fontSize, fontPicker.letterSpacing, and fontPicker.lineHeight all affect the product output.",
      "FontPicker acceptance must inspect the actual product text output after changing font, weight, size, letter spacing, and line height; runtime state, select labels, or popup preview text alone are not enough.",
      "Browser verification must open the popup, choose a different font, change font weight, change font size, move the letter-spacing footer slider, and move the line-height footer slider.",
    ],
  },
  curves: {
    ...control("curves", "Curves", "standalone", "component-owned"),
    aiUsageRules: [
      "Curves is a compound control; acceptance must prove curves.activeChannel and curves.points both affect the product output.",
      "Do not accept a curves test that only opens the UI or changes selected point state without proving renderer/export output changes.",
    ],
  },
  anchorGrid: {
    ...control("anchorGrid", "AnchorGrid", "standalone", "component-owned"),
    aiUsageRules: [
      "AnchorGrid is a position selector; acceptance must prove anchorGrid.position changes product placement, not only selected button state.",
      "Choose representative edge/corner anchors in browser tests so center-only behavior cannot pass.",
    ],
  },
  channelMixer: {
    ...control("channelMixer", "ChannelMixer", "standalone", "component-owned"),
    aiUsageRules: [
      "ChannelMixer is a compound control; acceptance must prove channelMixer.activeChannel and channelMixer.values both affect the product output.",
      "Do not accept a channel mixer test that changes only the active tab or only one slider without proving the selected channel matrix is consumed by the renderer/export.",
    ],
  },
  fileDrop: {
    ...control("fileDrop", "FileDrop", "standalone", "component-owned"),
    aiUsageRules: [
      "Use fileDrop for source material uploads in the controls panel, not on the canvas.",
      "In single-layer apps, the runtime shows the uploaded image as the fileDrop preview and provides the clear action.",
      "In multi-layer apps, deletion and visibility belong to the Layers panel; fileDrop remains an upload target.",
    ],
    commands: ["media.delete", "media.import"],
  },
  imagePicker: {
    ...control("imagePicker", "ImagePicker", "standalone", "component-owned"),
    aiUsageRules: [
      "ImagePicker owns thumbnail layout; pass the item list only and do not recreate the grid manually.",
      "Every visible ImagePicker item must be actionable in the current product context.",
      "Do not show selectable image choices that the renderer later sanitizes to a fallback or no-op.",
      "If available choices depend on another control such as template, mode, or selected object, either make every visible item valid for every mode, split the choice into separate semantic controls, or ask the user before implementation.",
      "A defensive invalid-value fallback is allowed, but it is not acceptance proof for a visible ImagePicker option.",
      "Tests must choose each visible ImagePicker item and assert the selected image, texture, gradient, or exported pixels change in the product output.",
      "Do not accept renderer data attributes, runtime target changes, or option existence as final proof that an image choice works.",
    ],
  },
  code: {
    ...control("code", "CodeTextarea", "standalone", "required"),
    aiUsageRules: [
      "CodeTextarea is the multiline text input for any potentially long value, not only source code.",
      "Use text for short single-line strings such as names, small numeric values, compact prompts, titles, and short tokens.",
      "Use code when the user may enter long prompts, multiline text, JSON, CSS, shader code, scripts, templates, or other long structured data.",
      "CodeTextarea height is capped at 12 visible text lines; long content scrolls inside the textarea instead of making the controls panel taller.",
      "Do not name a section Code unless the product value is actually code; use the product role such as Prompt, Instructions, Template, JSON, Shader, or CSS.",
    ],
  },
  canvas: {
    aiUsageRules: [
      "Choose canvas.sizing.mode from product context instead of copying a universal 1024px artboard.",
      "Use intrinsic-media for single-layer upload/generation apps so imported media natural size becomes canvas.size.",
      "Use editable-output by default for generated, exportable, shader, poster, badge, wall, banner, thumbnail, and product-output apps where users should see or edit width and height.",
      "A user-provided base/default size is not a reason to remove size controls; model it as canvas.size plus editable-output unless the prompt or reference explicitly locks output dimensions.",
      "Use fixed-output only when the product output size must not be user-editable, and prove that lock with canvasSizingCoverage fixed-output-size acceptance.",
      "If canvas.size is provided without an explicit sizing mode, defineCreativeAppsKit treats it as editable-output and adds Canvas width and Canvas height controls.",
      "The runtime Canvas width and Canvas height block is untitled; do not add a Canvas section label above these fields.",
    ],
    capabilities: ["drag", "zoom", "radar", "upload", "editable-size"],
    commands: [
      "canvas.setSize",
      "canvas.panBy",
      "canvas.setOffset",
      "canvas.center",
      "canvas.zoomIn",
      "canvas.zoomOut",
      "canvas.zoomReset",
      "media.delete",
      "media.import",
    ],
    historyPolicy: "patch",
    id: "canvas",
    kind: "canvas",
    schemaType: "canvas",
    stateMode: "runtime-owned",
    visualComponent: "CanvasShell",
  },
  persistence: {
    aiUsageRules: [
      "Do not write app state to localStorage directly.",
      "Use schema persistence policy for app state that should survive reload.",
      "Persistence may include values, canvas, panels, timeline, and layers; history and media blobs are not persisted.",
      'Apps with visible runtime panels and localStorage persistence must include "panels" so dragged panel positions survive reload.',
      "Do not store media blobs, files, or large generated images in localStorage.",
    ],
    capabilities: ["themePreference", "appStatePolicy"],
    commands: [],
    historyPolicy: "never",
    id: "persistence",
    kind: "persistence",
    schemaType: "persistence",
    stateMode: "runtime-owned",
    visualComponent: "none",
  },
  settingsTransfer: {
    aiUsageRules: [
      'Use schema settingsTransfer: "auto" for complex apps unless the prompt explicitly disables settings import/export.',
      "Do not hand-roll settings import/export through app routes, hidden file inputs, or panelActions.",
      "Settings transfer appears as the first controls-panel section when enabled; it imports and exports control values, canvas size, and timeline state.",
      "Keep sticky footer panelActions for product delivery actions only, such as Export PNG, Export Video, Copy, Generate, Apply, or Download.",
    ],
    capabilities: ["settings-import-export"],
    commands: ["controls.setValue", "timeline.setCurrentTime", "timeline.setDuration"],
    historyPolicy: "patch",
    id: "settingsTransfer",
    kind: "settings",
    schemaType: "settingsTransfer",
    stateMode: "runtime-owned",
    visualComponent: "SettingsTransfer",
  },
  appEntityAcceptance: {
    aiUsageRules: [
      "Every app entity introduced by the AI must have an acceptance test that proves its product responsibility.",
      "Compound controls must declare controlPartCoverage for every semantic value part required by their control type.",
      "Compound control browser tests must explicitly exercise each required value part, not only one visible sub-control.",
      "Acceptance tests must fail when an entity is disconnected from runtime state, renderer output, export output, or command side effects.",
      "Do not accept typecheck, component existence, registered commands, runtime state mutation, renderer input objects, shader uniform presence, or signature strings as final proof.",
      "Use product-level observables such as rendered pixels, exported image bytes, canvas hash, clipboard payload, cleared media preview, selected layer result, changed viewport, or timeline-rendered frame.",
      "A generic canvas hash difference is not enough for workload or semantic controls; assert the intended direction of the effect.",
      "Component variants are accepted entities too; tests should fail if a non-default Creative Apps Kit control variant falls back to the default variant or custom markup.",
      "Conditional entities require fixtures that make the condition observable.",
      "Use visibleWhen for mode-exclusive sections or controls that do not belong to the current template, type, or mode.",
      "Use disabledWhen for controls that belong to the current entity but are temporarily unavailable for the selected mode; the disabled value must be preserved.",
      "Do not leave inactive mode-specific controls visible and enabled while making the renderer ignore them.",
      "If an entity cannot be tested against a product-level observable, remove it from the app schema or ask whether it is required.",
    ],
    capabilities: ["acceptance-tests", "product-output-verification"],
    commands: [],
    historyPolicy: "never",
    id: "appEntityAcceptance",
    kind: "composition",
    schemaType: "appEntityAcceptance",
    stateMode: "runtime-owned",
    visualComponent: "none",
  },
  performanceAcceptance: {
    aiUsageRules: [
      "Custom renderers must define performance budgets for media import, preview updates, control drags, and export/copy before implementation.",
      "Controls that change renderer workload, such as Char Size, Grid Density, Matrix Scale, Sample Count, Resolution, Blur Radius, Iterations, Particle Count, or Quality, must be tested at min, default, and max values.",
      "Hash differs is not enough for workload controls; tests must assert semantic direction, for example smaller Char Size increases glyph/cell density and larger Char Size decreases it.",
      "Performance tests must use representative fixtures and the same renderer/export path as the running app, not only tiny 32px fixtures or isolated helper state.",
      "Expensive renderers must cache decoded media, source pixels, glyph atlases, gradients, and other reusable inputs by media id, canvas size, and stable control keys.",
      "Slider drags and high-frequency controls must debounce or coalesce preview work, cancel stale async renders, and avoid re-decoding media on every control change.",
      "Performance matrices must declare rendererWorkload as none, simple-composition, text-output, vector-output, or pixel-output.",
      "Major post-generation iterations that add animation, keyframes, layers, renderer rewrites, canvas behavior changes, broad control rewiring, or product-output rewrites must run pnpm verify:perf or pnpm verify:final before completion.",
      "Renderer specs must include a Renderer Technique Decision Matrix with sourceRepresentation, productRepresentation, previewRenderer, exportRenderer, rendererWorkload, rendererStrategy, whyNotAlternativeStrategies, fidelityRisks, and performanceRisks.",
      "Custom renderer apps must mirror the Renderer Technique Decision Matrix in typed rendererTechnique config so validation can reject contradictory renderer choices.",
      "Custom renderer specs must include a Renderer Layer Inventory and mirror it in typed rendererTechnique.layers so dense raster backgrounds cannot silently rasterize semantic foreground output.",
      "Semantic foreground output such as product lines, shapes, icons, text, object bounds, and meaningful markers should use DOM or SVG by default; dense raster backgrounds do not justify rasterizing low-count foreground geometry or text.",
      "Editing handles must be DOM/SVG overlays, excluded from export, and written through runtime state instead of being drawn into the product raster layer.",
      "Product foreground and editing handle renderer layers must declare uiSelector so browser tests can verify the visible layer exists.",
      'productRepresentation "mixed" is valid only when rendererTechnique.layers proves at least two different content families.',
      "Choose renderer technique from product context, not convenience or novelty. Preserve reference renderer technology in reference-runtime-clone mode unless a concrete blocker and replacement acceptance tests are named.",
      "Do not switch renderer technology just because it seems more modern or faster. Preview and export may use different renderers only when the decision matrix explains why and export/copy remains product-quality.",
      "Choose renderer workload by product fidelity before choosing rendering technology: ASCII, glyph grids, code art, subtitles, typography, or monospace text products are text-output unless the product intentionally rasterizes them into per-pixel effects.",
      "Text-output and vector-output visible previews must preserve native output fidelity. Do not render a low-resolution offscreen canvas or texture and upscale it to the product size.",
      "Pixel-output renderers must use WebGL or WebGPU even when the scene is static.",
      "Procedural pixel renderers, shader-like effects, animated mesh gradients, and large exportable previews should use WebGL or WebGPU for pixel work instead of main-thread ImageData loops.",
      "WebGL and WebGPU renderers must initialize contexts, programs, shaders, pipelines, textures, and large buffers once, then update uniforms or stable buffers when controls change.",
      "For keyframe or playback renderers, texture upload and media decode must be keyed to source media/resource changes, not to timeline time or evaluated settings. Timeline-only updates must reuse decoded media and existing GPU resources.",
      "Do not create WebGL/WebGPU contexts, shader programs, textures, or requestAnimationFrame loops directly in the React render path.",
      "Animation loops must cancel scheduled frames during cleanup.",
      "Animated preview renderers must suspend or coalesce non-essential animation work while the user drags, pans, pinches, zooms, or centers the canvas viewport, then resume from the correct timeline or autonomous time without changing the user's play/pause state.",
      "If a generated app uses ImageData, getImageData, or putImageData for procedural output, performance validation must fail unless the renderer is converted to GPU rendering or the CPU path is removed.",
      "Performance matrices must declare rendererStrategy so tests can distinguish none, dom, svg, canvas-2d, webgl, and webgpu renderer paths.",
      "Browser verification must interact with the actual UI, exercise worst-case control values, and fail if the app freezes, creates runaway render loops, drops canvas zoom/offset, or misses the performance budget.",
      "If a renderer cannot meet the budget, reduce the work units, clamp the control range, move work off the critical path, or remove the control.",
    ],
    capabilities: ["performance-budgets", "workload-control-tests"],
    commands: [],
    historyPolicy: "never",
    id: "performanceAcceptance",
    kind: "composition",
    schemaType: "performanceAcceptance",
    stateMode: "runtime-owned",
    visualComponent: "none",
  },
  referenceRuntimeClone: {
    aiUsageRules: [
      'Use transferMode: "reference-runtime-clone" when the user asks to port, clone, copy, or reproduce an existing app exactly.',
      "Preserve the reference runtime as the source of truth instead of replacing it with a new renderer or timeline model.",
      "Port requestAnimationFrame loops, refs, mutable particle/object state, connection state, spawn/update cadence, lifetime rules, pause/resume, export/copy, canvas sizing, and media lifecycle when the reference depends on them.",
      "Keep Creative Apps Kit as the shell: defineCreativeAppsKit, CreativeAppsKitApp, schema controls, canvasContent, fileDrop, panelActions, and runtime commands.",
      "Reference clone timeline choice is based on timeline behavior, not only on whether the reference draws a timeline-shaped UI.",
      "If the reference has Play/Pause, Restart from beginning, current time/progress, duration, loop, scrub, selected range, trim handles, or video export timing, write a Reference Timeline Inventory before choosing a timeline mode.",
      'Use referenceTimeline.mode "creative-apps-kit-playback" for plain transport behavior such as play/pause, restart, duration/progress, loop, scrub, or export at time.',
      'Use referenceTimeline.mode "creative-apps-kit-keyframes" when controls need keyframe diamonds, expanded keyframe rows, easing, or editable keyframes.',
      'Use referenceTimeline.mode "none" only when the reference has no user-facing transport behavior at all.',
      "Reference clone specs must list every detected transport behavior explicitly, including pause-resume, restart, time-progress, export-at-time, playback, scrub, duration, loop, and keyframes when present.",
      "Do not create right-panel controls named or targeted as Play, Pause, Paused, Animate, Restart animation, or equivalent app-wide transport toggles.",
      'Do not downgrade custom reference timelines to panels.timeline mode "playback". State buttons, trim handles, selected-range playback, or range export require referenceTimeline.mode "custom-reference-timeline" and dedicated acceptance.',
      "Generated reference clone apps must declare appTransferMode.referenceTimeline with mode none, creative-apps-kit-playback, creative-apps-kit-keyframes, or custom-reference-timeline.",
      "Custom reference timeline behavior needs referenceTimelineCoverage entries such as state-jump, trim-range, range-playback, all-range, jump-to-trim-start, and export-range.",
      "Reference clone acceptance must include referenceCoverage rows for canvas sizing, control mapping, renderer state, and any renderer loop, spawn/update cadence, pause/resume, export/copy, or media lifecycle behavior in the reference.",
      "Browser tests must compare reference behavior or a reference-derived baseline, not only Creative Apps Kit state mutation.",
    ],
    capabilities: [
      "reference-runtime-clone",
      "reference-behavior-acceptance",
      "reference-timeline-inventory",
      "canvasContent-renderer",
    ],
    commands: [],
    historyPolicy: "never",
    id: "referenceRuntimeClone",
    kind: "composition",
    schemaType: "transferMode",
    stateMode: "runtime-owned",
    visualComponent: "canvasContent",
  },
  controlLabels: {
    aiUsageRules: [
      "Control labels must be short UI names, usually one to three words.",
      "Do not put explanations, formulas, units, parenthetical hints, or usage instructions in control labels.",
      "Use section titles, option labels, tests, or renderer/spec prose for details instead of long field labels.",
      "Bad: Grid Density (every Nth). Good: Grid Density, with Every 6th as the select option label.",
      "If a source label is unavoidably long, keep the visible label concise and rely on the native title tooltip for the full text.",
    ],
    capabilities: ["short-labels", "native-title-tooltip"],
    commands: [],
    historyPolicy: "never",
    id: "controlLabels",
    kind: "composition",
    schemaType: "controlLabels",
    stateMode: "runtime-owned",
    visualComponent: "ControlFieldLabel",
  },
  controlsPanel: panel("controlsPanel", "ControlsPanel", "right", ["left", "right"], "handle"),
  layersPanel: {
    ...panel("layersPanel", "LayersPanel", "left", ["left", "right"], "handle"),
    aiUsageRules: [
      "Enable panels.layers only when the app needs editable layer selection, ordering, grouping, visibility, or multi-object media management.",
      "Do not enable the layers panel for single-layer apps.",
      "If the user intent is ambiguous, ask whether layer management is required before enabling panels.layers.",
      "When layers are enabled, layer-specific controls should target selectedLayer.* and apply to the currently selected runtime layer.",
      "Do not use selectedLayer.* targets when panels.layers is disabled; single-layer apps use app-specific targets.",
      "Layer-enabled apps need layerCoverage acceptance for selection, visibility, reorder, and grouping.",
      "Every selectedLayer.* control needs selected-layer-controls acceptance proving it edits the currently selected layer output.",
      "Layer browser coverage must use real LayersPanel rows and buttons, not direct layers.* command dispatch.",
      "Layer-enabled custom renderers need layers.interactions viewport-stability coverage around real selection, visibility, reorder or grouping, and selected-layer output checks.",
    ],
    capabilities: [
      "draggable",
      "snap",
      "doubleClickReset",
      "dragMode:handle",
      "groups",
      "selection",
      "visibility",
    ],
    commands: [
      "layers.add",
      "layers.delete",
      "layers.moveToGroup",
      "layers.rename",
      "layers.reorder",
      "layers.select",
      "layers.toggleCollapsed",
      "layers.toggleVisibility",
    ],
  },
  timelinePanel: {
    ...panel("timelinePanel", "TimelinePanel", "top", ["top", "bottom"], "panel"),
    aiUsageRules: [
      "Do not enable the timeline panel just because a renderer is animated.",
      "Before choosing no timeline for any animated product, write an Animation Intent Inventory: product transport, editable keyframes, or autonomous decorative output, plus the user-facing time behaviors present or intentionally absent.",
      'User-requested product animation defaults to panels.timeline mode "playback" unless the spec explicitly declares autonomous decorative/self-running output with no play, pause, scrub, duration, loop, or export-at-time behavior.',
      'Use panels.timeline: { mode: "playback" } when the product needs user-facing play, pause, scrubbing, duration, loop, restart, time progress, or export-at-time controls.',
      "Playback renderers must consume runtime timeline state; pause freezes output, scrubbing renders a deterministic frame, and the full animation cycle maps to state.timeline.durationSeconds instead of a local fixed duration.",
      "Playback renderers may compute an initial default duration, but must not watch state.timeline.durationSeconds and dispatch timeline.setDuration back to a computed local duration. User-edited timeline duration is the source of truth after initialization or reset.",
      "When non-looping playback reaches the end, pressing Play again restarts playback from time 0.",
      "Intrinsic-media upload timelines must stay paused at time 0 until source media exists; clearing the last media asset must pause and reset playback.",
      'Use panels.timeline: { mode: "keyframes" } or panels.timeline: true only when controls need keyframe diamonds, expanded timeline rows, easing, or keyframe editing.',
      "In keyframes mode, Creative Apps Kit infers keyframe diamonds from control type; AI must not manually pick a smaller subset of slider/vector/color-style controls.",
      "Keyframe state stores typed control values; valueLabel is display-only and must never be parsed by renderers or tests as the source of truth.",
      "Custom renderers with keyframes must consume evaluateCreativeAppsKitTimelineValues or useCreativeAppsKitEvaluatedValues for keyframed settings instead of raw state.values for those targets.",
      "Every inferred keyframe-capable control must be evaluated from runtime timeline keyframes and needs acceptance proving diamond creation, row creation, keyframe updates, scrub/playback evaluation, and product output change.",
      "Keyframe custom renderers must prove zoom, radar, and canvas viewport stability while expanding the timeline, creating keyframes, and scrubbing or playing the timeline.",
      "Keyframe renderers must not re-decode media or re-upload source textures on timeline ticks, scrubs, playback, or evaluated setting changes.",
      "Timeline-driven preview renderers must suspend or coalesce non-essential animation work during canvas drag, pan, pinch, zoom, and radar/center interactions without mutating the user's timeline play/pause state.",
      "Use keyframeable: false only on controls that are structurally unsupported by the shared keyframe capability helper; capable controls cannot opt out to hide broken animation wiring.",
      "Right-panel animation controls may tune renderer parameters such as mode, intensity, speed, or stagger only after animation intent is declared; they must not replace top timeline transport.",
      "Do not put Pause or Resume in panelActions; playback belongs to TimelinePanel transport controls.",
      "Do not replace TimelinePanel with an app-level playback, transport, or timeline panel to avoid runtime performance issues; fix the Creative Apps Kit runtime clock/state path instead.",
      'Custom timeline UI is allowed only for explicit referenceTimeline.mode "custom-reference-timeline" transfers with browser-backed referenceTimelineCoverage.',
      "Playback-only timelines stay collapsed and do not show keyframe diamonds or expanded keyframe rows.",
      "If timeline verification fails, wire the renderer to runtime timeline state or remove panels.timeline.",
    ],
    capabilities: [
      "draggable",
      "snap",
      "doubleClickReset",
      "dragMode:panel",
      "duration",
      "keyframes",
      "playback",
    ],
    commands: [
      "timeline.changeKeyframeEasing",
      "timeline.deleteControlKeyframes",
      "timeline.deleteKeyframe",
      "timeline.moveKeyframe",
      "timeline.selectKeyframe",
      "timeline.setCurrentTime",
      "timeline.setDuration",
      "timeline.setPlaying",
      "timeline.toggleLoop",
      "timeline.togglePlayback",
    ],
  },
  toolbar: {
    ...panel("toolbar", "ToolbarPanel", "bottom", ["top", "bottom"], "panel"),
    capabilities: ["draggable", "snap", "doubleClickReset", "history", "zoom", "radar"],
    commands: [
      "history.undo",
      "history.redo",
      "canvas.center",
      "canvas.zoomIn",
      "canvas.zoomOut",
      "canvas.zoomReset",
    ],
    kind: "toolbar",
  },
} as const satisfies Record<string, CreativeAppsKitComponentContract>;

export type CreativeAppsKitComponentContractId = keyof typeof EFFECTS_EDITOR_COMPONENT_CONTRACTS;

export function getCreativeAppsKitComponentContract<const Id extends CreativeAppsKitComponentContractId>(
  id: Id,
): (typeof EFFECTS_EDITOR_COMPONENT_CONTRACTS)[Id] {
  return EFFECTS_EDITOR_COMPONENT_CONTRACTS[id];
}

function control<
  const Id extends string,
  const VisualComponent extends string,
  const SectionLayout extends CreativeAppsKitSectionLayout,
  const LabelPolicy extends CreativeAppsKitLabelPolicy,
>(
  id: Id,
  visualComponent: VisualComponent,
  defaultSectionLayout: SectionLayout,
  labelPolicy: LabelPolicy,
): {
  readonly defaultSectionLayout: SectionLayout;
  readonly historyPolicy: "patch";
  readonly id: Id;
  readonly kind: "control";
  readonly labelPolicy: LabelPolicy;
  readonly schemaType: Id;
  readonly stateMode: "controlled";
  readonly visualComponent: VisualComponent;
} {
  return {
    defaultSectionLayout,
    historyPolicy: "patch",
    id,
    kind: "control",
    labelPolicy,
    schemaType: id,
    stateMode: "controlled",
    visualComponent,
  };
}

function panel<
  const Id extends string,
  const VisualComponent extends string,
  const Placement extends CreativeAppsKitPanelPlacement,
  const SnapEdges extends readonly CreativeAppsKitPanelSnapEdge[],
  const DragMode extends "handle" | "panel",
>(
  id: Id,
  visualComponent: VisualComponent,
  defaultPlacement: Placement,
  snapEdges: SnapEdges,
  dragMode: DragMode,
): {
  readonly aiUsageRules: readonly [`Render ${VisualComponent} only through PanelHost.`];
  readonly capabilities: readonly [
    "draggable",
    "snap",
    "doubleClickReset",
    `dragMode:${DragMode}`,
  ];
  readonly defaultPlacement: Placement;
  readonly historyPolicy: "optional";
  readonly id: Id;
  readonly kind: "panel";
  readonly requiredWrapper: "PanelHost";
  readonly schemaType: Id;
  readonly snapEdges: SnapEdges;
  readonly stateMode: "runtime-owned";
  readonly visualComponent: VisualComponent;
} {
  return {
    aiUsageRules: [`Render ${visualComponent} only through PanelHost.`],
    capabilities: [
      "draggable",
      "snap",
      "doubleClickReset",
      `dragMode:${dragMode}` as const,
    ],
    defaultPlacement,
    historyPolicy: "optional",
    id,
    kind: "panel",
    requiredWrapper: "PanelHost",
    schemaType: id,
    snapEdges,
    stateMode: "runtime-owned",
    visualComponent,
  };
}
