import {
  defineToolcraftPerformance,
  type ToolcraftPerformanceConfig,
} from "@/toolcraft/runtime";

export const appPerformance: ToolcraftPerformanceConfig = defineToolcraftPerformance({
  rendererPipeline: {
    passes: [
      {
        cacheKey: ["canvas.size.width", "canvas.size.height", "canvas.renderScale"],
        id: "simulation-fbos",
        inputs: ["canvas.size.width", "canvas.size.height", "canvas.renderScale"],
        invalidatedBy: ["canvas.size.width", "canvas.size.height", "canvas.renderScale"],
        kind: "preprocess",
        output: "source",
        quality: "preview",
        runsOn: "gpu",
      },
      {
        cacheKey: [
          "ink.palette.family",
          "ink.palette.shade",
          "brush.size",
          "brush.load",
          "brush.wetness",
          "brush.flow",
          "pointer.uv",
        ],
        id: "ink-splats",
        inputs: [
          "pointer.uv",
          "ink.palette",
          "brush.size",
          "brush.load",
          "brush.wetness",
          "brush.flow",
        ],
        invalidatedBy: [
          "pointer.uv",
          "ink.palette",
          "brush.size",
          "brush.load",
          "brush.wetness",
          "brush.flow",
        ],
        kind: "pixel-transform",
        output: "intermediate",
        quality: "preview",
        runsOn: "gpu",
      },
      {
        cacheKey: [
          "velocity-fbo",
          "dye-fbo",
          "brush.wetness",
          "brush.settle",
          "brush.taper",
          "brush.flow",
          "flow.auto",
          "flow.clearSignal",
        ],
        id: "fluid-step",
        inputs: [
          "velocity-fbo",
          "dye-fbo",
          "brush.wetness",
          "brush.settle",
          "brush.taper",
          "brush.flow",
          "flow.auto",
          "flow.clearSignal",
        ],
        invalidatedBy: [
          "animation-frame",
          "pointer.uv",
          "brush.wetness",
          "brush.settle",
          "brush.taper",
          "brush.flow",
          "flow.auto",
          "flow.clearSignal",
        ],
        kind: "pixel-transform",
        output: "intermediate",
        quality: "preview",
        runsOn: "gpu",
      },
      {
        cacheKey: [
          "dye-fbo",
          "appearance.background",
          "export.includeBackground",
          "paper.texture.enabled",
          "paper.texture.grain",
          "paper.texture.scale",
          "paper.texture.fiber",
          "paper.texture.mottle",
        ],
        id: "display-composite",
        inputs: [
          "dye-fbo",
          "appearance.background",
          "export.includeBackground",
          "paper.texture.enabled",
          "paper.texture.grain",
          "paper.texture.scale",
          "paper.texture.fiber",
          "paper.texture.mottle",
        ],
        invalidatedBy: [
          "animation-frame",
          "appearance.background",
          "export.includeBackground",
          "paper.texture.enabled",
          "paper.texture.grain",
          "paper.texture.scale",
          "paper.texture.fiber",
          "paper.texture.mottle",
        ],
        kind: "composite",
        output: "preview",
        quality: "retina",
        runsOn: "gpu",
      },
      {
        id: "image-export",
        inputs: [
          "preview-webgl-canvas",
          "export.image.format",
          "export.image.resolution",
          "export.includeBackground",
          "appearance.background",
          "paper.texture.enabled",
          "paper.texture.grain",
          "paper.texture.scale",
          "paper.texture.fiber",
          "paper.texture.mottle",
        ],
        invalidatedBy: [
          "export.image.format",
          "export.image.resolution",
          "export.includeBackground",
          "appearance.background",
          "paper.texture.enabled",
          "paper.texture.grain",
          "paper.texture.scale",
          "paper.texture.fiber",
          "paper.texture.mottle",
        ],
        kind: "export",
        output: "export",
        quality: "export",
        runsOn: "export-only",
      },
    ],
    interactionInvalidation: [
      {
        interaction: "animation-frame",
        invalidates: ["display-composite"],
        mustNotInvalidate: ["simulation-fbos"],
        targets: ["fluid.clock"],
      },
      {
        interaction: "control-change",
        invalidates: ["ink-splats", "display-composite", "image-export"],
        mustNotInvalidate: ["simulation-fbos"],
        targets: [
          "ink.palette",
          "brush.size",
          "brush.load",
          "brush.wetness",
          "brush.settle",
          "brush.taper",
          "brush.flow",
          "flow.auto",
          "flow.clearSignal",
          "paper.texture.enabled",
          "paper.texture.grain",
          "paper.texture.scale",
          "paper.texture.fiber",
          "paper.texture.mottle",
          "export.includeBackground",
          "appearance.background",
          "export.image.format",
          "export.image.resolution",
        ],
      },
      {
        interaction: "control-change",
        invalidates: ["simulation-fbos", "display-composite"],
        targets: ["canvas.aspectRatio", "canvas.size.width", "canvas.size.height"],
      },
      {
        interaction: "control-drag",
        invalidates: ["simulation-fbos", "display-composite"],
        targets: ["canvas.renderScale"],
      },
      {
        interaction: "viewport-drag",
        invalidates: ["display-composite"],
        mustNotInvalidate: ["simulation-fbos", "fluid-step", "ink-splats"],
        targets: ["canvas.viewport.offset"],
      },
      {
        interaction: "viewport-zoom",
        invalidates: ["display-composite"],
        mustNotInvalidate: ["simulation-fbos", "fluid-step", "ink-splats"],
        targets: ["canvas.viewport.zoom"],
      },
      {
        interaction: "export",
        invalidates: ["image-export"],
        mustNotInvalidate: ["simulation-fbos", "fluid-step", "ink-splats"],
        targets: ["export.image.format", "export.image.resolution", "export.action"],
      },
    ],
  },
  rendererStrategy: "webgl",
  rendererTechnique: {
    exportRenderer: "canvas-2d",
    fidelityRisks: [
      "PNG and JPG export composite the current WebGL preview canvas into the runtime export canvas.",
      "The default paper remains flat beige; optional procedural texture is user-controlled and has no uploaded source asset.",
    ],
    layers: [
      {
        content: ["shader"],
        exportMode: "composited",
        id: "backgroundLayer",
        kind: "background",
        primitiveCount: "high",
        renderer: "webgl",
        uiSelector: "[data-suminagashi-canvas]",
      },
      {
        content: ["shader", "dense-pattern"],
        exportMode: "included",
        id: "productForegroundLayer",
        kind: "product-foreground",
        primitiveCount: "high",
        renderer: "webgl",
        uiSelector: "[data-suminagashi-canvas]",
      },
      {
        content: ["composite"],
        exportMode: "composited",
        id: "exportComposite",
        kind: "export-composite",
        primitiveCount: "medium",
        renderer: "canvas-2d",
      },
    ],
    performanceRisks: [
      "Full pressure projection preserves the reference 28 GPU iterations, but it is deferred while the pointer is actively drawing and then resumes in frame-sized batches during a bounded post-release settle.",
      "Dense pointer input is coalesced into continuous line splats so fast strokes stay brush-like without processing every raw pointermove as a separate dye pass.",
      "Hover pointer movement is ignored by the fluid solver; only pressed brush input writes velocity or dye, pointerdown presents its first drop in the next animation frame, active strokes throttle display and wet-preview work, pointerup defers final splats to requestAnimationFrame, post-release settling runs full solver batches for a bounded wetness-based window, and Taper smoothly damps velocity before freeze.",
      "The display composite renders into a dye-sized 8-bit target and presents through WebGL2 framebuffer blit to preserve selected render scale with fewer fullscreen shader passes.",
      "Canvas resizing and render-scale changes rebuild simulation and dye framebuffers.",
    ],
    previewExportDifferenceReason:
      "Preview owns the live WebGL simulation; export uses the standard Toolcraft PNG helper and draws the current WebGL frame into the export canvas for background, alpha, and resolution handling.",
    previewRenderer: "webgl",
    productRepresentation: "pixel",
    referenceRendererChangeReason:
      "The reference uses Three.js WebGL; this app keeps WebGL but implements the passes directly so no runtime panels or reference shell are copied.",
    rendererStrategy: "webgl",
    rendererWorkload: "pixel-output",
    sourceRepresentation: "reference-runtime",
    whyNotAlternativeStrategies: [
      "DOM and SVG cannot reproduce the reference absorption-field fluid simulation.",
      "Canvas 2D would move dense pixel advection and pressure projection to the CPU.",
      "WebGPU is unnecessary for this reference-sized stable fluids workload and has less browser coverage.",
    ],
  },
  rendererWorkload: "pixel-output",
  scenarios: [
    {
      automated: true,
      automatedTestName: "perf: preview render stays under budget",
      browser: true,
      browserTestName: "browser perf: preview render stays under budget",
      budget: { maxLongTaskMs: 200, maxPreviewMs: 2000 },
      expectedObservable: "The flat-paper WebGL preview renders without blocking.",
      fixture: "Default 1920x1080 canvas at 2x render scale.",
      id: "preview-render",
      interaction: "preview-render",
      stress: true,
      stressFixture: {
        kind: "custom",
        reason: "Largest default preview workload combines fixed 1080p output and 2x backing pixels.",
        value: { renderScale: 2 },
      },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: animation frames stay responsive",
      browser: true,
      browserTestName: "browser perf: animation frames stay responsive",
      budget: { maxFrameGapMs: 120, maxLongTaskMs: 160 },
      expectedObservable: "Painted ink advection and optional Auto flow keep sampling frames.",
      fixture: "Painted simulation with Auto flow enabled.",
      id: "animation-frame",
      interaction: "animation-frame",
      stress: true,
      stressFixture: {
        kind: "custom",
        reason: "The live fluid solver is measured independently from the render-scale workload.",
        value: { autoFlow: true, renderScale: 1 },
      },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: render scale drag stays responsive",
      browser: true,
      browserTestName: "browser perf: render scale drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Resolution scale",
      expectedObservable: "Dragging render scale preserves a responsive WebGL preview.",
      fixture: "Default canvas with fluid preview active.",
      id: "render-scale-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "2x is the maximum runtime backing-pixel scale.",
        value: 2,
      },
      target: "canvas.renderScale",
      values: { default: 2, max: 2, min: 1 },
      workloadFixture: {
        kind: "large-canvas",
        reason: "The fixed 1920x1080 output is the heavy baseline before render-scale drag.",
        value: { output: { height: 1080, width: 1920 } },
      },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: canvas aspect ratio changes stay responsive",
      browser: true,
      browserTestName: "browser perf: canvas aspect ratio changes stay responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Aspect ratio",
      expectedObservable: "Aspect ratio changes rebuild WebGL output dimensions without blocking the panel.",
      fixture: "Default 1920x1080 canvas with fluid preview active.",
      id: "canvas-aspect-ratio-change",
      interaction: "control-change",
      stressFixture: {
        kind: "custom",
        reason: "4:3 switches to another canonical output size and forces framebuffer rebuild.",
        value: { height: 3, mode: "preset", value: "4:3", width: 4 },
      },
      target: "canvas.aspectRatio",
      values: {
        default: { height: 9, mode: "preset", value: "16:9", width: 16 },
        max: { height: 3, mode: "preset", value: "4:3", width: 4 },
        min: { height: 9, mode: "preset", value: "16:9", width: 16 },
      },
      workloadFixture: {
        kind: "custom",
        reason: "Measured at retina render scale because aspect changes rebuild backing buffers.",
        value: { renderScale: 2 },
      },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: canvas width changes stay responsive",
      browser: true,
      browserTestName: "browser perf: canvas width changes stay responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Canvas width",
      expectedObservable: "Canvas width edits rebuild WebGL output width without blocking the panel.",
      fixture: "Default 1920x1080 canvas with fluid preview active.",
      id: "canvas-width-change",
      interaction: "control-change",
      stressFixture: {
        kind: "custom",
        reason: "1600px is a real custom output width that forces a framebuffer resize.",
        value: { width: 1600 },
      },
      target: "canvas.size.width",
      values: { default: 1920, max: 1920, min: 1280 },
      workloadFixture: {
        kind: "custom",
        reason: "Measured at retina render scale because width changes rebuild backing buffers.",
        value: { renderScale: 2 },
      },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: canvas height changes stay responsive",
      browser: true,
      browserTestName: "browser perf: canvas height changes stay responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Canvas height",
      expectedObservable: "Canvas height edits rebuild WebGL output height without blocking the panel.",
      fixture: "Default 1920x1080 canvas with fluid preview active.",
      id: "canvas-height-change",
      interaction: "control-change",
      stressFixture: {
        kind: "custom",
        reason: "900px is a real custom output height that forces a framebuffer resize.",
        value: { height: 900 },
      },
      target: "canvas.size.height",
      values: { default: 1080, max: 1080, min: 720 },
      workloadFixture: {
        kind: "custom",
        reason: "Measured at retina render scale because height changes rebuild backing buffers.",
        value: { renderScale: 2 },
      },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: palette changes stay responsive",
      browser: true,
      browserTestName: "browser perf: palette changes stay responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Palette",
      expectedObservable: "Palette family and shade changes update future ink color.",
      fixture: "Palette component with family and shade buttons.",
      id: "ink-palette-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        reason: "Blue 900 is a dark high-contrast replacement ink token.",
        value: { family: "Blue", shade: "900" },
      },
      target: "ink.palette",
      values: {
        default: { family: "Slate", shade: "900" },
        max: { family: "Blue", shade: "900" },
        min: { family: "Red", shade: "700" },
      },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: brush size changes stay responsive",
      browser: true,
      browserTestName: "browser perf: brush size changes stay responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Size",
      expectedObservable: "Brush size updates future line-splat radius without rebuilding FBOs.",
      fixture: "Brush size slider with painted preview.",
      id: "brush-size-change",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "72px is the widest useful brush radius.",
        value: 72,
      },
      target: "brush.size",
      values: { default: 28, max: 72, min: 6 },
      workloadFixture: {
        kind: "custom",
        reason: "Brush size is measured against the live 2x WebGL preview baseline.",
        value: { renderScale: 2 },
      },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: brush load changes stay responsive",
      browser: true,
      browserTestName: "browser perf: brush load changes stay responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Load",
      expectedObservable: "Brush load updates future pigment strength without extra passes.",
      fixture: "Brush load slider with painted preview.",
      id: "brush-load-change",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "180% is the heaviest pigment load.",
        value: 180,
      },
      target: "brush.load",
      values: { default: 100, max: 180, min: 20 },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: brush wetness changes stay responsive",
      browser: true,
      browserTestName: "browser perf: brush wetness changes stay responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Wetness",
      expectedObservable: "Wetness updates immediate in-stroke advection without changing pass count.",
      fixture: "Wetness slider with painted preview.",
      id: "brush-wetness-change",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "100% is the strongest in-stroke spread.",
        value: 100,
      },
      target: "brush.wetness",
      values: { default: 70, max: 100, min: 0 },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: brush settle changes stay responsive",
      browser: true,
      browserTestName: "browser perf: brush settle changes stay responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Settle",
      expectedObservable: "Settle updates post-release solver duration without rebuilding resources.",
      fixture: "Settle slider with painted preview.",
      id: "brush-settle-change",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "200% is the longest exposed post-release full-solver window.",
        value: 200,
      },
      target: "brush.settle",
      values: { default: 100, max: 200, min: 0 },
      workloadFixture: {
        kind: "custom",
        reason: "Settle duration is measured against the live 2x WebGL preview baseline.",
        value: { renderScale: 2 },
      },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: brush taper changes stay responsive",
      browser: true,
      browserTestName: "browser perf: brush taper changes stay responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Taper",
      expectedObservable: "Taper updates the post-release velocity fade window without rebuilding resources.",
      fixture: "Taper slider with painted preview.",
      id: "brush-taper-change",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "200% is the smoothest and longest exposed post-release fade window.",
        value: 200,
      },
      target: "brush.taper",
      values: { default: 100, max: 200, min: 0 },
      workloadFixture: {
        kind: "custom",
        reason: "Taper duration is measured against the live 2x WebGL preview baseline.",
        value: { renderScale: 2 },
      },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: brush flow changes stay responsive",
      browser: true,
      browserTestName: "browser perf: brush flow changes stay responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Flow",
      expectedObservable: "Flow updates brush-driven velocity strength without rebuilding resources.",
      fixture: "Flow slider with painted preview.",
      id: "brush-flow-change",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "180% is the strongest brush-driven water movement.",
        value: 180,
      },
      target: "brush.flow",
      values: { default: 100, max: 180, min: 0 },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: auto flow toggle stays responsive",
      browser: true,
      browserTestName: "browser perf: auto flow toggle stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Auto",
      expectedObservable: "Auto flow toggles optional idle drops without blocking the preview.",
      fixture: "Auto flow switch.",
      id: "auto-flow-toggle",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        reason: "Turning optional auto flow on resumes the heaviest background behavior.",
        value: true,
      },
      target: "flow.auto",
      values: { default: false, max: true, min: false },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: clear action stays responsive",
      browser: true,
      browserTestName: "browser perf: clear action stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Clear",
      expectedObservable: "Clear fades ink to blank without blocking input.",
      fixture: "Clear action button with painted dye.",
      id: "clear-action",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        reason: "A clear signal triggers the fastest dye fade path.",
        value: 1,
      },
      target: "flow.clearSignal",
      values: { default: 0, max: 1, min: 0 },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: paper texture toggle stays responsive",
      browser: true,
      browserTestName: "browser perf: paper texture toggle stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Texture",
      expectedObservable: "Texture toggles procedural paper grain without rebuilding fluid state.",
      fixture: "Paper texture switch.",
      id: "paper-texture-toggle",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        reason: "Turning texture on exercises the procedural paper shader branch.",
        value: true,
      },
      target: "paper.texture.enabled",
      values: { default: false, max: true, min: false },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: paper grain changes stay responsive",
      browser: true,
      browserTestName: "browser perf: paper grain changes stay responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Grain",
      expectedObservable: "Grain updates procedural paper noise strength without rebuilding fluid state.",
      fixture: "Paper texture enabled.",
      id: "paper-grain-change",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "100% is the strongest exposed paper grain.",
        value: 100,
      },
      target: "paper.texture.grain",
      values: { default: 35, max: 100, min: 0 },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: paper scale changes stay responsive",
      browser: true,
      browserTestName: "browser perf: paper scale changes stay responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Scale",
      expectedObservable: "Scale updates procedural paper frequency without rebuilding fluid state.",
      fixture: "Paper texture enabled.",
      id: "paper-scale-change",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "220% is the coarsest exposed paper texture scale.",
        value: 220,
      },
      target: "paper.texture.scale",
      values: { default: 100, max: 220, min: 50 },
      workloadFixture: {
        kind: "custom",
        reason: "Paper scale frequency is measured against the live 2x WebGL preview baseline.",
        value: { renderScale: 2 },
      },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: paper fiber changes stay responsive",
      browser: true,
      browserTestName: "browser perf: paper fiber changes stay responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Fiber",
      expectedObservable: "Fiber updates directional paper streaks without rebuilding fluid state.",
      fixture: "Paper texture enabled.",
      id: "paper-fiber-change",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "100% is the strongest exposed paper fiber streaking.",
        value: 100,
      },
      target: "paper.texture.fiber",
      values: { default: 45, max: 100, min: 0 },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: paper mottle changes stay responsive",
      browser: true,
      browserTestName: "browser perf: paper mottle changes stay responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Mottle",
      expectedObservable: "Mottle updates low-frequency paper variation without rebuilding fluid state.",
      fixture: "Paper texture enabled.",
      id: "paper-mottle-change",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        reason: "100% is the strongest exposed paper mottling.",
        value: 100,
      },
      target: "paper.texture.mottle",
      values: { default: 30, max: 100, min: 0 },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: background include toggle stays responsive",
      browser: true,
      browserTestName: "browser perf: background include toggle stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Include",
      expectedObservable: "Background include toggles preview alpha without rebuilding fluid state.",
      fixture: "Background Include switch.",
      id: "background-include-toggle",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        reason: "Turning background off exercises transparent preview compositing.",
        value: false,
      },
      target: "export.includeBackground",
      values: { default: true, max: true, min: false },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: background color changes stay responsive",
      browser: true,
      browserTestName: "browser perf: background color changes stay responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Background",
      expectedObservable: "Paper color updates the display shader uniform.",
      fixture: "Background color picker.",
      id: "background-color-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        reason: "A darker beige makes output changes visually measurable.",
        value: "#e8dcc7",
      },
      target: "appearance.background",
      values: { default: "#efeae0", max: "#e8dcc7", min: "#f7f1e7" },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: image format changes stay responsive",
      browser: true,
      browserTestName: "browser perf: image format changes stay responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Format",
      expectedObservable: "Image format selection updates export encoding state.",
      fixture: "Image Export format select.",
      id: "image-format-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        reason: "JPG forces opaque export compositing.",
        value: "jpg",
      },
      target: "export.image.format",
      values: { default: "png", max: "jpg", min: "png" },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: image resolution changes stay responsive",
      browser: true,
      browserTestName: "browser perf: image resolution changes stay responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000 },
      controlLabel: "Resolution",
      expectedObservable: "Image resolution selection updates export dimensions.",
      fixture: "Image Export resolution select.",
      id: "image-resolution-change",
      interaction: "control-change",
      stressFixture: {
        kind: "large-canvas",
        reason: "8K is the largest available image export long edge.",
        value: "8k",
      },
      target: "export.image.resolution",
      values: { default: "4k", max: "8k", min: "2k" },
      workloadFixture: {
        kind: "custom",
        reason: "Image export resolution is measured with the live 2x WebGL preview baseline.",
        value: { renderScale: 2 },
      },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: export image stays under budget",
      browser: true,
      browserTestName: "browser perf: export image stays under budget",
      budget: { maxExportMs: 8000 },
      expectedObservable: "Export encodes the current drawing through the standard image helper.",
      fixture: "4K PNG export from the current WebGL frame.",
      id: "export-image",
      interaction: "export-copy",
      stress: true,
      stressFixture: {
        kind: "large-canvas",
        reason: "4K export is the default delivery workload.",
        value: "4k",
      },
      target: "export.action",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: animation viewport drag remains stable",
      browser: true,
      browserTestName: "browser perf: animation viewport drag remains stable",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 160 },
      expectedObservable: "Viewport drag coalesces non-essential auto work while animation continues.",
      fixture: "Animated fluid preview during real canvas drag.",
      id: "animation-viewport-drag",
      interaction: "animation-viewport-drag",
      stress: true,
      stressFixture: {
        kind: "custom",
        reason: "Animated viewport drag is the worst interaction coupling for the renderer.",
        value: { autoFlow: true, renderScale: 2 },
      },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: viewport zoom stress stays responsive",
      browser: true,
      browserTestName: "browser perf: viewport zoom stress stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 160 },
      expectedObservable: "Toolbar zoom does not rebuild fluid simulation resources.",
      fixture: "Animated fluid preview at 2x render scale.",
      id: "viewport-zoom-stress",
      interaction: "viewport-zoom-stress",
      stress: true,
      stressFixture: {
        kind: "custom",
        reason: "Zooming a live 2x WebGL canvas stresses viewport transforms and animation scheduling.",
        value: { autoFlow: true, renderScale: 2 },
      },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: viewport stays stable",
      browser: true,
      browserTestName: "browser perf: viewport stays stable",
      budget: { maxFrameGapMs: 120 },
      expectedObservable: "Idle preview frames do not alter canvas viewport offset or zoom.",
      fixture: "Default fluid preview.",
      id: "viewport-stability",
      interaction: "viewport-stability",
      workload: false,
    },
  ],
  usesCustomRenderer: true,
  workloadTargets: [
    "brush.size",
    "brush.settle",
    "brush.taper",
    "canvas.aspectRatio",
    "canvas.size.width",
    "canvas.size.height",
    "canvas.renderScale",
    "export.image.resolution",
    "paper.texture.scale",
  ],
});
