import {
  defineToolcraftPerformance,
  type ToolcraftPerformanceConfig,
  type ToolcraftPerformanceScenario,
} from "@/toolcraft/runtime";

import { productControlSections } from "./app-schema";

const workloadTargets = [
  "effect.mode",
  "pixelate.size",
  "dither.size",
  "dither.colorMode",
  "ascii.shape",
  "ascii.size",
  "halftone.size",
  "mosaic.size",
  "bricks.size",
  "pointillism.size",
  "threshold.colorMode",
  "bloom.radius",
  "export.image.resolution",
] as const;

const additionalWorkloadValues = [
  { defaultValue: 1, interaction: "control-drag", label: "Size", max: 16, min: 1, target: "dither.size" },
  { defaultValue: "duotone", interaction: "control-change", label: "Color mode", max: "grayscale", min: "source", target: "dither.colorMode" },
  { defaultValue: "mixed", interaction: "control-change", label: "Shape", max: "matrix", min: "mixed", target: "ascii.shape" },
  { defaultValue: 8, interaction: "control-drag", label: "Size", max: 50, min: 4, target: "ascii.size" },
  { defaultValue: 15, interaction: "control-drag", label: "Size", max: 100, min: 5, target: "halftone.size" },
  { defaultValue: 16, interaction: "control-drag", label: "Size", max: 64, min: 4, target: "mosaic.size" },
  { defaultValue: 22, interaction: "control-drag", label: "Size", max: 64, min: 8, target: "bricks.size" },
  { defaultValue: 6, interaction: "control-drag", label: "Dot size", max: 24, min: 2, target: "pointillism.size" },
  { defaultValue: "duotone", interaction: "control-change", label: "Color mode", max: "grayscale", min: "source", target: "threshold.colorMode" },
  { defaultValue: 0.5, interaction: "control-drag", label: "Radius", max: 1, min: 0, target: "bloom.radius" },
  { defaultValue: "4k", interaction: "control-change", label: "Resolution", max: "8k", min: "2k", target: "export.image.resolution" },
] as const;

function workloadScenario(
  item: (typeof additionalWorkloadValues)[number],
): ToolcraftPerformanceScenario {
  const isNumeric = typeof item.max === "number";
  const baseline = { renderScale: 2 };

  return {
    automated: true,
    automatedTestName: "perf: generated Effects control coverage stays responsive",
    browser: true,
    browserTestName: `browser perf: ${item.target} workload stays responsive`,
    budget: { maxFrameGapMs: 80, maxInteractionMs: 600, maxLongTaskMs: 180 },
    controlLabel: item.label,
    expectedObservable: `${item.target} changes the WebGL output during a real control interaction.`,
    fixture: "Built-in ring model at render scale 2",
    id: `workload-${item.target.replace(/[^a-z0-9]+/gi, "-")}`,
    interaction: item.interaction,
    stressFixture: {
      kind: "max-value",
      loadProfile: {
        hardLimit: item.max,
        metric: isNumeric ? "numeric-max" : "custom",
        smoothTarget: item.max,
        smoothTargetRatio: 1,
        target: item.target,
        userFacingRange: "fully-guaranteed",
      },
      reason: `The exposed maximum for ${item.target} is the heaviest useful control value.`,
      value: item.max,
    },
    target: item.target,
    values: { default: item.defaultValue, max: item.max, min: item.min },
    workload: true,
    workloadFixture: {
      kind: "custom",
      loadProfile: {
        hardLimit: baseline,
        metric: "custom",
        smoothTarget: baseline,
        smoothTargetRatio: 1,
        target: "canvas.renderScale",
        userFacingRange: "fully-guaranteed",
      },
      reason: "Every workload control is measured against the full preview backing scale.",
      value: baseline,
    },
  };
}

const coreCoveredTargets = new Set<string>([
  "effect.mode",
  "pixelate.size",
  "source.model",
  "view.orbit",
  "actions.output",
  "grain.dynamic",
  ...additionalWorkloadValues.map((item) => item.target),
]);

function createResponsivenessScenarios(): ToolcraftPerformanceScenario[] {
  return productControlSections.flatMap((section) =>
    Object.values(section.controls).flatMap((control) => {
      if (control.type === "panelActions" || coreCoveredTargets.has(control.target)) {
        return [];
      }

      const isSlider = control.type === "slider" || control.type === "rangeSlider";
      const controlLabel =
        typeof control.label === "string" ? control.label : section.title ?? control.target;

      return [
        {
          automated: true,
          automatedTestName: "perf: generated Effects control coverage stays responsive",
          browser: true,
          browserTestName: `browser perf: ${control.target} remains responsive`,
          budget: { maxFrameGapMs: 90, maxInteractionMs: 650, maxLongTaskMs: 180 },
          controlLabel,
          expectedObservable: `${control.target} updates runtime state and visible WebGL output without freezing the canvas.`,
          fixture: "Built-in ring model with the owning conditional section visible",
          id: `responsive-${control.target.replace(/[^a-z0-9]+/gi, "-")}`,
          interaction: isSlider ? "control-drag" : "control-change",
          target: control.target,
          workload: false,
        } satisfies ToolcraftPerformanceScenario,
      ];
    }),
  );
}

export const appPerformance: ToolcraftPerformanceConfig = defineToolcraftPerformance({
  browserCheckPolicy: {
    fallbackRunner: "playwright",
    fallbackWhen: ["agent-browser-unavailable", "ci"],
    preferredRunner: "agent-browser",
  },
  rendererPipeline: {
    interactionInvalidation: [
      {
        interaction: "media-import",
        invalidates: [
          "model-decode",
          "scene-normalize",
          "scene-raster",
          "effects-composite",
          "preview-present",
        ],
        targets: ["source.model"],
      },
      {
        interaction: "control-change",
        invalidates: ["effects-composite", "preview-present"],
        mustNotInvalidate: ["model-decode", "scene-normalize", "scene-raster"],
        targets: ["effect.mode", "dither.colorMode", "ascii.shape", "threshold.colorMode"],
      },
      {
        interaction: "control-drag",
        invalidates: ["effects-composite", "preview-present"],
        mustNotInvalidate: ["model-decode", "scene-normalize", "scene-raster"],
        targets: [
          "pixelate.size",
          "dither.size",
          "ascii.size",
          "halftone.size",
          "mosaic.size",
          "bricks.size",
          "pointillism.size",
          "bloom.radius",
          "adjustments.contrast",
          "bloom.strength",
        ],
      },
      {
        interaction: "control-drag",
        invalidates: [
          "scene-raster",
          "effects-composite",
          "orientation-gizmo",
          "preview-present",
        ],
        mustNotInvalidate: [
          "studio-environment",
          "model-decode",
          "scene-normalize",
        ],
        targets: ["view.orbit"],
      },
      {
        interaction: "animation-frame",
        invalidates: ["animated-present", "preview-present"],
        mustNotInvalidate: [
          "model-decode",
          "scene-normalize",
          "scene-raster",
          "effects-composite",
        ],
        targets: ["grain.dynamic", "grain.amount"],
      },
      {
        interaction: "viewport-drag",
        invalidates: [],
        mustNotInvalidate: [
          "model-decode",
          "scene-normalize",
          "scene-raster",
          "effects-composite",
        ],
        targets: ["canvas.offset"],
      },
      {
        interaction: "viewport-zoom",
        invalidates: [],
        mustNotInvalidate: [
          "model-decode",
          "scene-normalize",
          "scene-raster",
          "effects-composite",
        ],
        targets: ["canvas.zoom"],
      },
      {
        interaction: "export",
        invalidates: ["png-export"],
        mustNotInvalidate: ["model-decode"],
        targets: ["actions.output", "export.image.resolution"],
      },
    ],
    passes: [
      {
        cacheKey: ["procedural light panels", "PMREM convolution"],
        id: "studio-environment",
        inputs: ["six local light panels", "PMREM convolution"],
        invalidatedBy: ["app load"],
        kind: "preprocess",
        output: "source",
        quality: "full",
        runsOn: "gpu",
      },
      {
        cacheKey: ["mediaAsset.id", "mediaAsset.dataUrl"],
        id: "model-decode",
        inputs: ["source.model", "built-in ring model"],
        invalidatedBy: ["source.model"],
        kind: "decode",
        output: "source",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: ["decoded model identity"],
        id: "scene-normalize",
        inputs: ["model-decode"],
        invalidatedBy: ["model-decode"],
        kind: "preprocess",
        output: "intermediate",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: ["scene", "camera pose", "procedural studio environment", "view.orbit", "background", "canvas backing size"],
        id: "scene-raster",
        inputs: ["scene-normalize", "studio-environment", "MeshPhysical material", "view.orbit", "scene.background", "canvas.size", "canvas.renderScale"],
        invalidatedBy: ["source.model", "view.orbit", "scene.background", "canvas.size", "canvas.renderScale"],
        kind: "rasterize",
        output: "intermediate",
        quality: "preview",
        runsOn: "gpu",
      },
      {
        cacheKey: ["cached MSAA scene texture", "active effect shader pass", "ordered post passes"],
        id: "effects-composite",
        inputs: [
          "scene-raster",
          "active stylized shader pass",
          "Bloom > Depth of Field > Chromatic",
          "pre-grain cache",
          "single-sampled HalfFloat post targets",
          "terminal tone-map and sRGB transform",
        ],
        invalidatedBy: ["effect controls", "adjustment controls", "post-processing controls"],
        kind: "pixel-transform",
        output: "preview",
        quality: "preview",
        runsOn: "gpu",
      },
      {
        cacheKey: ["pre-grain cache texture", "time", "grain uniforms"],
        id: "animated-present",
        inputs: [
          "effects-composite cache",
          "Film Grain > Gradient Overlay > Vignette",
          "adjustments",
          "terminal output conversion without an input copy",
          "grain uniforms",
          "time",
        ],
        invalidatedBy: ["grain.dynamic", "grain.amount", "animation frame"],
        kind: "composite",
        output: "intermediate",
        quality: "preview",
        runsOn: "gpu",
      },
      {
        cacheKey: ["view.orbit", "editor theme", "fixed DPR 2"],
        id: "orientation-gizmo",
        inputs: ["view.orbit", "viewport theme"],
        invalidatedBy: ["view.orbit", "theme change"],
        kind: "handles",
        output: "overlay",
        quality: "retina",
        runsOn: "main",
      },
      {
        cacheKey: ["animated-present texture", "viewport presentation"],
        id: "preview-present",
        inputs: ["animated-present"],
        invalidatedBy: ["effects-composite", "animated-present"],
        kind: "composite",
        output: "preview",
        quality: "preview",
        runsOn: "gpu",
      },
      {
        cacheKey: ["source.model", "state.values", "canvas.size", "export.image.resolution"],
        id: "png-export",
        inputs: ["scene-normalize", "effects-composite", "Background", "Image Export"],
        invalidatedBy: ["export.png"],
        kind: "export",
        output: "export",
        quality: "export",
        runsOn: "export-only",
      },
    ],
  },
  rendererStrategy: "webgl",
  rendererTechnique: {
    exportRenderer: "webgl",
    fidelityRisks: [
      "Effect mappings were validated against the recorded behavior baseline; the base scene now uses an independently tuned model profile and locally generated studio environment.",
      "External glTF sidecar files are not available from a single fileDrop upload; embedded glTF and GLB are the reliable formats.",
    ],
    layers: [
      {
        content: ["shader"],
        exportMode: "included",
        id: "background",
        kind: "background",
        primitiveCount: "low",
        renderer: "webgl",
        uiSelector: '[data-toolcraft-product-output="mesh-fx"]',
      },
      {
        content: ["geometry", "shader", "dense-pattern", "noise"],
        exportMode: "included",
        id: "product-foreground",
        kind: "product-foreground",
        primitiveCount: "high",
        renderer: "webgl",
        uiSelector: '[data-toolcraft-product-output="mesh-fx-canvas"]',
      },
      {
        content: ["handles"],
        exportMode: "excluded",
        id: "orientation-gizmo",
        kind: "editing-handles",
        primitiveCount: "low",
        renderer: "dom",
        uiSelector: '[data-toolcraft-canvas-handle="orientation-gizmo"]',
      },
      {
        content: ["composite"],
        exportMode: "composited",
        id: "export-composite",
        kind: "export-composite",
        primitiveCount: "low",
        renderer: "webgl",
      },
    ],
    performanceRisks: [
      "8K export can approach browser WebGL texture and memory limits.",
      "High-poly uploaded meshes and multi-tap blur/bloom can increase GPU frame time.",
      "Animated film grain requires continuous composite frames while enabled.",
    ],
    previewExportDifferenceReason:
      "Preview uses the full fitted viewport at browser DPR multiplied by the selected render scale, with preview-logical shader resolution kept separate from physical backing pixels; export reruns the same GPU pipeline at the selected 2K/4K/8K image dimensions and scales pixel-sized uniforms from the current preview baseline width.",
    previewRenderer: "webgl",
    productRepresentation: "pixel",
    referenceRendererChangeReason:
      "The WebGL effect algorithms run inside Toolcraft's Three.js scene, media, canvas, and export lifecycle with GPU-native preview and export output.",
    rendererStrategy: "webgl",
    rendererWorkload: "pixel-output",
    sourceRepresentation: "mixed",
    whyNotAlternativeStrategies: [
      "DOM and SVG cannot preserve mesh depth, lighting, occlusion, and per-pixel shader effects.",
      "Canvas 2D would move the shader workload to the CPU and make live slider updates and 8K export substantially more expensive.",
      "WebGPU has narrower compatibility and no benefit over the mature Three.js GLB/OBJ/WebGL path for this workload.",
    ],
  },
  rendererWorkload: "pixel-output",
  scenarios: [
    {
      automated: true,
      automatedTestName: "perf: worst-case WebGL preview stays under budget",
      browser: true,
      browserTestName: "browser perf: worst-case WebGL preview stays under budget",
      budget: { maxFrameGapMs: 90, maxLongTaskMs: 180, maxPreviewMs: 1800 },
      expectedObservable: "The 4K-class WebGL preview renders the built-in model with Bloom and Grain without blocking the UI.",
      fixture: "3840x2160 canvas, render scale 2, Bloom and animated Grain enabled",
      id: "webgl-preview-stress",
      interaction: "preview-render",
      stress: true,
      stressFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { bloom: true, grain: true, height: 2160, renderScale: 2, width: 3840 },
          metric: "custom",
          smoothTarget: { bloom: true, grain: true, height: 2160, renderScale: 2, width: 3840 },
          smoothTargetRatio: 1,
          target: "preview.combined",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Largest useful 4K-class preview with full resolution scale and continuously updating post effects.",
        value: { bloom: true, grain: true, height: 2160, renderScale: 2, width: 3840 },
      },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: camera orbit remains responsive",
      browser: true,
      browserTestName: "browser perf: view.orbit remains responsive",
      budget: { maxFrameGapMs: 90, maxInteractionMs: 650, maxLongTaskMs: 180 },
      expectedObservable:
        "Dragging an orientation-gizmo point diagonally tracks the pointer on the sphere, updates the camera pose and visible WebGL output, and does not rebuild model or environment resources.",
      fixture: "Built-in ring model at render scale 2 with the bottom-left orientation gizmo",
      id: "responsive-view-orbit",
      interaction: "control-drag",
      stressFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { renderScale: 2 },
          metric: "custom",
          smoothTarget: { renderScale: 2 },
          smoothTargetRatio: 1,
          target: "canvas.renderScale",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Camera orbit is measured against the full preview backing scale.",
        value: { renderScale: 2 },
      },
      target: "view.orbit",
      uiSelector: '[data-toolcraft-canvas-handle="orientation-gizmo"]',
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: effect mode changes stay responsive",
      browser: true,
      browserTestName: "browser perf: effect mode changes stay responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 450, maxLongTaskMs: 160 },
      controlLabel: "Effect",
      expectedObservable: "Changing Effect swaps shader branches without re-decoding the model.",
      fixture: "Built-in ring model and full Effects option set",
      id: "effect-mode-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: "bricks",
          metric: "custom",
          smoothTarget: "bricks",
          smoothTargetRatio: 1,
          target: "effect.mode",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Bricks uses cell shading, grout, studs, bevel, and lighting in one branch.",
        value: "bricks",
      },
      target: "effect.mode",
      values: { default: "dither", max: "bricks", min: "none" },
      workload: true,
      workloadFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { renderScale: 2 },
          metric: "custom",
          smoothTarget: { renderScale: 2 },
          smoothTargetRatio: 1,
          target: "canvas.renderScale",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Effect mode changes are measured against the full preview backing scale.",
        value: { renderScale: 2 },
      },
    },
    {
      automated: true,
      automatedTestName: "perf: pixelate size drag stays responsive",
      browser: true,
      browserTestName: "browser perf: pixelate size drag stays responsive",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 500, maxLongTaskMs: 160 },
      controlLabel: "Size",
      expectedObservable: "Dragging Pixelate Size updates output during the drag without rebuilding model resources.",
      fixture: "Pixelate mode on the built-in ring model",
      id: "pixelate-size-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: 128,
          metric: "numeric-max",
          smoothTarget: 128,
          smoothTargetRatio: 1,
          target: "pixelate.size",
          userFacingRange: "fully-guaranteed",
        },
        reason: "The exposed Pixelate Size maximum must remain a live GPU uniform update.",
        value: 128,
      },
      target: "pixelate.size",
      values: { default: 8, max: 128, min: 2 },
      workload: true,
      workloadFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { renderScale: 2 },
          metric: "custom",
          smoothTarget: { renderScale: 2 },
          smoothTargetRatio: 1,
          target: "canvas.renderScale",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Pixelate dragging is measured against the full preview backing scale.",
        value: { renderScale: 2 },
      },
    },
    {
      automated: true,
      automatedTestName: "perf: high-poly OBJ import stays responsive",
      browser: true,
      browserTestName: "browser perf: high-poly OBJ import stays responsive",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 1800, maxLongTaskMs: 250, maxPreviewMs: 2000 },
      expectedObservable: "A generated 50k-face OBJ replaces the built-in model and produces visible rendered pixels.",
      fixture: "Generated 50,000-face OBJ file",
      id: "model-media-import",
      interaction: "media-import",
      stressFixture: {
        kind: "media",
        loadProfile: {
          hardLimit: { height: 2160, width: 3840 },
          metric: "media-area",
          smoothTarget: { height: 2160, width: 3840 },
          smoothTargetRatio: 1,
          target: "source.model",
          userFacingRange: "fully-guaranteed",
        },
        reason: "The upload path uses a 4K-equivalent media fixture while the OBJ generator supplies dense geometry.",
        value: { height: 2160, width: 3840 },
      },
      target: "source.model",
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: 4K image export stays under budget",
      browser: true,
      browserTestName: "browser perf: 4K image export stays under budget",
      budget: { maxExportMs: 6500, maxInteractionMs: 2000, maxLongTaskMs: 250 },
      expectedObservable: "Export produces decoded 4096px-long-edge image bytes.",
      fixture: "4K PNG export with Bloom and Gradient Overlay",
      id: "image-export-4k",
      interaction: "export-copy",
      stressFixture: {
        kind: "large-canvas",
        loadProfile: {
          hardLimit: 4096,
          metric: "numeric-max",
          smoothTarget: 4096,
          smoothTargetRatio: 1,
          target: "export.image.resolution",
          userFacingRange: "fully-guaranteed",
        },
        reason: "4K is the default image export tier and must be production-safe.",
        value: 4096,
      },
      target: "actions.output",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: viewport remains stable across effects",
      browser: true,
      browserTestName: "browser perf: viewport remains stable across effects",
      budget: { maxFrameGapMs: 80, maxInteractionMs: 450 },
      expectedObservable: "Effect changes do not alter canvas zoom or offset.",
      fixture: "Built-in ring model with toolbar zoom and effect changes",
      id: "effects-viewport-stability",
      interaction: "viewport-stability",
      target: "effect.mode",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: stressed WebGL viewport zoom remains smooth",
      browser: true,
      browserTestName: "browser perf: stressed WebGL viewport zoom remains smooth",
      budget: { maxFrameGapMs: 90, maxInteractionMs: 650, maxLongTaskMs: 180 },
      expectedObservable: "Real toolbar zoom stays stable over the combined Bloom and Grain workload.",
      fixture: "Bloom plus animated Grain at render scale 2",
      id: "effects-viewport-zoom-stress",
      interaction: "viewport-zoom-stress",
      stress: true,
      stressFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { bloom: true, grain: true, renderScale: 2 },
          metric: "custom",
          smoothTarget: { bloom: true, grain: true, renderScale: 2 },
          smoothTargetRatio: 1,
          target: "viewport.zoom.combined",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Combined post effects and full preview backing pixels are the realistic zoom stress state.",
        value: { bloom: true, grain: true, renderScale: 2 },
      },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: animated grain frame loop stays smooth",
      browser: true,
      browserTestName: "browser perf: animated grain frame loop stays smooth",
      budget: { maxFrameGapMs: 90, maxLongTaskMs: 180 },
      expectedObservable: "Animated Film Grain produces changing frames without a timeline.",
      fixture: "Film Grain enabled, Animate on, amount 1",
      id: "grain-animation-frame",
      interaction: "animation-frame",
      stress: true,
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: 1,
          metric: "numeric-max",
          smoothTarget: 1,
          smoothTargetRatio: 1,
          target: "grain.amount",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Maximum Grain amplitude keeps the autonomous frame path visibly active.",
        value: 1,
      },
      target: "grain.amount",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: animated grain yields to viewport drag",
      browser: true,
      browserTestName: "browser perf: animated grain yields to viewport drag",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 700, maxLongTaskMs: 190 },
      expectedObservable: "Dragging the real canvas viewport remains responsive while Grain animation continues afterward.",
      fixture: "Film Grain enabled during canvas viewport drag",
      id: "grain-animation-viewport-drag",
      interaction: "animation-viewport-drag",
      stress: true,
      stressFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { grain: 1, renderScale: 2 },
          metric: "custom",
          smoothTarget: { grain: 1, renderScale: 2 },
          smoothTargetRatio: 1,
          target: "grain.viewport-drag",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Maximum grain at full backing scale is the heaviest animated viewport interaction.",
        value: { grain: 1, renderScale: 2 },
      },
      target: "grain.dynamic",
      workload: false,
    },
    ...additionalWorkloadValues.map(workloadScenario),
    ...createResponsivenessScenarios(),
  ],
  usesCustomRenderer: true,
  workloadTargets,
});
