import type { ToolcraftControlSectionInventoryEntry } from "./acceptance/types";
import { maskSectionInventory } from "./circle-mask-acceptance";

export const waveControlSectionInventory: readonly ToolcraftControlSectionInventoryEntry[] = [
  {
    entity: "Output background",
    entityId: "background",
    finiteSelectors: [
      {
        reason: "Background inclusion changes its own preview and artifact compositing outcome.",
        role: "parameter",
        target: "export.includeBackground",
      },
    ],
    groupingReason: "Inclusion and color jointly define the runtime-owned output background.",
    id: "background",
    targets: ["export.includeBackground", "appearance.background"],
    title: "Background",
  },
  {
    entity: "Vault structure",
    entityId: "structure",
    finiteSelectors: [
      {
        affectedTargets: [],
        reason: "Shape selects vault or dome geometry and gates Dome length.",
        role: "branch",
        target: "structure.shape",
      },
    ],
    groupingReason: "Form, rhythm, and deformation controls define one continuous rib structure.",
    id: "structure",
    targets: [
      "structure.shape",
      "structure.radius",
      "structure.domeLength",
      "structure.arc",
      "structure.spacing",
      "structure.count",
      "structure.twist",
      "structure.wave",
      "structure.waveLength",
    ],
    title: "Structure",
  },
  {
    entity: "Rib profile",
    entityId: "rib",
    finiteSelectors: [
      {
        reason: "Taper side changes its own geometric direction without changing peer relevance.",
        role: "parameter",
        target: "rib.taperSide",
      },
    ],
    groupingReason: "Profile dimensions, rounding, and taper jointly define every swept rib.",
    id: "rib",
    targets: [
      "rib.width",
      "rib.depth",
      "rib.corner",
      "rib.taperStart",
      "rib.taperTip",
      "rib.taperSide",
    ],
    title: "Rib",
  },
  {
    entity: "Photographic camera",
    entityId: "camera",
    finiteSelectors: [],
    groupingReason: "Position, orientation, and field of view author one fixed camera framing.",
    id: "camera",
    targets: [
      "camera.position",
      "camera.height",
      "camera.yaw",
      "camera.pitch",
      "camera.roll",
      "camera.fov",
    ],
    title: "Camera",
  },
  {
    entity: "Scene lighting",
    entityId: "light",
    finiteSelectors: [
      {
        affectedTargets: [],
        reason:
          "Cast shadows switches the sun between shadowed and pure directional shading and gates Shadow softness.",
        role: "branch",
        target: "light.shadows",
      },
    ],
    groupingReason: "Sun, cast shadows, and hemisphere fill jointly light the rib geometry.",
    id: "light",
    targets: [
      "light.azimuth",
      "light.elevation",
      "light.intensity",
      "light.color",
      "light.shadows",
      "light.shadowSoftness",
      "light.ambient",
      "light.skyColor",
      "light.groundColor",
    ],
    title: "Light",
  },
  {
    entity: "Sky and atmosphere",
    entityId: "sky",
    finiteSelectors: [],
    groupingReason: "Visible sky, environment lighting, and fog define one atmospheric enclosure.",
    id: "sky",
    targets: [
      "sky.gradient",
      "sky.lightGradient",
      "sky.envIntensity",
      "sky.fogNear",
      "sky.fogFar",
      "sky.fogColor",
    ],
    title: "Sky",
  },
  {
    entity: "Rib material",
    entityId: "material",
    finiteSelectors: [],
    groupingReason: "Base color, roughness, and clearcoat define one physical rib material.",
    id: "material",
    targets: [
      "material.color",
      "material.roughness",
      "material.clearcoat",
      "material.clearcoatRoughness",
    ],
    title: "Material",
  },
  {
    entity: "Frame post-processing",
    entityId: "post",
    finiteSelectors: [
      {
        affectedTargets: [],
        reason: "Depth of field enables the bokeh pass and gates Focus distance and Aperture.",
        role: "branch",
        target: "post.depthOfField",
      },
    ],
    groupingReason: "Exposure, bloom, screen-space occlusion, and focus finish one rendered frame.",
    id: "post",
    targets: [
      "post.exposure",
      "post.bloom",
      "post.bloomThreshold",
      "post.occlusion",
      "post.occlusionRadius",
      "post.depthOfField",
      "post.focus",
      "post.aperture",
    ],
    title: "Post-processing",
  },
  {
    entity: "Atmospheric haze overlay",
    entityId: "haze",
    finiteSelectors: [
      {
        reason: "Blend changes only how the tint gradient composites over the frame.",
        role: "parameter",
        target: "haze.blend",
      },
    ],
    groupingReason:
      "The tint gradient and the sun glow together form one screen-space atmosphere layer.",
    id: "haze",
    targets: [
      "haze.gradient",
      "haze.strength",
      "haze.blend",
      "haze.glowColor",
      "haze.glowPosition",
      "haze.glowRadius",
      "haze.glowStrength",
    ],
    title: "Haze",
  },
  {
    entity: "One-way rib flow",
    entityId: "flow",
    finiteSelectors: [
      { target: "flow.travel", role: "parameter", reason: "Whole ribs per loop change only travel distance and speed." },
      { target: "flow.direction", role: "parameter", reason: "Direction changes only the sign of rib travel." },
      { target: "flow.glowOrbit", role: "parameter", reason: "Whole turns change only the optional glow trajectory." },
    ],
    groupingReason: "Travel, direction and the optional glow orbit define one forward loop.",
    id: "flow",
    targets: ["flow.travel", "flow.direction", "flow.glowOrbit", "flow.glowOrbitRadius"],
    title: "Flow",
  },
  {
    entity: "Reference presets",
    entityId: "presets",
    finiteSelectors: [],
    groupingReason:
      "The four reference-look commands load matched scene and Flow values across every scene entity.",
    id: "presets",
    targets: ["presets.apply"],
    title: "Presets",
  },
  maskSectionInventory,
];
