import type { ToolcraftRenderPass } from "@/toolcraft/runtime";

import { grassScanPipelinePasses } from "./app-renderer-scan-pipeline";
import {
  grassCloverBlendChangeTargets,
  grassCloverBlendTargets,
  grassButterflyLayoutInputTargets,
  grassEnvironmentChangeTargets,
  grassEnvironmentMediaTargets,
  grassGroundGeometryInputTargets,
  grassLayoutInputTargets,
  grassNoisePreviewInputTargets,
  grassNoisePreviewTargets,
  grassRenderChangeTargets,
  grassRenderSliderTargets,
  lawnLayoutInputTargets,
} from "./grass/grass-render-targets";

export const grassRendererPassDefinitions = [
  {
    cacheKey: grassNoisePreviewInputTargets,
    cost: {
      dimensions: [
        "terrain-octaves",
        "tall-mask-octaves",
        "lawn-mask-octaves",
        "clover-mask-octaves",
      ],
      frequency: "interaction",
      relationship: "linear",
    },
    id: "grass-noise-preview",
    inputs: grassNoisePreviewInputTargets,
    invalidatedBy: grassNoisePreviewTargets,
    kind: "rasterize",
    lifecycle: { cache: "memoized", resourceScope: "renderer" },
    output: "preview",
    quality: "full",
    runsOn: "gpu",
  },
  {
    cacheKey: grassGroundGeometryInputTargets,
    cost: {
      dimensions: ["terrain-octaves"],
      frequency: "interaction",
      relationship: "linear",
    },
    id: "grass-ground-geometry-build",
    inputs: grassGroundGeometryInputTargets,
    invalidatedBy: grassGroundGeometryInputTargets,
    kind: "vector-build",
    lifecycle: { cache: "memoized", resourceScope: "renderer" },
    output: "intermediate",
    quality: "full",
    runsOn: "main",
  },
  {
    cacheKey: grassLayoutInputTargets,
    cost: {
      dimensions: ["blade-count", "terrain-octaves", "tall-mask-octaves"],
      frequency: "interaction",
      relationship: "product",
    },
    id: "grass-layout-build",
    inputs: grassLayoutInputTargets,
    invalidatedBy: grassLayoutInputTargets,
    kind: "vector-build",
    lifecycle: { cache: "memoized", resourceScope: "renderer" },
    output: "intermediate",
    quality: "full",
    runsOn: "main",
  },
  {
    cacheKey: lawnLayoutInputTargets,
    cost: {
      dimensions: [
        "lawn-blade-count",
        "terrain-octaves",
        "lawn-mask-octaves",
      ],
      frequency: "interaction",
      relationship: "product",
    },
    id: "grass-lawn-layout-build",
    inputs: lawnLayoutInputTargets,
    invalidatedBy: lawnLayoutInputTargets,
    kind: "vector-build",
    lifecycle: { cache: "memoized", resourceScope: "renderer" },
    output: "intermediate",
    quality: "full",
    runsOn: "main",
  },
  {
    cacheKey: ["butterflies.enabled"],
    cost: {
      dimensions: [],
      frequency: "discrete",
      relationship: "constant",
    },
    id: "grass-butterfly-resource",
    inputs: ["butterflies.enabled"],
    invalidatedBy: ["butterflies.enabled"],
    kind: "decode",
    lifecycle: { cache: "memoized", resourceScope: "source" },
    output: "source",
    quality: "full",
    runsOn: "main",
  },
  {
    cacheKey: grassButterflyLayoutInputTargets,
    cost: {
      dimensions: ["butterfly-count", "terrain-octaves"],
      frequency: "interaction",
      relationship: "product",
    },
    id: "grass-butterfly-layout-build",
    inputs: grassButterflyLayoutInputTargets,
    invalidatedBy: grassButterflyLayoutInputTargets,
    kind: "vector-build",
    lifecycle: { cache: "memoized", resourceScope: "renderer" },
    output: "intermediate",
    quality: "full",
    runsOn: "main",
  },
  {
    cacheKey: ["rendererId"],
    cost: {
      dimensions: [],
      frequency: "discrete",
      relationship: "constant",
    },
    id: "grass-scene-resource",
    inputs: ["canvas.size", "canvas.renderScale"],
    invalidatedBy: ["canvas.size", "canvas.renderScale"],
    kind: "composite",
    lifecycle: { cache: "retained-resource", resourceScope: "renderer" },
    output: "intermediate",
    quality: "full",
    runsOn: "gpu",
  },
  {
    cacheKey: [
      ...grassEnvironmentChangeTargets,
      ...grassEnvironmentMediaTargets,
    ],
    cost: {
      dimensions: [],
      frequency: "discrete",
      relationship: "constant",
    },
    id: "grass-environment-resource",
    inputs: [
      ...grassEnvironmentChangeTargets,
      ...grassEnvironmentMediaTargets,
    ],
    invalidatedBy: [
      ...grassEnvironmentChangeTargets,
      ...grassEnvironmentMediaTargets,
    ],
    kind: "decode",
    lifecycle: { cache: "memoized", resourceScope: "source" },
    output: "source",
    quality: "full",
    runsOn: "main",
  },
  ...grassScanPipelinePasses,
  {
    cost: {
      dimensions: [
        "blade-count",
        "lawn-blade-count",
        "live-preview-tall-count",
        "live-preview-lawn-count",
        "tufted-scan-count",
        "wild-scan-count",
        "white-flower-count",
        "yellow-flower-count",
        "rock-scan-count",
        "preview-render-scale",
        "butterfly-count",
        "clover-mask-octaves",
      ],
      frequency: "frame",
      relationship: "product",
    },
    id: "grass-scene-render",
    inputs: [
      "grass-ground-geometry-build",
      "grass-layout-build",
      "grass-lawn-layout-build",
      "grass-butterfly-resource",
      "grass-butterfly-layout-build",
      "grass-environment-resource",
      "grass-scan-resource",
      "grass-tufted-layout-build",
      "grass-wild-layout-build",
      "grass-white-layout-build",
      "grass-yellow-layout-build",
      "grass-rock-layout-build",
      ...grassRenderSliderTargets,
      ...grassRenderChangeTargets,
      ...grassCloverBlendTargets,
      ...grassCloverBlendChangeTargets,
      "timeline.currentTimeSeconds",
      "renderer.pointerDirection",
    ],
    invalidatedBy: [
      "grass-ground-geometry-build",
      "grass-layout-build",
      "grass-lawn-layout-build",
      "grass-butterfly-resource",
      "grass-butterfly-layout-build",
      "grass-environment-resource",
      "grass-scan-resource",
      "grass-tufted-layout-build",
      "grass-wild-layout-build",
      "grass-white-layout-build",
      "grass-yellow-layout-build",
      "grass-rock-layout-build",
      ...grassRenderSliderTargets,
      ...grassRenderChangeTargets,
      ...grassCloverBlendTargets,
      ...grassCloverBlendChangeTargets,
      "timeline.currentTimeSeconds",
      "renderer.pointerDirection",
    ],
    kind: "handles",
    lifecycle: { cache: "none", resourceScope: "interaction" },
    output: "preview",
    quality: "full",
    runsOn: "gpu",
  },
  {
    cost: {
      dimensions: [
        "blade-count",
        "lawn-blade-count",
        "tufted-scan-count",
        "wild-scan-count",
        "white-flower-count",
        "yellow-flower-count",
        "rock-scan-count",
        "butterfly-count",
        "clover-mask-octaves",
      ],
      frequency: "batch",
      relationship: "linear",
    },
    id: "grass-export-frame",
    inputs: [
      "grass-ground-geometry-build",
      "grass-layout-build",
      "grass-lawn-layout-build",
      "grass-butterfly-resource",
      "grass-butterfly-layout-build",
      "grass-environment-resource",
      "grass-scan-resource",
      "grass-tufted-layout-build",
      "grass-wild-layout-build",
      "grass-white-layout-build",
      "grass-yellow-layout-build",
      "grass-rock-layout-build",
      "timeline.exportTimeSeconds",
      "export.outputSize",
      ...grassRenderSliderTargets.filter(
        (target) => target !== "canvas.renderScale",
      ),
      ...grassRenderChangeTargets,
      ...grassCloverBlendTargets,
      ...grassCloverBlendChangeTargets,
    ],
    invalidatedBy: [
      "grass-ground-geometry-build",
      "grass-layout-build",
      "grass-lawn-layout-build",
      "grass-butterfly-resource",
      "grass-butterfly-layout-build",
      "grass-environment-resource",
      "grass-scan-resource",
      "grass-tufted-layout-build",
      "grass-wild-layout-build",
      "grass-white-layout-build",
      "grass-yellow-layout-build",
      "grass-rock-layout-build",
      "timeline.exportTimeSeconds",
      "export.outputSize",
      ...grassRenderSliderTargets.filter(
        (target) => target !== "canvas.renderScale",
      ),
      ...grassRenderChangeTargets,
      ...grassCloverBlendTargets,
      ...grassCloverBlendChangeTargets,
    ],
    kind: "export",
    lifecycle: { cache: "none", resourceScope: "call" },
    output: "export",
    quality: "export",
    runsOn: "export-only",
  },
] as const satisfies readonly ToolcraftRenderPass[];

export type GrassRendererPassId =
  (typeof grassRendererPassDefinitions)[number]["id"];

export const grassRendererPassIds = Object.freeze(
  grassRendererPassDefinitions.map(({ id }) => id),
) as readonly GrassRendererPassId[];
