import { defineToolcraft } from "@/toolcraft/runtime";

import {
  DEFAULT_MESH_COLORS,
  DEFAULT_MESH_POINT_LAYOUT,
  MESH_MAX_COLUMNS,
  MESH_MAX_POINTS,
  MESH_MIN_POINTS,
} from "./mesh-gradient/mesh-model";
import {
  MESH_CUSTOM_PRESET_ID,
  MESH_PRESET_PICKER_ITEMS,
} from "./mesh-gradient/mesh-presets";

export const appSchema = defineToolcraft({
  canvas: {
    draggable: true,
    enabled: true,
    renderScale: true,
    size: { height: 600, unit: "px", width: 800 },
    sizing: { mode: "editable-output" },
    upload: false,
  },
  export: {
    png: { background: "transparent" },
  },
  panels: {
    controls: {
      sections: [
        {
          controls: {
            preset: {
              defaultValue: MESH_CUSTOM_PRESET_ID,
              items: MESH_PRESET_PICKER_ITEMS,
              keyframeable: false,
              label: "Choose",
              performanceReason: "Preset selection replaces the bounded mesh palette and topology in one interaction.",
              performanceRole: "responsiveness",
              target: "mesh.preset",
              type: "imagePicker",
            },
          },
          title: "Presets",
        },
        {
          controls: {
            colors: {
              addLabel: "Add color point",
              defaultValue: [...DEFAULT_MESH_COLORS],
              hardMaxItems: MESH_MAX_POINTS,
              itemDefaultValue: "#7C3AED",
              itemLabel: "Point",
              label: "Color points",
              minItems: MESH_MIN_POINTS,
              orderRole: "input",
              performanceReason: "Adding and removing points must update shader output and handles immediately.",
              performanceRole: "workload",
              recommendedMaxItems: 12,
              removeLabel: "Remove color point",
              target: "mesh.colors",
              type: "meshColorPoints",
            } as never,
          },
          title: "Color Points",
        },
        {
          controls: {
            editing: {
              defaultValue: true,
              description: "Shows mesh curves, points, and Bezier handles on the canvas.",
              label: "Edit mesh",
              performanceReason: "The canvas editing overlay must appear and disappear immediately.",
              performanceRole: "responsiveness",
              target: "mesh.editing",
              type: "switch",
            },
            columns: {
              defaultValue: 4,
              label: "Columns",
              max: MESH_MAX_COLUMNS,
              min: 2,
              performanceReason: "Column changes must redraw the topology guides immediately.",
              performanceRole: "responsiveness",
              sliderValueKind: "discrete",
              step: 1,
              target: "mesh.columns",
              type: "slider",
              unit: "cols",
              variant: "discrete",
            },
            pinEdges: {
              defaultValue: false,
              description: "Locks and hides every perimeter node, matching ColorFlow's fixed-edge editing mode.",
              label: "Fix edges",
              performanceReason: "Edge constraints change point placement and shader output during drag.",
              performanceRole: "responsiveness",
              target: "mesh.pinEdges",
              type: "switch",
            },
            guides: {
              defaultValue: true,
              label: "Grid guides",
              performanceReason: "Guide visibility must update the editing overlay immediately.",
              performanceRole: "responsiveness",
              target: "mesh.guides",
              type: "switch",
            },
            geometryActions: {
              actions: [
                { label: "Reflow", value: "mesh.reflow" },
                { label: "Shuffle", value: "mesh.shuffle" },
              ],
              defaultValue: DEFAULT_MESH_POINT_LAYOUT,
              label: "Geometry",
              performanceReason: "Geometry commands must update point state and visible output without blocking.",
              performanceRole: "responsiveness",
              target: "mesh.points",
              type: "actions",
            },
          },
          layoutGroups: [
            { columns: 2, controls: ["pinEdges", "guides"], layout: "inline" },
          ],
          title: "Topology",
        },
        {
          controls: {
            interpolation: {
              defaultValue: "oklab",
              description: "OKLab keeps perceived brightness more even between distant colors.",
              label: "Interpolation",
              options: [
                { label: "sRGB", value: "srgb" },
                { label: "Linear", value: "linear" },
                { label: "OKLab", value: "oklab" },
              ],
              performanceReason: "Interpolation mode switches shader color-space math live.",
              performanceRole: "responsiveness",
              target: "mix.interpolation",
              type: "segmented",
            },
            spread: {
              defaultValue: 90,
              label: "Color spread",
              max: 100,
              min: 10,
              performanceReason: "Spread must update color influence while the slider is dragged.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: "mix.spread",
              type: "slider",
              unit: "%",
            },
            warp: {
              defaultValue: 0,
              label: "Distortion",
              max: 100,
              min: 0,
              performanceReason: "Distortion changes fragment sampling on every live slider update.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: "mix.warp",
              type: "slider",
              unit: "%",
            },
            swirl: {
              defaultValue: 0,
              label: "Swirl",
              max: 100,
              min: -100,
              performanceReason: "Swirl changes the continuous mesh field during slider drag.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: "mix.swirl",
              type: "slider",
              unit: "%",
            },
            opacity: {
              defaultValue: 94,
              label: "Opacity",
              max: 100,
              min: 10,
              performanceReason: "Opacity changes preview compositing and export alpha live.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: "mix.opacity",
              type: "slider",
              unit: "%",
            },
            grain: {
              defaultValue: 0,
              label: "Grain",
              max: 12,
              min: 0,
              performanceReason: "Grain adds a fragment-stage finish that must remain responsive.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 0.5,
              target: "mix.grain",
              type: "slider",
              unit: "%",
            },
          },
          title: "Mixing",
        },
        {
          controls: {
            exposure: {
              defaultValue: 0,
              label: "Exposure",
              max: 2,
              min: -2,
              performanceReason: "Exposure applies in the live shader while dragging.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 0.05,
              target: "color.exposure",
              type: "slider",
            },
            contrast: {
              defaultValue: 100,
              label: "Contrast",
              max: 180,
              min: 20,
              performanceReason: "Contrast applies in the live shader while dragging.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: "color.contrast",
              type: "slider",
              unit: "%",
            },
            hue: {
              defaultValue: 0,
              label: "Hue",
              max: 180,
              min: -180,
              performanceReason: "Hue rotation updates every mixed color in real time.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: "color.hue",
              type: "slider",
              unit: "°",
            },
            saturation: {
              defaultValue: 100,
              label: "Saturation",
              max: 180,
              min: 0,
              performanceReason: "Saturation applies in the live shader while dragging.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: "color.saturation",
              type: "slider",
              unit: "%",
            },
            lightness: {
              defaultValue: 0,
              label: "Lightness",
              max: 50,
              min: -50,
              performanceReason: "Lightness applies in the live shader while dragging.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: "color.lightness",
              type: "slider",
              unit: "%",
            },
          },
          title: "Color Correction",
        },
        {
          controls: {
            positionDrift: {
              defaultValue: 14,
              label: "Point drift",
              max: 40,
              min: 0,
              performanceReason: "Point drift updates the animated shader every timeline frame.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: "motion.positionDrift",
              type: "slider",
              unit: "%",
            },
            colorDrift: {
              defaultValue: 12,
              label: "Color drift",
              max: 90,
              min: 0,
              performanceReason: "Color drift updates animated hue on every timeline frame.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: "motion.colorDrift",
              type: "slider",
              unit: "°",
            },
            scale: {
              defaultValue: 100,
              label: "Motion scale",
              max: 220,
              min: 40,
              performanceReason: "Motion scale changes procedural spatial frequency live.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: "motion.scale",
              type: "slider",
              unit: "%",
            },
            cycles: {
              defaultValue: 1,
              label: "Loop cycles",
              max: 4,
              min: 1,
              performanceReason: "Cycle count changes seamless timeline harmonics immediately.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: "motion.cycles",
              type: "slider",
            },
            randomness: {
              defaultValue: 42,
              label: "Randomness",
              max: 100,
              min: 0,
              performanceReason: "Randomness reseeds point phases without changing the loop seam.",
              performanceRole: "responsiveness",
              sliderValueKind: "continuous",
              step: 1,
              target: "motion.randomness",
              type: "slider",
              unit: "%",
            },
          },
          title: "Motion",
        },
        {
          controls: {
            includeBackground: {
              defaultValue: true,
              description: "Controls preview and image-export background; video always keeps it.",
              label: "Include",
              performanceReason: "Background inclusion must update preview compositing immediately.",
              performanceRole: "responsiveness",
              target: "export.includeBackground",
              type: "switch",
            },
            background: {
              defaultValue: "#09090B",
              label: false,
              performanceReason: "Background color changes preview and exported output.",
              performanceRole: "responsiveness",
              target: "appearance.background",
              type: "color",
            },
          },
          layoutGroups: [
            { columns: 2, controls: ["includeBackground", "background"], layout: "inline" },
          ],
          title: "Background",
        },
        {
          controls: {
            imageFormat: {
              defaultValue: "png",
              label: "Format",
              options: [
                { label: "PNG", value: "png" },
                { label: "JPG", value: "jpg" },
              ],
              performanceReason: "Image format selection must route the final export action correctly.",
              performanceRole: "responsiveness",
              target: "export.image.format",
              type: "select",
            },
            imageResolution: {
              defaultValue: "4k",
              label: "Resolution",
              options: [
                { label: "2K", value: "2k" },
                { label: "4K", value: "4k" },
                { label: "8K", value: "8k" },
              ],
              performanceReason: "Resolution selection controls actual image export dimensions.",
              performanceRole: "responsiveness",
              target: "export.image.resolution",
              type: "select",
            },
          },
          layoutGroups: [
            { columns: 2, controls: ["imageFormat", "imageResolution"], layout: "inline" },
          ],
          title: "Image Export",
        },
        {
          controls: {
            videoFormat: {
              defaultValue: "mp4",
              label: "Format",
              options: [
                { label: "MP4", value: "mp4" },
                { label: "WebM", value: "webm" },
              ],
              performanceReason: "Video format selection controls recorder capability negotiation.",
              performanceRole: "responsiveness",
              target: "export.video.format",
              type: "select",
            },
            videoResolution: {
              defaultValue: "current",
              label: "Resolution",
              options: [
                { label: "Current", value: "current" },
                { label: "4K", value: "4k" },
              ],
              performanceReason: "Video resolution selection controls encoder-safe output dimensions.",
              performanceRole: "responsiveness",
              target: "export.video.resolution",
              type: "select",
            },
          },
          layoutGroups: [
            { columns: 2, controls: ["videoFormat", "videoResolution"], layout: "inline" },
          ],
          title: "Video Export",
        },
        {
          actionGroup: "primary",
          controls: {
            exportActions: {
              actions: [
                {
                  icon: "upload-simple",
                  label: "Export PNG",
                  role: "export-image",
                  value: "export.png",
                },
                {
                  icon: "upload-simple",
                  label: "Export SVG",
                  role: "export-image",
                  value: "export.svg",
                },
                {
                  icon: "upload-simple",
                  label: "Export Video",
                  role: "export-video",
                  value: "export.video",
                },
              ],
              label: false,
              target: "export.actions",
              type: "panelActions",
            },
          },
        },
      ],
      title: "Mesh Gradient",
    },
    timeline: { defaultDurationSeconds: 6, enabled: true, mode: "playback" },
  },
  persistence: {
    include: ["values", "canvas", "panels", "timeline"],
    key: "toolcraft:mesh-gradient:state:v4",
    storage: "localStorage",
    version: 4,
  },
  settingsTransfer: { appId: "mesh-gradient", enabled: "auto", fileName: "mesh-gradient-settings" },
  toolbar: {
    history: true,
    radar: true,
    theme: true,
    zoom: true,
  },
});
