import {
  defineToolcraftPerformance,
  type ToolcraftPerformanceConfig,
} from "@/toolcraft/runtime";

import { editorialPatternDefaultValues } from "./editorial-pattern-defaults";

const automatedTestName = "maps product controls to the custom poster renderer";

function controlChangeScenario({
  browserTestName,
  controlLabel,
  id,
  target,
}: {
  browserTestName: string;
  controlLabel: string;
  id: string;
  target: string;
}) {
  return {
    automated: true,
    automatedTestName,
    browser: true,
    browserTestName,
    budget: { maxFrameGapMs: 90, maxInteractionMs: 500 },
    controlLabel,
    expectedObservable: `${controlLabel} updates the poster without freezing the editor.`,
    fixture: "Default 1440×1080 poster",
    id,
    interaction: "control-change" as const,
    target,
    values: { default: "default", max: "alternate", min: "default" },
    workload: false,
  };
}

function sliderScenario({
  browserTestName,
  controlLabel,
  defaultValue,
  id,
  max,
  min,
  stressValue,
  target,
  workload,
}: {
  browserTestName: string;
  controlLabel: string;
  defaultValue: number;
  id: string;
  max: number;
  min: number;
  stressValue?: number;
  target: string;
  workload: boolean;
}) {
  const resolvedStressValue = stressValue ?? max;
  const stressMetric: "numeric-max" | "numeric-min" =
    resolvedStressValue === min ? "numeric-min" : "numeric-max";
  const workloadBaseline =
    target === "pattern.detail"
      ? { segmentSize: 0.35 }
      : target === "pattern.segmentSize"
        ? { detail: 10000 }
        : { detail: 10000, segmentSize: 0.35 };

  return {
    automated: true,
    automatedTestName,
    browser: true,
    browserTestName,
    budget: { maxFrameGapMs: 90, maxInteractionMs: 600, maxLongTaskMs: 180 },
    controlLabel,
    expectedObservable: `${controlLabel} changes live product output during pointer drag.`,
    fixture: "Default poster with visible bottom pattern",
    id,
    interaction: "control-drag" as const,
    stressFixture: workload
      ? {
          kind: (target === "pattern.segmentSize" ? "high-density" : "max-value") as
            | "high-density"
            | "max-value",
          loadProfile: {
            hardLimit: resolvedStressValue,
            metric: stressMetric,
            smoothTarget: resolvedStressValue,
            smoothTargetRatio: 1,
            target,
            userFacingRange: "fully-guaranteed" as const,
          },
          reason:
            target === "pattern.segmentSize"
              ? "The minimum segment size creates the largest useful SVG path count."
              : `The maximum ${controlLabel.toLowerCase()} is the heaviest useful exposed value.`,
          value: resolvedStressValue,
        }
      : undefined,
    workloadFixture: workload
      ? {
          kind: "custom" as const,
          loadProfile: {
            hardLimit: workloadBaseline,
            metric: "custom" as const,
            smoothTarget: workloadBaseline,
            smoothTargetRatio: 1,
            target: "poster.maximum-baseline",
            userFacingRange: "fully-guaranteed" as const,
          },
          reason: "Independent maximum pattern settings establish the heavy app baseline before the measured slider drag.",
          value: workloadBaseline,
        }
      : undefined,
    target,
    values: { default: defaultValue, max, min },
    workload,
  };
}

export const appPerformance: ToolcraftPerformanceConfig = defineToolcraftPerformance({
  browserCheckPolicy: {
    fallbackRunner: "playwright",
    fallbackWhen: ["agent-browser-unavailable", "ci"],
    preferredRunner: "agent-browser",
  },
  rendererPipeline: {
    interactionInvalidation: [
      {
        interaction: "control-change",
        invalidates: [
          "equation-sample",
          "morph-resample",
          "morph-interpolate",
          "color-segmentation",
          "text-layout",
          "preview-composite",
        ],
        targets: ["composition.shuffle"],
      },
      {
        interaction: "control-change",
        invalidates: ["text-layout", "preview-composite"],
        mustNotInvalidate: [
          "appearance-interpolate",
          "color-segmentation",
          "equation-sample",
          "morph-resample",
          "morph-interpolate",
        ],
        targets: [
          "editorial.customCopy",
          "editorial.eyebrow",
          "editorial.headline",
          "editorial.body",
          "editorial.footer",
        ],
      },
      {
        interaction: "control-change",
        invalidates: [
          "morph-resample",
          "morph-interpolate",
          "appearance-interpolate",
          "color-segmentation",
          "text-layout",
          "preview-composite",
        ],
        mustNotInvalidate: ["equation-sample"],
        targets: ["editorial.template"],
      },
      {
        interaction: "control-change",
        invalidates: [
          "morph-resample",
          "morph-interpolate",
          "appearance-interpolate",
          "color-segmentation",
          "preview-composite",
        ],
        mustNotInvalidate: ["equation-sample", "text-layout"],
        targets: [
          "pattern.position",
          "pattern.colorA",
          "pattern.colorB",
          "pattern.colorC",
          "pattern.paletteActions",
          "appearance.headline",
          "appearance.detail",
          "appearance.rule",
          "appearance.background",
        ],
      },
      {
        interaction: "control-change",
        invalidates: ["preview-composite"],
        mustNotInvalidate: [
          "appearance-interpolate",
          "color-segmentation",
          "equation-sample",
          "morph-resample",
          "morph-interpolate",
          "text-layout",
        ],
        targets: [
          "export.includeBackground",
          "export.image.format",
          "export.image.resolution",
        ],
      },
      {
        interaction: "control-change",
        invalidates: [
          "equation-sample",
          "morph-resample",
          "morph-interpolate",
          "appearance-interpolate",
          "color-segmentation",
          "preview-composite",
        ],
        mustNotInvalidate: ["text-layout"],
        targets: ["pattern.preset"],
      },
      {
        interaction: "control-drag",
        invalidates: [
          "equation-sample",
          "morph-resample",
          "morph-interpolate",
          "appearance-interpolate",
          "color-segmentation",
          "preview-composite",
        ],
        mustNotInvalidate: ["text-layout"],
        targets: [
          "pattern.symmetry",
          "pattern.resonance",
          "pattern.coupling",
          "pattern.phase",
          "pattern.warp",
        ],
      },
      {
        interaction: "control-drag",
        invalidates: [
          "equation-sample",
          "morph-resample",
          "morph-interpolate",
          "appearance-interpolate",
          "color-segmentation",
          "preview-composite",
        ],
        mustNotInvalidate: ["text-layout"],
        targets: ["pattern.detail"],
      },
      {
        interaction: "animation-frame",
        invalidates: [
          "morph-interpolate",
          "appearance-interpolate",
          "color-segmentation",
          "preview-composite",
        ],
        mustNotInvalidate: ["equation-sample", "morph-resample", "text-layout"],
        targets: ["pattern.morph"],
      },
      {
        interaction: "control-drag",
        invalidates: [
          "morph-resample",
          "morph-interpolate",
          "appearance-interpolate",
          "color-segmentation",
          "preview-composite",
        ],
        mustNotInvalidate: ["equation-sample", "text-layout"],
        targets: [
          "pattern.segmentSize",
          "pattern.segmentRandomness",
          "pattern.colorSpread",
        ],
      },
      {
        interaction: "control-drag",
        invalidates: [
          "morph-resample",
          "morph-interpolate",
          "appearance-interpolate",
          "color-segmentation",
          "preview-composite",
        ],
        mustNotInvalidate: ["equation-sample", "text-layout"],
        targets: ["pattern.scale", "pattern.stroke"],
      },
      {
        interaction: "viewport-drag",
        invalidates: ["preview-composite"],
        mustNotInvalidate: ["equation-sample", "color-segmentation", "text-layout"],
        targets: ["canvas.viewport.offset"],
      },
      {
        interaction: "viewport-zoom",
        invalidates: ["preview-composite"],
        mustNotInvalidate: ["equation-sample", "color-segmentation", "text-layout"],
        targets: ["canvas.viewport.zoom"],
      },
      {
        interaction: "export",
        invalidates: ["export-rasterize"],
        mustNotInvalidate: ["equation-sample", "color-segmentation", "text-layout"],
        targets: ["panel.actions", "export.image.format", "export.image.resolution"],
      },
    ],
    passes: [
      {
        cacheKey: [
          "pattern.preset",
          "pattern.symmetry",
          "pattern.resonance",
          "pattern.coupling",
          "pattern.phase",
          "pattern.warp",
          "pattern.detail",
        ],
        id: "equation-sample",
        inputs: ["pattern.equation", "pattern.variables", "pattern.detail"],
        invalidatedBy: [
          "pattern.preset",
          "pattern.symmetry",
          "pattern.resonance",
          "pattern.coupling",
          "pattern.phase",
          "pattern.warp",
          "pattern.detail",
        ],
        kind: "vector-build",
        output: "intermediate",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: ["displayed-pattern", "equation-sample", "pattern.morph-key"],
        id: "morph-resample",
        inputs: ["displayed-pattern", "equation-sample", "pattern.morph-key"],
        invalidatedBy: ["pattern.morph-key"],
        kind: "vector-build",
        output: "intermediate",
        quality: "preview",
        runsOn: "main",
      },
      {
        cacheKey: ["morph-resample", "pattern.morph-progress"],
        id: "morph-interpolate",
        inputs: ["morph-resample", "pattern.morph-progress"],
        invalidatedBy: ["pattern.morph-progress"],
        kind: "vector-build",
        output: "intermediate",
        quality: "preview",
        runsOn: "main",
      },
      {
        cacheKey: ["pattern.appearance-target", "pattern.morph-progress"],
        id: "appearance-interpolate",
        inputs: ["pattern.appearance-target", "pattern.morph-progress"],
        invalidatedBy: ["pattern.appearance-target", "pattern.morph-progress"],
        kind: "vector-build",
        output: "intermediate",
        quality: "preview",
        runsOn: "main",
      },
      {
        cacheKey: [
          "morph-interpolate",
          "appearance-interpolate",
          "pattern.segmentSize",
          "pattern.segmentRandomness",
          "pattern.colorSpread",
        ],
        id: "color-segmentation",
        inputs: ["morph-interpolate", "appearance-interpolate", "pattern.segmentation"],
        invalidatedBy: [
          "morph-interpolate",
          "appearance-interpolate",
          "pattern.segmentSize",
          "pattern.segmentRandomness",
          "pattern.colorSpread",
        ],
        kind: "vector-build",
        output: "intermediate",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: [
          "editorial.template",
          "editorial.customCopy",
          "editorial.copy",
          "canvas.size.width",
          "canvas.size.height",
        ],
        id: "text-layout",
        inputs: ["editorial.template", "editorial.copyMode", "editorial.copy", "canvas.size"],
        invalidatedBy: ["editorial.copy", "editorial.customCopy", "editorial.template", "canvas.size"],
        kind: "text-layout",
        output: "intermediate",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: ["runtime.values", "canvas.size"],
        id: "preview-composite",
        inputs: ["color-segmentation", "text-layout", "appearance-interpolate"],
        invalidatedBy: ["runtime.values", "canvas.size"],
        kind: "composite",
        output: "preview",
        quality: "full",
        runsOn: "main",
      },
      {
        id: "export-rasterize",
        inputs: ["runtime.values", "canvas.size", "export.image.resolution"],
        invalidatedBy: ["panel.actions.export-png"],
        kind: "export",
        output: "export",
        quality: "export",
        runsOn: "export-only",
      },
    ],
  },
  rendererStrategy: "svg",
  rendererTechnique: {
    exportRenderer: "canvas-2d",
    fidelityRisks: [
      "Browser SVG and Canvas 2D font metrics can differ slightly at line endings.",
    ],
    layers: [
      {
        content: ["geometry"],
        exportMode: "included",
        id: "backgroundLayer",
        kind: "background",
        primitiveCount: "low",
        renderer: "svg",
        uiSelector: '[data-testid="poster-background"]',
      },
      {
        content: ["dense-pattern", "geometry", "text"],
        exportMode: "included",
        id: "productForegroundLayer",
        kind: "product-foreground",
        primitiveCount: "high",
        renderer: "svg",
        uiSelector: '[data-testid="editorial-pattern-output"]',
      },
      {
        content: ["composite"],
        exportMode: "composited",
        id: "exportComposite",
        intentionalRasterizationReason:
          "The standard image export contract composites the vector/text scene into selected 2K, 4K, or 8K image bytes.",
        kind: "export-composite",
        primitiveCount: "high",
        renderer: "canvas-2d",
      },
    ],
    performanceRisks: [
      "Maximum detail rebuilds ten thousand SVG path points.",
      "Minimum segment size partitions the line into roughly three hundred SVG paths.",
      "Eight-kilopixel image export performs an export-only Canvas rasterization.",
      "The densest editorial template composes twenty-five text elements plus visible grid rules.",
      "Equation and parameter changes interpolate up to 1,200 aligned points and rebuild short colored segments once per animation frame for 480ms.",
    ],
    previewExportDifferenceReason:
      "Preview stays vector-native in SVG while image delivery uses the standard Canvas export helper.",
    previewRenderer: "svg",
    productRepresentation: "mixed",
    rendererStrategy: "svg",
    rendererWorkload: "vector-output",
    sourceRepresentation: "procedural-data",
    whyNotAlternativeStrategies: [
      "DOM cannot express the dense continuous pattern as one scalable geometry tree.",
      "Canvas 2D preview would rasterize linework and type that remain crisp in SVG.",
      "WebGL and WebGPU add pipeline complexity without benefit for a bounded static vector path.",
    ],
  },
  rendererWorkload: "vector-output",
  scenarios: [
    {
      ...controlChangeScenario({ browserTestName: "browser perf: whole composition shuffle stays responsive", controlLabel: "Composition", id: "composition-shuffle-change", target: "composition.shuffle" }),
      budget: { maxFrameGapMs: 110, maxInteractionMs: 500 },
    },
    controlChangeScenario({ browserTestName: "browser perf: preserve colors toggle stays responsive", controlLabel: "Preserve colors", id: "preserve-colors-change", target: "composition.preserveColors" }),
    {
      ...controlChangeScenario({ browserTestName: "browser perf: template changes stay responsive", controlLabel: "Template", id: "template-change", target: "editorial.template" }),
      stressFixture: {
        kind: "many-items",
        loadProfile: {
          hardLimit: "archive-spine",
          metric: "custom",
          smoothTarget: "archive-spine",
          smoothTargetRatio: 1,
          target: "editorial.template",
          userFacingRange: "fully-guaranteed",
        },
        minCount: 25,
        reason: "Archive Spine is the densest template with twenty-five text elements and visible construction guides.",
        value: "archive-spine",
      },
      workloadFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { detail: 10000, segmentSize: 0.35 },
          metric: "custom",
          smoothTarget: { detail: 10000, segmentSize: 0.35 },
          smoothTargetRatio: 1,
          target: "poster.maximum-baseline",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Maximum pattern detail and minimum segment size establish the independent heavy geometry baseline before selecting the densest editorial template.",
        value: { detail: 10000, segmentSize: 0.35 },
      },
      values: {
        default: editorialPatternDefaultValues["editorial.template"],
        max: "archive-spine",
        min: "negative-space",
      },
      workload: true,
    },
    controlChangeScenario({ browserTestName: "browser perf: custom copy mode stays responsive", controlLabel: "Custom copy", id: "custom-copy-change", target: "editorial.customCopy" }),
    controlChangeScenario({ browserTestName: "browser perf: eyebrow edits stay responsive", controlLabel: "Eyebrow", id: "eyebrow-change", target: "editorial.eyebrow" }),
    controlChangeScenario({ browserTestName: "browser perf: headline edits stay responsive", controlLabel: "Headline", id: "headline-change", target: "editorial.headline" }),
    controlChangeScenario({ browserTestName: "browser perf: body edits stay responsive", controlLabel: "Body", id: "body-change", target: "editorial.body" }),
    controlChangeScenario({ browserTestName: "browser perf: footer edits stay responsive", controlLabel: "Footer", id: "footer-change", target: "editorial.footer" }),
    controlChangeScenario({ browserTestName: "browser perf: equation changes stay responsive", controlLabel: "Equation", id: "preset-change", target: "pattern.preset" }),
    {
      automated: true,
      automatedTestName,
      browser: true,
      browserTestName: "browser perf: equation morph frames stay smooth",
      budget: { maxFrameGapMs: 90, maxLongTaskMs: 180 },
      expectedObservable: "The bounded curve morph advances and settles without frame stalls.",
      fixture: "Maximum-detail poster with minimum segment size before Shuffle all",
      id: "pattern-morph-frames",
      interaction: "animation-frame",
      stress: true,
      stressFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { detail: 10000, segmentSize: 0.35 },
          metric: "custom",
          smoothTarget: { detail: 10000, segmentSize: 0.35 },
          smoothTargetRatio: 1,
          target: "pattern.morph",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Maximum final detail and minimum segment size establish the heaviest authored morph surroundings while transient interpolation remains capped at 1,200 points.",
        value: { detail: 10000, segmentSize: 0.35 },
      },
      target: "pattern.morph",
      workload: false,
    },
    {
      automated: true,
      automatedTestName,
      browser: true,
      browserTestName: "browser perf: canvas drag stays responsive during equation morph",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 1200, maxLongTaskMs: 180 },
      expectedObservable: "The canvas viewport follows pointer drag while the curve morph remains coalesced to animation frames.",
      fixture: "Maximum-detail poster morphing during a physical viewport drag",
      id: "pattern-morph-viewport-drag",
      interaction: "animation-viewport-drag",
      stress: true,
      stressFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { detail: 10000, segmentSize: 0.35 },
          metric: "custom",
          smoothTarget: { detail: 10000, segmentSize: 0.35 },
          smoothTargetRatio: 1,
          target: "pattern.morph-viewport",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Viewport drag is measured while the heaviest bounded morph environment is active.",
        value: { detail: 10000, segmentSize: 0.35 },
      },
      target: "pattern.morph",
      workload: false,
    },
    sliderScenario({ browserTestName: "browser perf: symmetry drag stays live", controlLabel: "Symmetry", defaultValue: editorialPatternDefaultValues["pattern.symmetry"], id: "symmetry-drag", max: 16, min: 2, target: "pattern.symmetry", workload: false }),
    sliderScenario({ browserTestName: "browser perf: resonance drag stays live", controlLabel: "Resonance", defaultValue: editorialPatternDefaultValues["pattern.resonance"], id: "resonance-drag", max: 16, min: 1, target: "pattern.resonance", workload: false }),
    sliderScenario({ browserTestName: "browser perf: coupling drag stays live", controlLabel: "Coupling", defaultValue: editorialPatternDefaultValues["pattern.coupling"], id: "coupling-drag", max: 100, min: 0, target: "pattern.coupling", workload: false }),
    sliderScenario({ browserTestName: "browser perf: phase drag stays live", controlLabel: "Phase", defaultValue: editorialPatternDefaultValues["pattern.phase"], id: "phase-drag", max: 180, min: -180, target: "pattern.phase", workload: false }),
    sliderScenario({ browserTestName: "browser perf: warp drag stays live", controlLabel: "Warp", defaultValue: editorialPatternDefaultValues["pattern.warp"], id: "warp-drag", max: 100, min: 0, target: "pattern.warp", workload: false }),
    controlChangeScenario({ browserTestName: "browser perf: position fields stay responsive", controlLabel: "Position", id: "position-change", target: "pattern.position" }),
    sliderScenario({ browserTestName: "browser perf: scale drag stays live", controlLabel: "Scale", defaultValue: editorialPatternDefaultValues["pattern.scale"], id: "scale-drag", max: 135, min: 45, target: "pattern.scale", workload: true }),
    sliderScenario({ browserTestName: "browser perf: detail drag stays live", controlLabel: "Detail", defaultValue: editorialPatternDefaultValues["pattern.detail"], id: "detail-drag", max: 10000, min: 2400, target: "pattern.detail", workload: true }),
    sliderScenario({ browserTestName: "browser perf: stroke drag stays live", controlLabel: "Stroke", defaultValue: editorialPatternDefaultValues["pattern.stroke"], id: "stroke-drag", max: 3, min: 0.5, target: "pattern.stroke", workload: false }),
    sliderScenario({ browserTestName: "browser perf: segment size drag stays live", controlLabel: "Segment size", defaultValue: editorialPatternDefaultValues["pattern.segmentSize"], id: "segment-size-drag", max: 2.5, min: 0.35, stressValue: 0.35, target: "pattern.segmentSize", workload: true }),
    sliderScenario({ browserTestName: "browser perf: segment randomness drag stays live", controlLabel: "Randomness", defaultValue: editorialPatternDefaultValues["pattern.segmentRandomness"], id: "segment-randomness-drag", max: 100, min: 0, target: "pattern.segmentRandomness", workload: false }),
    sliderScenario({ browserTestName: "browser perf: color spread drag stays live", controlLabel: "Color spread", defaultValue: editorialPatternDefaultValues["pattern.colorSpread"], id: "color-spread-drag", max: 100, min: 0, target: "pattern.colorSpread", workload: false }),
    controlChangeScenario({ browserTestName: "browser perf: first line color stays responsive", controlLabel: "Line Palette", id: "color-a-change", target: "pattern.colorA" }),
    controlChangeScenario({ browserTestName: "browser perf: second line color stays responsive", controlLabel: "Line Palette", id: "color-b-change", target: "pattern.colorB" }),
    controlChangeScenario({ browserTestName: "browser perf: third line color stays responsive", controlLabel: "Line Palette", id: "color-c-change", target: "pattern.colorC" }),
    controlChangeScenario({ browserTestName: "browser perf: palette shuffle stays responsive", controlLabel: "Harmony", id: "palette-shuffle-change", target: "pattern.paletteActions" }),
    controlChangeScenario({ browserTestName: "browser perf: headline ink stays responsive", controlLabel: "Headline", id: "headline-ink-change", target: "appearance.headline" }),
    controlChangeScenario({ browserTestName: "browser perf: detail ink stays responsive", controlLabel: "Detail", id: "detail-ink-change", target: "appearance.detail" }),
    controlChangeScenario({ browserTestName: "browser perf: rule ink stays responsive", controlLabel: "Rule", id: "rule-ink-change", target: "appearance.rule" }),
    controlChangeScenario({ browserTestName: "browser perf: background include stays responsive", controlLabel: "Include", id: "background-include-change", target: "export.includeBackground" }),
    controlChangeScenario({ browserTestName: "browser perf: background color stays responsive", controlLabel: "Background", id: "background-color-change", target: "appearance.background" }),
    controlChangeScenario({ browserTestName: "browser perf: image format stays responsive", controlLabel: "Format", id: "image-format-change", target: "export.image.format" }),
    {
      ...controlChangeScenario({ browserTestName: "browser perf: image resolution selection stays responsive", controlLabel: "Resolution", id: "image-resolution-change", target: "export.image.resolution" }),
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: "8k",
          metric: "custom",
          smoothTarget: "8k",
          smoothTargetRatio: 1,
          target: "export.image.resolution",
          userFacingRange: "fully-guaranteed",
        },
        reason: "8K is the largest exposed export resolution.",
        value: "8k",
      },
      workloadFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { detail: 10000, segmentSize: 0.35 },
          metric: "custom",
          smoothTarget: { detail: 10000, segmentSize: 0.35 },
          smoothTargetRatio: 1,
          target: "poster.maximum-baseline",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Maximum pattern geometry is the independent baseline for export resolution selection.",
        value: { detail: 10000, segmentSize: 0.35 },
      },
      values: { default: "4k", max: "8k", min: "2k" },
      workload: true,
    },
    {
      automated: true,
      automatedTestName,
      browser: true,
      browserTestName: "browser perf: maximum-detail preview renders within budget",
      budget: { maxLongTaskMs: 200, maxPreviewMs: 1200 },
      expectedObservable: "The maximum-detail SVG poster becomes visible without a long freeze.",
      fixture: "Maximum detail and minimum segment size",
      id: "preview-render",
      interaction: "preview-render",
      stress: true,
      stressFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { detail: 10000, segmentSize: 0.35, scale: 135 },
          metric: "custom",
          smoothTarget: { detail: 10000, segmentSize: 0.35, scale: 135 },
          smoothTargetRatio: 1,
          target: "poster.maximum",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Combined maximum geometry is the heaviest useful preview state.",
        value: { detail: 10000, segmentSize: 0.35, scale: 135 },
      },
      workload: false,
    },
    {
      automated: true,
      automatedTestName,
      browser: true,
      browserTestName: "browser perf: maximum-detail viewport zoom stays stable",
      budget: { maxFrameGapMs: 100, maxInteractionMs: 1600, maxLongTaskMs: 180 },
      expectedObservable: "Toolbar zoom keeps the maximum-detail poster visible and stable.",
      fixture: "Maximum detail and scale before toolbar zoom",
      id: "viewport-zoom-stress",
      interaction: "viewport-zoom-stress",
      stress: true,
      stressFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { detail: 10000, segmentSize: 0.35, scale: 135 },
          metric: "custom",
          smoothTarget: { detail: 10000, segmentSize: 0.35, scale: 135 },
          smoothTargetRatio: 1,
          target: "poster.maximum-zoom",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Zoom stress uses the combined maximum pattern state.",
        value: { detail: 10000, segmentSize: 0.35, scale: 135 },
      },
      workload: false,
    },
    {
      automated: true,
      automatedTestName,
      browser: true,
      browserTestName: "browser perf: poster viewport remains stable",
      budget: { maxFrameGapMs: 100 },
      expectedObservable: "Control changes do not jump canvas zoom or offset.",
      fixture: "Default poster and toolbar viewport",
      id: "viewport-stability",
      interaction: "viewport-stability",
      workload: false,
    },
    {
      automated: true,
      automatedTestName,
      browser: true,
      browserTestName: "browser perf: 8K poster export completes within budget",
      budget: { maxExportMs: 8000, maxLongTaskMs: 250 },
      expectedObservable: "Export downloads non-empty 8K image bytes.",
      fixture: "Maximum detail poster exported at 8K",
      id: "export-copy",
      interaction: "export-copy",
      stress: true,
      stressFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { detail: 10000, resolution: "8k", segmentSize: 0.35 },
          metric: "custom",
          smoothTarget: { detail: 10000, resolution: "8k", segmentSize: 0.35 },
          smoothTargetRatio: 1,
          target: "poster.maximum-export",
          userFacingRange: "fully-guaranteed",
        },
        reason: "8K export at maximum pattern detail is the heaviest delivery path.",
        value: { detail: 10000, resolution: "8k", segmentSize: 0.35 },
      },
      workload: false,
    },
  ],
  usesCustomRenderer: true,
  workloadTargets: [
    "editorial.template",
    "pattern.scale",
    "pattern.detail",
    "pattern.segmentSize",
    "export.image.resolution",
  ],
});
