import { defineToolcraft } from "@/toolcraft/runtime";

import { editorialPatternFirstLaunchDefaults } from "./editorial-pattern-defaults";
import { editorialTemplateOptions } from "./editorial-templates";
import { equationOptions } from "./pattern-equations";

const firstLaunchDefaults = editorialPatternFirstLaunchDefaults.values;

export const appSchema = defineToolcraft({
  canvas: {
    enabled: true,
    size: {
      height: editorialPatternFirstLaunchDefaults.canvas.height,
      unit: editorialPatternFirstLaunchDefaults.canvas.unit,
      width: editorialPatternFirstLaunchDefaults.canvas.width,
    },
    sizing: {
      mode: "editable-output",
    },
    upload: false,
  },
  panels: {
    controls: {
      sections: [
        {
          controls: {
            preserveColors: {
              defaultValue: firstLaunchDefaults["composition.preserveColors"],
              description: "Keeps the current background, line palette, text and rule inks, and Background Include setting when Shuffle all runs.",
              keyframeable: false,
              label: "Preserve colors",
              orderRole: "mode",
              performanceReason: "The toggle changes which bounded runtime targets the next Shuffle all action updates.",
              performanceRole: "responsiveness",
              target: "composition.preserveColors",
              type: "switch",
            },
            shuffleComposition: {
              actions: [
                {
                  icon: "shuffle",
                  label: "Shuffle all",
                  value: "shuffle-composition",
                },
              ],
              description: "Builds a new poster from a different layout, equation, and variables, with either preserved colors or a new saturated contrast-safe color system.",
              label: "Composition",
              orderRole: "action",
              performanceReason: "One action updates a bounded set of poster values and starts one coalesced geometry morph.",
              performanceRole: "responsiveness",
              target: "composition.shuffle",
              type: "actions",
            },
          },
          layout: "standalone",
          title: "Explore",
        },
        {
          controls: {
            template: {
              defaultValue: firstLaunchDefaults["editorial.template"],
              description: "Chooses one of thirty reference-derived grid, type, copy, and pattern compositions.",
              keyframeable: false,
              label: "Template",
              options: editorialTemplateOptions,
              orderRole: "mode",
              performanceReason: "Template selection changes the text-element and construction-rule count from sparse to dense scenes.",
              performanceRole: "workload",
              target: "editorial.template",
              type: "select",
            },
            customCopy: {
              defaultValue: firstLaunchDefaults["editorial.customCopy"],
              description: "Replaces the selected template's authored text with your editable copy.",
              keyframeable: false,
              label: "Custom copy",
              orderRole: "mode",
              performanceReason: "Copy mode swaps four bounded SVG text sources without changing geometry workload.",
              performanceRole: "responsiveness",
              target: "editorial.customCopy",
              type: "switch",
            },
            eyebrow: {
              commitMode: "content",
              defaultValue: firstLaunchDefaults["editorial.eyebrow"],
              keyframeable: false,
              label: "Eyebrow",
              orderRole: "detail",
              performanceReason: "Short copy updates one SVG text role.",
              performanceRole: "responsiveness",
              target: "editorial.eyebrow",
              type: "text",
              visibleWhen: {
                equals: true,
                target: "editorial.customCopy",
              },
            },
            headline: {
              defaultValue: firstLaunchDefaults["editorial.headline"],
              description: "Supports line breaks for editorial display copy.",
              keyframeable: false,
              label: "Headline",
              orderRole: "detail",
              performanceReason: "Headline edits reflow a small fixed number of SVG lines.",
              performanceRole: "responsiveness",
              target: "editorial.headline",
              type: "code",
              visibleWhen: {
                equals: true,
                target: "editorial.customCopy",
              },
            },
            body: {
              defaultValue: firstLaunchDefaults["editorial.body"],
              description: "Multiline supporting copy for the compact editorial column.",
              keyframeable: false,
              label: "Body",
              orderRole: "detail",
              performanceReason: "Body edits reflow a bounded compact text block.",
              performanceRole: "responsiveness",
              target: "editorial.body",
              type: "code",
              visibleWhen: {
                equals: true,
                target: "editorial.customCopy",
              },
            },
            footer: {
              commitMode: "content",
              defaultValue: firstLaunchDefaults["editorial.footer"],
              keyframeable: false,
              label: "Footer",
              orderRole: "detail",
              performanceReason: "Short footer copy updates one SVG text line.",
              performanceRole: "responsiveness",
              target: "editorial.footer",
              type: "text",
              visibleWhen: {
                equals: true,
                target: "editorial.customCopy",
              },
            },
          },
          layout: "standalone",
          title: "Editorial Template",
        },
        {
          controls: {
            preset: {
              defaultValue: firstLaunchDefaults["pattern.preset"],
              description: "Chooses one of twelve closed physical and mathematical systems.",
              keyframeable: false,
              label: "Equation",
              options: equationOptions,
              orderRole: "mode",
              performanceReason: "Each equation uses the same bounded sample count and rebuilds once.",
              performanceRole: "responsiveness",
              target: "pattern.preset",
              type: "select",
            },
            symmetry: {
              defaultValue: firstLaunchDefaults["pattern.symmetry"],
              description: "Changes the primary lobe and rotational topology count.",
              keyframeable: false,
              label: "Symmetry",
              max: 16,
              min: 2,
              orderRole: "strength",
              performanceReason: "Symmetry changes equation topology at the same bounded sample count.",
              performanceRole: "responsiveness",
              step: 1,
              target: "pattern.symmetry",
              type: "slider",
              variant: "discrete",
            },
            resonance: {
              defaultValue: firstLaunchDefaults["pattern.resonance"],
              description: "Changes the integer difference between coupled modes and crossings.",
              keyframeable: false,
              label: "Resonance",
              max: 16,
              min: 1,
              orderRole: "strength",
              performanceReason: "Resonance changes equation topology at the same bounded sample count.",
              performanceRole: "responsiveness",
              step: 1,
              target: "pattern.resonance",
              type: "slider",
              variant: "discrete",
            },
            coupling: {
              defaultValue: firstLaunchDefaults["pattern.coupling"],
              description: "Controls the energy transferred into the secondary mode.",
              keyframeable: false,
              label: "Coupling",
              max: 100,
              min: 0,
              orderRole: "strength",
              performanceReason: "Coupling changes point positions without changing sample count.",
              performanceRole: "responsiveness",
              step: 1,
              target: "pattern.coupling",
              type: "slider",
              unit: "%",
            },
            phase: {
              defaultValue: firstLaunchDefaults["pattern.phase"],
              description: "Offsets the alignment between primary and resonant modes.",
              keyframeable: false,
              label: "Phase",
              max: 180,
              min: -180,
              orderRole: "strength",
              performanceReason: "Phase changes point positions without changing sample count.",
              performanceRole: "responsiveness",
              step: 1,
              target: "pattern.phase",
              type: "slider",
              unit: "°",
            },
            warp: {
              defaultValue: firstLaunchDefaults["pattern.warp"],
              description: "Adds nonlinear radial and phase deformation to every equation.",
              keyframeable: false,
              label: "Warp",
              max: 100,
              min: 0,
              orderRole: "strength",
              performanceReason: "Warp changes point positions without changing sample count.",
              performanceRole: "responsiveness",
              step: 1,
              target: "pattern.warp",
              type: "slider",
              unit: "%",
            },
          },
          layout: "standalone",
          title: "Field Equation",
        },
        {
          controls: {
            position: {
              defaultValue: firstLaunchDefaults["pattern.position"],
              description: "Moves the pattern horizontally and vertically; positive Y moves down.",
              keyframeable: false,
              label: "Position",
              orderRole: "spatial",
              performanceReason: "Position updates only the SVG group transform.",
              performanceRole: "responsiveness",
              target: "pattern.position",
              type: "vector",
              xLabel: "X",
              yLabel: "Y",
            },
            scale: {
              defaultValue: firstLaunchDefaults["pattern.scale"],
              keyframeable: false,
              label: "Scale",
              max: 135,
              min: 45,
              orderRole: "strength",
              performanceReason: "Scale changes only the SVG and Canvas composite transform.",
              performanceRole: "workload",
              step: 1,
              target: "pattern.scale",
              type: "slider",
              unit: "%",
            },
            detail: {
              defaultValue: firstLaunchDefaults["pattern.detail"],
              description: "Controls curve samples; higher values preserve tighter interference lines.",
              keyframeable: false,
              label: "Detail",
              max: 10000,
              min: 2400,
              orderRole: "detail",
              performanceReason: "Detail changes the number of generated parametric path points.",
              performanceRole: "workload",
              step: 200,
              target: "pattern.detail",
              type: "slider",
            },
            stroke: {
              defaultValue: firstLaunchDefaults["pattern.stroke"],
              keyframeable: false,
              label: "Stroke",
              max: 3,
              min: 0.5,
              orderRole: "detail",
              performanceReason: "Stroke changes presentation without rebuilding geometry.",
              performanceRole: "responsiveness",
              step: 0.05,
              target: "pattern.stroke",
              type: "slider",
              unit: "px",
            },
          },
          layout: "standalone",
          title: "Line Form",
        },
        {
          controls: {
            segmentSize: {
              defaultValue: firstLaunchDefaults["pattern.segmentSize"],
              description: "Sets each colored stroke as a percentage of the continuous sampled line.",
              keyframeable: false,
              label: "Segment size",
              max: 2.5,
              min: 0.35,
              orderRole: "strength",
              performanceReason: "Smaller values create more SVG paths from the same sampled points.",
              performanceRole: "workload",
              step: 0.05,
              target: "pattern.segmentSize",
              type: "slider",
              unit: "%",
            },
            segmentRandomness: {
              defaultValue: firstLaunchDefaults["pattern.segmentRandomness"],
              description: "Jitters short-stroke lengths and color order through a stable seeded sequence.",
              keyframeable: false,
              label: "Randomness",
              max: 100,
              min: 0,
              orderRole: "strength",
              performanceReason: "Randomness repartitions existing sampled points without increasing detail.",
              performanceRole: "responsiveness",
              step: 1,
              target: "pattern.segmentRandomness",
              type: "slider",
              unit: "%",
            },
            colorSpread: {
              defaultValue: firstLaunchDefaults["pattern.colorSpread"],
              description: "Moves from longer color neighborhoods to rapidly interleaved palette strokes.",
              keyframeable: false,
              label: "Color spread",
              max: 100,
              min: 0,
              orderRole: "strength",
              performanceReason: "Color spread only reassigns three paint indices across existing segments.",
              performanceRole: "responsiveness",
              step: 1,
              target: "pattern.colorSpread",
              type: "slider",
              unit: "%",
            },
          },
          layout: "standalone",
          title: "Color Segments",
        },
        {
          controls: {
            colorA: {
              defaultValue: firstLaunchDefaults["pattern.colorA"],
              keyframeable: false,
              label: false,
              orderRole: "color",
              performanceReason: "Color changes only SVG stroke paint.",
              performanceRole: "responsiveness",
              target: "pattern.colorA",
              type: "color",
            },
            colorB: {
              defaultValue: firstLaunchDefaults["pattern.colorB"],
              keyframeable: false,
              label: false,
              orderRole: "color",
              performanceReason: "Color changes only SVG stroke paint.",
              performanceRole: "responsiveness",
              target: "pattern.colorB",
              type: "color",
            },
            colorC: {
              defaultValue: firstLaunchDefaults["pattern.colorC"],
              keyframeable: false,
              label: false,
              orderRole: "color",
              performanceReason: "Color changes only SVG stroke paint.",
              performanceRole: "responsiveness",
              target: "pattern.colorC",
              type: "color",
            },
            paletteActions: {
              actions: [
                {
                  icon: "shuffle",
                  label: "Shuffle",
                  value: "shuffle-palette",
                },
              ],
              label: "Harmony",
              orderRole: "action",
              performanceReason: "Shuffle updates three palette values and repaints existing segment strokes.",
              performanceRole: "responsiveness",
              target: "pattern.paletteActions",
              type: "actions",
            },
          },
          title: "Line Palette",
        },
        {
          controls: {
            headlineInk: {
              defaultValue: firstLaunchDefaults["appearance.headline"],
              keyframeable: false,
              label: "Headline",
              orderRole: "color",
              performanceReason: "Ink changes only SVG text paint.",
              performanceRole: "responsiveness",
              target: "appearance.headline",
              type: "color",
            },
            detailInk: {
              defaultValue: firstLaunchDefaults["appearance.detail"],
              keyframeable: false,
              label: "Detail",
              orderRole: "color",
              performanceReason: "Ink changes only compact SVG text paint.",
              performanceRole: "responsiveness",
              target: "appearance.detail",
              type: "color",
            },
            ruleInk: {
              defaultValue: firstLaunchDefaults["appearance.rule"],
              keyframeable: false,
              label: "Rule",
              orderRole: "color",
              performanceReason: "Rule color changes one SVG line paint.",
              performanceRole: "responsiveness",
              target: "appearance.rule",
              type: "color",
            },
          },
          title: "Editorial Ink",
        },
        {
          controls: {
            includeBackground: {
              defaultValue: firstLaunchDefaults["export.includeBackground"],
              description: "Hides the poster background in preview and makes PNG export transparent.",
              keyframeable: false,
              label: "Include",
              orderRole: "mode",
              performanceReason: "The toggle adds or removes one SVG background rectangle.",
              performanceRole: "responsiveness",
              target: "export.includeBackground",
              type: "switch",
            },
            background: {
              defaultValue: firstLaunchDefaults["appearance.background"],
              keyframeable: false,
              label: false,
              orderRole: "color",
              performanceReason: "Background color changes one SVG fill.",
              performanceRole: "responsiveness",
              target: "appearance.background",
              type: "color",
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["includeBackground", "background"],
              layout: "inline",
            },
          ],
          title: "Background",
        },
        {
          controls: {
            format: {
              defaultValue: firstLaunchDefaults["export.image.format"],
              keyframeable: false,
              label: "Format",
              options: [
                { label: "PNG", value: "png" },
                { label: "JPG", value: "jpg" },
              ],
              orderRole: "mode",
              performanceReason: "Format selection only changes export encoding.",
              performanceRole: "responsiveness",
              target: "export.image.format",
              type: "select",
            },
            resolution: {
              defaultValue: firstLaunchDefaults["export.image.resolution"],
              keyframeable: false,
              label: "Resolution",
              options: [
                { label: "2K", value: "2k" },
                { label: "4K", value: "4k" },
                { label: "8K", value: "8k" },
              ],
              orderRole: "detail",
              performanceReason: "Resolution changes export-only raster dimensions.",
              performanceRole: "workload",
              target: "export.image.resolution",
              type: "select",
            },
          },
          layoutGroups: [
            {
              columns: 2,
              controls: ["format", "resolution"],
              layout: "inline",
            },
          ],
          title: "Image Export",
        },
        {
          actionGroup: "primary",
          controls: {
            export: {
              actions: [
                {
                  icon: "upload-simple",
                  label: "Export PNG",
                  value: "export-png",
                },
              ],
              target: "panel.actions",
              type: "panelActions",
            },
          },
        },
      ],
      title: "Editorial Pattern Studio",
    },
  },
  persistence: {
    include: ["values", "canvas", "panels"],
    key: "toolcraft:editorial-pattern-studio:state:v3",
    storage: "localStorage",
    version: 3,
  },
  settingsTransfer: "auto",
  toolbar: {
    history: true,
    radar: true,
    theme: true,
    zoom: true,
  },
});
