import {
  defineToolcraftPerformance,
  type ToolcraftPerformanceConfig,
  type ToolcraftPerformanceScenario,
} from "@/toolcraft/runtime";

const renderScaleWorkload = {
  kind: "custom",
  reason:
    "The heaviest normal editor baseline keeps the WebGL preview at the default 2x backing scale before measuring an individual control.",
  value: { renderScale: 2 },
} as const;

const buttonImageWorkload = {
  kind: "custom",
  reason:
    "Button image position and scale are measured after loading a realistic glass-clipped image at the default 2x preview backing scale.",
  value: { buttonImageMedia: { height: 1080, width: 1920 }, renderScale: 2 },
} as const;

function workloadDragScenario({
  budget = { maxFrameGapMs: 120, maxInteractionMs: 1900 },
  defaultValue,
  id,
  label,
  max,
  min,
  observable,
  target,
  workloadFixture = renderScaleWorkload,
}: {
  budget?: ToolcraftPerformanceScenario["budget"];
  defaultValue: number;
  id: string;
  label: string;
  max: number;
  min: number;
  observable: string;
  target: string;
  workloadFixture?: ToolcraftPerformanceScenario["workloadFixture"];
}): ToolcraftPerformanceScenario {
  return {
    automated: true,
    automatedTestName: `perf: ${id} workload stays responsive`,
    browser: true,
    browserTestName: `browser perf: ${id} workload stays responsive`,
    budget,
    controlLabel: label,
    expectedObservable: observable,
    fixture: `${label} max workload at render scale 2`,
    id,
    interaction: "control-drag",
    stressFixture: {
      kind: "max-value",
      reason: `${label} max is the heaviest useful value exposed by the product control.`,
      value: max,
    },
    target,
    values: { default: defaultValue, max, min },
    workload: true,
    workloadFixture,
  };
}

function responsiveDragScenario({
  budget = { maxFrameGapMs: 120, maxInteractionMs: 1100 },
  id,
  label,
  observable,
  target,
}: {
  budget?: ToolcraftPerformanceScenario["budget"];
  id: string;
  label: string;
  observable: string;
  target: string;
}): ToolcraftPerformanceScenario {
  return {
    automated: true,
    automatedTestName: `perf: ${id} drag stays responsive`,
    browser: true,
    browserTestName: `browser perf: ${id} drag stays responsive`,
    budget,
    controlLabel: label,
    expectedObservable: observable,
    fixture: `${label} interactive drag`,
    id,
    interaction: "control-drag",
    target,
    workload: false,
  };
}

function responsiveChangeScenario({
  budget = { maxFrameGapMs: 120, maxInteractionMs: 1000 },
  id,
  label,
  observable,
  target,
}: {
  budget?: ToolcraftPerformanceScenario["budget"];
  id: string;
  label: string;
  observable: string;
  target: string;
}): ToolcraftPerformanceScenario {
  return {
    automated: true,
    automatedTestName: `perf: ${id} change stays responsive`,
    browser: true,
    browserTestName: `browser perf: ${id} change stays responsive`,
    budget,
    controlLabel: label,
    expectedObservable: observable,
    fixture: `${label} control change`,
    id,
    interaction: "control-change",
    target,
    workload: false,
  };
}

function workloadChangeScenario({
  budget = { maxFrameGapMs: 120, maxInteractionMs: 1200 },
  defaultValue,
  id,
  label,
  max,
  min,
  observable,
  target,
}: {
  budget?: ToolcraftPerformanceScenario["budget"];
  defaultValue: string;
  id: string;
  label: string;
  max: string;
  min: string;
  observable: string;
  target: string;
}): ToolcraftPerformanceScenario {
  return {
    automated: true,
    automatedTestName: `perf: ${id} workload change stays responsive`,
    browser: true,
    browserTestName: `browser perf: ${id} workload change stays responsive`,
    budget,
    controlLabel: label,
    expectedObservable: observable,
    fixture: `${label} workload option`,
    id,
    interaction: "control-change",
    stressFixture: {
      kind: "max-value",
      reason: `${label} option "${max}" exercises the heavier renderer path for this control.`,
      value: max,
    },
    target,
    values: { default: defaultValue, max, min },
    workload: true,
    workloadFixture: renderScaleWorkload,
  };
}

const workloadScenarios: readonly ToolcraftPerformanceScenario[] = [
  workloadChangeScenario({
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1200 },
    defaultValue: "16:9",
    id: "canvas-aspect-ratio",
    label: "Aspect ratio",
    max: "1:1",
    min: "16:9",
    observable: "Aspect ratio changes output dimensions without freezing the renderer.",
    target: "canvas.aspectRatio",
  }),
  workloadChangeScenario({
    defaultValue: "1920",
    id: "canvas-width",
    label: "Canvas width",
    max: "2200",
    min: "1280",
    observable: "Canvas width edits resize the WebGL output responsively.",
    target: "canvas.size.width",
  }),
  workloadChangeScenario({
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1200 },
    defaultValue: "1080",
    id: "canvas-height",
    label: "Canvas height",
    max: "1400",
    min: "720",
    observable: "Canvas height edits resize the WebGL output responsively.",
    target: "canvas.size.height",
  }),
  workloadDragScenario({
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1800 },
    defaultValue: 2,
    id: "canvas-render-scale",
    label: "Resolution scale",
    max: 2,
    min: 1,
    observable: "Resolution scale changes preview backing pixels without jank.",
    target: "canvas.renderScale",
  }),
  workloadChangeScenario({
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1200 },
    defaultValue: "off",
    id: "texture-mode",
    label: "Texture",
    max: "preset",
    min: "off",
    observable: "Texture mode changes overlay compositing without blocking preview.",
    target: "texture.mode",
  }),
  workloadChangeScenario({
    defaultValue: "grain",
    id: "texture-preset",
    label: "Pattern",
    max: "etched",
    min: "grain",
    observable: "Pattern changes redraw the glass-constrained texture frame responsively.",
    target: "texture.preset",
  }),
  {
    automated: true,
    automatedTestName: "perf: text-style workload change stays responsive",
    browser: true,
    browserTestName: "browser perf: text-style workload change stays responsive",
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1400 },
    controlLabel: "Style",
    expectedObservable:
      "FontPicker style changes redraw the cached glass text frame without reprocessing source pixels.",
    fixture: "large centered glass text style at render scale 2",
    id: "text-style",
    interaction: "control-change",
    stressFixture: {
      kind: "custom",
      reason:
        "Large font size plus uppercase text exercises text rasterization while preserving the current preview render scale.",
      value: { fontSize: 118, textCase: "uppercase" },
    },
    target: "text.style",
    values: {
      default: { fontSize: 64, textCase: "uppercase" },
      max: { fontSize: 118, textCase: "uppercase" },
      min: { fontSize: 8, textCase: "original" },
    },
    workload: true,
    workloadFixture: renderScaleWorkload,
  },
  workloadChangeScenario({
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1200 },
    defaultValue: "circle",
    id: "glass-shape",
    label: "Shape",
    max: "square",
    min: "circle",
    observable: "Shape changes regenerate the SDF map without panel jank.",
    target: "glass.shape",
  }),
  workloadDragScenario({
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1800 },
    defaultValue: 420,
    id: "glass-width",
    label: "Width",
    max: 960,
    min: 96,
    observable: "Width changes regenerate the lens map at the largest useful lens size.",
    target: "glass.width",
  }),
  workloadDragScenario({
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1800 },
    defaultValue: 260,
    id: "glass-height",
    label: "Height",
    max: 720,
    min: 96,
    observable: "Height changes regenerate the lens map at the largest useful lens size.",
    target: "glass.height",
  }),
  workloadDragScenario({
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1600 },
    defaultValue: 92,
    id: "glass-radius",
    label: "Radius",
    max: 360,
    min: 0,
    observable: "Radius changes the rounded SDF map under stress.",
    target: "glass.radius",
  }),
  workloadDragScenario({
    defaultValue: 0.72,
    id: "glass-depth",
    label: "Depth",
    max: 1,
    min: 0,
    observable: "Depth changes the SDF reach under stress.",
    target: "glass.depth",
  }),
  workloadDragScenario({
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1600 },
    defaultValue: 0.58,
    id: "glass-curvature",
    label: "Curvature",
    max: 1,
    min: 0,
    observable: "Curvature changes dome map generation under stress.",
    target: "glass.curvature",
  }),
  workloadDragScenario({
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1600 },
    defaultValue: 0.08,
    id: "glass-splay",
    label: "Splay",
    max: 1,
    min: 0,
    observable: "Splay changes corner displacement without freezing input.",
    target: "glass.splay",
  }),
  workloadDragScenario({
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1600 },
    defaultValue: 0.34,
    id: "glass-bend",
    label: "Bend",
    max: 1,
    min: 0,
    observable: "Bend changes the edge meniscus map under stress.",
    target: "glass.bend",
  }),
  workloadDragScenario({
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1300 },
    defaultValue: 0.16,
    id: "glass-bend-width",
    label: "Edge Width",
    max: 0.4,
    min: 0.04,
    observable: "Edge width changes the rim band map under stress.",
    target: "glass.bendWidth",
  }),
  workloadDragScenario({
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1500 },
    defaultValue: 3,
    id: "glass-frost",
    label: "Frost",
    max: 14,
    min: 0,
    observable: "Frost changes the blur prepass at the heaviest exposed radius.",
    target: "glass.frost",
  }),
  workloadDragScenario({
    defaultValue: 0.38,
    id: "glass-sheen",
    label: "Sheen",
    max: 2,
    min: 0,
    observable: "Sheen changes the B-channel specular map under stress.",
    target: "glass.sheen",
  }),
  workloadDragScenario({
    defaultValue: 3,
    id: "glass-sheen-width",
    label: "Thickness",
    max: 10,
    min: 1,
    observable: "Sheen thickness changes the highlight band under stress.",
    target: "glass.sheenWidth",
  }),
  workloadDragScenario({
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1600 },
    defaultValue: 45,
    id: "glass-sheen-angle",
    label: "Angle",
    max: 180,
    min: 0,
    observable: "Sheen angle changes directional highlight mapping responsively.",
    target: "glass.sheenAngle",
  }),
  workloadDragScenario({
    defaultValue: 0.16,
    id: "glass-glow",
    label: "Glow",
    max: 1,
    min: 0,
    observable: "Glow changes the specular channel under stress.",
    target: "glass.glow",
  }),
  workloadDragScenario({
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1600 },
    defaultValue: 1,
    id: "glass-glow-spread",
    label: "Spread",
    max: 2,
    min: 0.2,
    observable: "Glow spread changes inner glow reach under stress.",
    target: "glass.glowSpread",
  }),
  workloadDragScenario({
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1500 },
    defaultValue: 42,
    id: "shadow-blur",
    label: "Blur",
    max: 140,
    min: 0,
    observable: "Shadow blur expands shader softness and scissor padding responsively.",
    target: "shadow.blur",
  }),
  workloadChangeScenario({
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1200 },
    defaultValue: "4k",
    id: "image-resolution",
    label: "Resolution",
    max: "8k",
    min: "2k",
    observable: "Image resolution changes export size selection without panel lag.",
    target: "export.image.resolution",
  }),
];

const responsiveScenarios: readonly ToolcraftPerformanceScenario[] = [
  responsiveChangeScenario({
    id: "runtime-settings-transfer",
    label: "Export Settings",
    observable: "Settings transfer controls remain responsive in the complex editor.",
    target: "runtime.settingsTransfer",
  }),
  responsiveDragScenario({
    budget: { maxFrameGapMs: 120, maxInteractionMs: 900 },
    id: "source-saturation",
    label: "Saturation",
    observable: "Saturation adjusts source color without freezing slider drag.",
    target: "source.saturation",
  }),
  responsiveChangeScenario({
    id: "glass-center",
    label: "Center",
    observable: "Center vector edits move the lens without remaking heavy resources.",
    target: "glass.center",
  }),
  responsiveDragScenario({
    budget: { maxFrameGapMs: 120, maxInteractionMs: 900 },
    id: "glass-opacity",
    label: "Opacity",
    observable: "Opacity updates the shader blend uniform during drag.",
    target: "glass.opacity",
  }),
  responsiveChangeScenario({
    id: "shadow-enabled",
    label: "Include",
    observable: "Shadow include toggles a WebGL composite branch without remaking maps.",
    target: "shadow.enabled",
  }),
  responsiveChangeScenario({
    budget: { maxFrameGapMs: 120, maxInteractionMs: 850 },
    id: "shadow-offset",
    label: "Offset",
    observable: "Shadow offset moves the drop-shadow silhouette through uniforms.",
    target: "shadow.offset",
  }),
  responsiveChangeScenario({
    id: "shadow-color",
    label: "Color",
    observable: "Shadow color and opacity update shader uniforms responsively.",
    target: "shadow.color",
  }),
  responsiveChangeScenario({
    budget: { maxFrameGapMs: 120, maxInteractionMs: 900 },
    id: "texture-blend-mode",
    label: "Blend",
    observable: "Blend updates the texture compositing uniform responsively.",
    target: "texture.blendMode",
  }),
  responsiveDragScenario({
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1100 },
    id: "texture-opacity",
    label: "Texture Opacity",
    observable: "Texture opacity updates the overlay alpha uniform during drag.",
    target: "texture.opacity",
  }),
  {
    automated: true,
    automatedTestName: "perf: button-image-blend-mode change stays responsive",
    browser: true,
    browserTestName: "browser perf: button-image-blend-mode change stays responsive",
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1000 },
    controlLabel: "Blend",
    expectedObservable:
      "Button image blend mode updates only the image compositing uniform under a realistic uploaded image workload.",
    fixture: "uploaded button image blend mode at render scale 2",
    id: "button-image-blend-mode",
    interaction: "control-change",
    stressFixture: {
      kind: "max-value",
      reason:
        "Screen is a visibly different compositing mode while preserving the cached button image frame.",
      value: "screen",
    },
    target: "buttonImage.blendMode",
    values: { default: "overlay", max: "screen", min: "normal" },
    workload: true,
    workloadFixture: buttonImageWorkload,
  },
  {
    automated: true,
    automatedTestName: "perf: button-image-position change stays responsive",
    browser: true,
    browserTestName: "browser perf: button-image-position change stays responsive",
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1200 },
    controlLabel: "Position",
    expectedObservable:
      "Position redraws only the cached button image frame and the WebGL composite under a realistic uploaded image workload.",
    fixture: "uploaded button image position at render scale 2",
    id: "button-image-position",
    interaction: "control-change",
    stressFixture: {
      kind: "max-value",
      reason:
        "Moving both axes exercises the cached button-image frame without changing the glass lens geometry.",
      value: { x: 0.62, y: -0.42 },
    },
    target: "buttonImage.offset",
    values: {
      default: { x: 0.07, y: 0.01 },
      max: { x: 1, y: 1 },
      min: { x: -1, y: -1 },
    },
    workload: true,
    workloadFixture: buttonImageWorkload,
  },
  {
    automated: true,
    automatedTestName: "perf: button-image-scale drag stays responsive",
    browser: true,
    browserTestName: "browser perf: button-image-scale drag stays responsive",
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1400 },
    controlLabel: "Scale",
    expectedObservable:
      "Scale redraws the cached button image frame live while preserving source, texture, text, displacement, and frost caches.",
    fixture: "uploaded button image scale at render scale 2",
    id: "button-image-scale",
    interaction: "control-drag",
    stressFixture: {
      kind: "max-value",
      reason:
        "Scale max is the largest useful image enlargement exposed by the product control.",
      value: 3,
    },
    target: "buttonImage.scale",
    values: { default: 0.71, max: 3, min: 0.2 },
    workload: true,
    workloadFixture: buttonImageWorkload,
  },
  responsiveChangeScenario({
    id: "text-enabled",
    label: "Include",
    observable: "Text include toggles glass-local text compositing responsively.",
    target: "text.enabled",
  }),
  responsiveChangeScenario({
    id: "text-drag-target",
    label: "Drag",
    observable: "Drag target switches between glass movement and text movement responsively.",
    target: "text.dragTarget",
  }),
  responsiveChangeScenario({
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1200 },
    id: "text-content",
    label: "Text",
    observable: "Bounded glass text content redraws the cached text texture responsively.",
    target: "text.content",
  }),
  responsiveChangeScenario({
    id: "text-blend-mode",
    label: "Text Blend",
    observable: "Text blend mode updates the text compositing uniform responsively.",
    target: "text.blendMode",
  }),
  responsiveChangeScenario({
    id: "text-align-x",
    label: "Horizontal",
    observable: "Horizontal alignment redraws the cached text frame responsively.",
    target: "text.alignX",
  }),
  responsiveChangeScenario({
    id: "text-align-y",
    label: "Vertical",
    observable: "Vertical alignment redraws the cached text frame responsively.",
    target: "text.alignY",
  }),
  responsiveChangeScenario({
    id: "text-offset",
    label: "Offset",
    observable: "Offset redraws the cached glass text frame responsively.",
    target: "text.offset",
  }),
  responsiveDragScenario({
    id: "glass-strength",
    label: "Strength",
    observable: "Strength updates displacement uniforms during drag.",
    target: "glass.strength",
  }),
  responsiveDragScenario({
    id: "glass-fisheye",
    label: "Fisheye",
    observable: "Fisheye updates radial distortion uniforms during drag.",
    target: "glass.fisheye",
  }),
  responsiveDragScenario({
    id: "glass-dispersion",
    label: "Aberration",
    observable: "Aberration updates RGB split uniforms during drag.",
    target: "glass.dispersion",
  }),
  responsiveDragScenario({
    id: "glass-brightness",
    label: "Brightness",
    observable: "Brightness updates the shader veil during drag.",
    target: "glass.brightness",
  }),
  responsiveDragScenario({
    id: "glass-murkiness",
    label: "Murkiness",
    observable: "Murkiness updates the milky veil uniform during drag.",
    target: "glass.murkiness",
  }),
  responsiveDragScenario({
    id: "glass-specular",
    label: "Specular",
    observable: "Specular updates highlight lift during drag.",
    target: "glass.specular",
  }),
  responsiveChangeScenario({
    id: "include-background",
    label: "Include",
    observable: "Include toggles background compositing without viewport jumps.",
    target: "export.includeBackground",
  }),
  responsiveChangeScenario({
    budget: { maxFrameGapMs: 120, maxInteractionMs: 1000 },
    id: "background-color",
    label: "Background",
    observable: "Background color edits update renderer background responsively.",
    target: "appearance.background",
  }),
  responsiveChangeScenario({
    budget: { maxFrameGapMs: 120, maxInteractionMs: 850 },
    id: "image-format",
    label: "Format",
    observable: "Image format selection stays responsive.",
    target: "export.image.format",
  }),
];

export const appPerformance: ToolcraftPerformanceConfig = defineToolcraftPerformance({
  rendererPipeline: {
    interactionInvalidation: [
      {
        interaction: "control-drag",
        invalidates: [
          "source-frame",
          "button-image-frame",
          "text-frame",
          "displacement-map",
          "frost-prepass",
          "lens-composite",
        ],
        targets: [
          "canvas.renderScale",
          "glass.width",
          "glass.height",
          "glass.radius",
          "glass.center",
          "glass.opacity",
          "glass.strength",
          "glass.depth",
          "glass.curvature",
          "glass.fisheye",
          "glass.dispersion",
          "glass.splay",
          "glass.bend",
          "glass.bendWidth",
          "glass.frost",
          "glass.brightness",
          "glass.murkiness",
          "glass.specular",
          "glass.sheen",
          "glass.sheenWidth",
          "glass.sheenAngle",
          "glass.glow",
          "glass.glowSpread",
        ],
      },
      {
        interaction: "control-drag",
        invalidates: ["lens-composite"],
        mustNotInvalidate: [
          "source-frame",
          "button-image-frame",
          "displacement-map",
          "frost-prepass",
        ],
        targets: ["source.saturation", "texture.opacity"],
      },
      {
        interaction: "control-drag",
        invalidates: ["lens-composite"],
        mustNotInvalidate: [
          "source-frame",
          "button-image-frame",
          "texture-frame",
          "text-frame",
          "displacement-map",
          "frost-prepass",
        ],
        targets: ["shadow.blur"],
      },
      {
        interaction: "control-change",
        invalidates: ["text-frame", "lens-composite", "png-export"],
        mustNotInvalidate: ["source-frame", "displacement-map", "frost-prepass"],
        targets: [
          "text.enabled",
          "text.content",
          "text.style",
          "text.alignX",
          "text.alignY",
        ],
      },
      {
        interaction: "control-change",
        invalidates: ["lens-composite"],
        mustNotInvalidate: [
          "source-frame",
          "button-image-frame",
          "texture-frame",
          "text-frame",
          "displacement-map",
          "frost-prepass",
        ],
        targets: ["text.dragTarget"],
      },
      {
        interaction: "control-change",
        invalidates: ["lens-composite", "png-export"],
        mustNotInvalidate: [
          "source-frame",
          "button-image-frame",
          "texture-frame",
          "text-frame",
          "displacement-map",
          "frost-prepass",
        ],
        targets: ["text.offset"],
      },
      {
        interaction: "control-change",
        invalidates: ["lens-composite", "png-export"],
        mustNotInvalidate: [
          "source-frame",
          "button-image-frame",
          "texture-frame",
          "text-frame",
          "displacement-map",
          "frost-prepass",
        ],
        targets: ["shadow.enabled", "shadow.offset", "shadow.color"],
      },
      {
        interaction: "control-change",
        invalidates: ["button-image-frame", "lens-composite", "png-export"],
        mustNotInvalidate: [
          "source-frame",
          "texture-frame",
          "text-frame",
          "displacement-map",
          "frost-prepass",
        ],
        targets: ["buttonImage.offset"],
      },
      {
        interaction: "control-change",
        invalidates: ["lens-composite", "png-export"],
        mustNotInvalidate: [
          "source-frame",
          "button-image-frame",
          "texture-frame",
          "text-frame",
          "displacement-map",
          "frost-prepass",
        ],
        targets: ["buttonImage.blendMode"],
      },
      {
        interaction: "control-drag",
        invalidates: ["button-image-frame", "lens-composite", "png-export"],
        mustNotInvalidate: [
          "source-frame",
          "texture-frame",
          "text-frame",
          "displacement-map",
          "frost-prepass",
        ],
        targets: ["buttonImage.scale"],
      },
      {
        interaction: "control-change",
        invalidates: [
          "source-frame",
          "displacement-map",
          "lens-composite",
          "png-export",
        ],
        targets: [
          "runtime.settingsTransfer",
          "canvas.aspectRatio",
          "canvas.size.width",
          "canvas.size.height",
          "glass.shape",
          "glass.center",
          "appearance.background",
          "export.includeBackground",
          "export.image.format",
          "export.image.resolution",
        ],
      },
      {
        interaction: "control-change",
        invalidates: ["lens-composite", "png-export"],
        mustNotInvalidate: [
          "source-frame",
          "button-image-frame",
          "texture-frame",
          "text-frame",
          "displacement-map",
          "frost-prepass",
        ],
        targets: ["text.blendMode"],
      },
      {
        interaction: "control-change",
        invalidates: ["texture-frame", "lens-composite", "png-export"],
        mustNotInvalidate: [
          "source-frame",
          "button-image-frame",
          "displacement-map",
          "frost-prepass",
        ],
        targets: ["texture.mode", "texture.preset", "texture.blendMode"],
      },
      {
        interaction: "media-import",
        invalidates: ["source-frame", "lens-composite"],
        mustNotInvalidate: ["button-image-frame", "texture-frame", "text-frame"],
        targets: ["source.upload"],
      },
      {
        interaction: "media-import",
        invalidates: ["button-image-frame", "lens-composite", "png-export"],
        mustNotInvalidate: [
          "source-frame",
          "texture-frame",
          "text-frame",
          "displacement-map",
          "frost-prepass",
        ],
        targets: ["buttonImage.upload"],
      },
      {
        interaction: "media-import",
        invalidates: ["texture-frame", "lens-composite"],
        mustNotInvalidate: [
          "source-frame",
          "button-image-frame",
          "displacement-map",
          "frost-prepass",
        ],
        targets: ["texture.upload"],
      },
      {
        interaction: "mask-drag",
        invalidates: ["lens-composite"],
        mustNotInvalidate: [
          "source-frame",
          "button-image-frame",
          "displacement-map",
          "frost-prepass",
        ],
        targets: ["glass.center"],
      },
      {
        interaction: "mask-drag",
        invalidates: ["lens-composite"],
        mustNotInvalidate: [
          "source-frame",
          "button-image-frame",
          "texture-frame",
          "text-frame",
          "displacement-map",
          "frost-prepass",
        ],
        targets: ["text.offset"],
      },
      {
        interaction: "viewport-zoom",
        invalidates: ["lens-composite"],
        mustNotInvalidate: [
          "source-frame",
          "button-image-frame",
          "displacement-map",
          "frost-prepass",
        ],
        targets: ["toolbar.zoom", "canvas.viewport"],
      },
      {
        interaction: "viewport-drag",
        invalidates: ["lens-composite"],
        mustNotInvalidate: [
          "source-frame",
          "button-image-frame",
          "displacement-map",
          "frost-prepass",
        ],
        targets: ["canvas.viewport"],
      },
      {
        interaction: "export",
        invalidates: ["png-export"],
        targets: ["panel.actions", "export.image.resolution", "export.image.format"],
      },
    ],
    passes: [
      {
        cacheKey: [
          "source.upload",
          "appearance.background",
          "export.includeBackground",
          "canvas.size.width",
          "canvas.size.height",
        ],
        id: "source-frame",
        inputs: [
          "source.upload",
          "appearance.background",
          "export.includeBackground",
          "canvas.size.width",
          "canvas.size.height",
        ],
        invalidatedBy: [
          "source.upload",
          "appearance.background",
          "export.includeBackground",
          "canvas.size.width",
          "canvas.size.height",
        ],
        kind: "preprocess",
        output: "source",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: ["texture.mode", "texture.preset", "texture.upload"],
        id: "texture-frame",
        inputs: ["texture.mode", "texture.preset", "texture.upload"],
        invalidatedBy: ["texture.mode", "texture.preset", "texture.upload"],
        kind: "preprocess",
        output: "intermediate",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: [
          "buttonImage.upload",
          "buttonImage.offset",
          "buttonImage.scale",
          "glass.shape",
          "glass.width",
          "glass.height",
          "glass.radius",
        ],
        id: "button-image-frame",
        inputs: [
          "buttonImage.upload",
          "buttonImage.offset",
          "buttonImage.scale",
          "glass.shape",
          "glass.width",
          "glass.height",
          "glass.radius",
        ],
        invalidatedBy: [
          "buttonImage.upload",
          "buttonImage.offset",
          "buttonImage.scale",
          "glass.shape",
          "glass.width",
          "glass.height",
          "glass.radius",
        ],
        kind: "rasterize",
        output: "intermediate",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: [
          "text.enabled",
          "text.content",
          "text.style",
          "text.alignX",
          "text.alignY",
          "glass.shape",
          "glass.width",
          "glass.height",
          "glass.radius",
        ],
        id: "text-frame",
        inputs: [
          "text.enabled",
          "text.content",
          "text.style",
          "text.alignX",
          "text.alignY",
          "glass.shape",
          "glass.width",
          "glass.height",
          "glass.radius",
        ],
        invalidatedBy: [
          "text.enabled",
          "text.content",
          "text.style",
          "text.alignX",
          "text.alignY",
          "glass.shape",
          "glass.width",
          "glass.height",
          "glass.radius",
        ],
        kind: "rasterize",
        output: "intermediate",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: [
          "glass.shape",
          "glass.width",
          "glass.height",
          "glass.radius",
          "glass.depth",
          "glass.curvature",
          "glass.splay",
          "glass.bend",
          "glass.bendWidth",
          "glass.sheen",
          "glass.sheenWidth",
          "glass.sheenAngle",
          "glass.glow",
          "glass.glowSpread",
        ],
        id: "displacement-map",
        inputs: [
          "glass.shape",
          "glass.width",
          "glass.height",
          "glass.radius",
          "glass.depth",
          "glass.curvature",
          "glass.splay",
          "glass.bend",
          "glass.bendWidth",
          "glass.sheen",
          "glass.sheenWidth",
          "glass.sheenAngle",
          "glass.glow",
          "glass.glowSpread",
        ],
        invalidatedBy: [
          "glass.shape",
          "glass.width",
          "glass.height",
          "glass.radius",
          "glass.depth",
          "glass.curvature",
          "glass.splay",
          "glass.bend",
          "glass.bendWidth",
          "glass.sheen",
          "glass.sheenWidth",
          "glass.sheenAngle",
          "glass.glow",
          "glass.glowSpread",
        ],
        kind: "pixel-transform",
        output: "intermediate",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: ["source-frame", "glass.frost"],
        id: "frost-prepass",
        inputs: ["source-frame", "glass.frost"],
        invalidatedBy: ["source-frame", "glass.frost"],
        kind: "pixel-transform",
        output: "intermediate",
        quality: "preview",
        runsOn: "gpu",
      },
      {
        cacheKey: [
          "source-frame",
          "source.saturation",
          "texture-frame",
          "button-image-frame",
          "text-frame",
          "displacement-map",
          "frost-prepass",
          "glass.center",
          "glass.uniforms",
          "texture.blendMode",
          "texture.opacity",
          "buttonImage.blendMode",
          "text.blendMode",
          "text.offset",
          "shadow.enabled",
          "shadow.offset",
          "shadow.color",
          "shadow.blur",
          "canvas.renderScale",
        ],
        id: "lens-composite",
        inputs: [
          "source-frame",
          "source.saturation",
          "texture-frame",
          "button-image-frame",
          "text-frame",
          "displacement-map",
          "frost-prepass",
          "glass.center",
          "glass.opacity",
          "glass.strength",
          "glass.fisheye",
          "glass.dispersion",
          "glass.brightness",
          "glass.murkiness",
          "glass.specular",
          "texture.blendMode",
          "texture.opacity",
          "buttonImage.blendMode",
          "text.blendMode",
          "text.enabled",
          "text.offset",
          "shadow.enabled",
          "shadow.offset",
          "shadow.color",
          "shadow.blur",
          "canvas.renderScale",
        ],
        invalidatedBy: [
          "source-frame",
          "source.saturation",
          "texture-frame",
          "displacement-map",
          "frost-prepass",
          "glass.center",
          "glass.opacity",
          "glass.strength",
          "glass.fisheye",
          "glass.dispersion",
          "glass.brightness",
          "glass.murkiness",
          "glass.specular",
          "texture.blendMode",
          "texture.opacity",
          "buttonImage.blendMode",
          "button-image-frame",
          "text-frame",
          "text.blendMode",
          "text.enabled",
          "text.offset",
          "shadow.enabled",
          "shadow.offset",
          "shadow.color",
          "shadow.blur",
          "canvas.renderScale",
        ],
        kind: "composite",
        output: "preview",
        quality: "retina",
        runsOn: "gpu",
      },
      {
        id: "png-export",
        inputs: [
          "source-frame",
          "texture-frame",
          "button-image-frame",
          "text-frame",
          "displacement-map",
          "frost-prepass",
          "lens-composite",
          "export.image.resolution",
          "export.image.format",
        ],
        invalidatedBy: [
          "panel.actions",
          "export.image.resolution",
          "export.image.format",
          "export.includeBackground",
        ],
        kind: "export",
        output: "export",
        quality: "export",
        runsOn: "export-only",
      },
    ],
  },
  rendererStrategy: "webgl",
  rendererTechnique: {
    exportRenderer: "webgl",
    fidelityRisks: [
      "The Toolcraft port uses the reference WebGL/copy path rather than backdrop-filter DOM refraction so exported pixels stay deterministic.",
      "8K export depends on the browser GPU maximum texture size; tests cover the selected resolution path and record failures.",
    ],
    layers: [
      {
        content: ["dense-pattern", "bitmap-media"],
        exportMode: "included",
        id: "source-texture",
        kind: "background",
        primitiveCount: "high",
        renderer: "canvas-2d",
      },
      {
        content: ["dense-pattern", "bitmap-media"],
        exportMode: "included",
        id: "glass-texture",
        kind: "product-foreground",
        primitiveCount: "high",
        renderer: "canvas-2d",
        uiSelector: "[data-liquid-glass-renderer]",
      },
      {
        content: ["bitmap-media"],
        exportMode: "included",
        id: "button-image",
        intentionalRasterizationReason:
          "Uploaded button imagery must be clipped to the glass lens and transformed inside shader-local UV space, so the image is rasterized to a shape-local texture before WebGL compositing.",
        kind: "product-foreground",
        primitiveCount: "medium",
        renderer: "canvas-2d",
        uiSelector: "[data-liquid-glass-renderer]",
      },
      {
        content: ["text"],
        exportMode: "included",
        id: "glass-text",
        intentionalRasterizationReason:
          "The text must be clipped by and blended inside the WebGL lens SDF, so it is rasterized to a shape-local texture and sampled by the shader rather than rendered as DOM/SVG outside the product canvas.",
        kind: "product-foreground",
        primitiveCount: "low",
        renderer: "canvas-2d",
        uiSelector: "[data-liquid-glass-renderer]",
      },
      {
        content: ["shader", "composite"],
        exportMode: "included",
        id: "liquid-glass-webgl",
        kind: "product-foreground",
        primitiveCount: "high",
        renderer: "webgl",
        uiSelector: "[data-liquid-glass-renderer]",
      },
    ],
    performanceRisks: [
      "SDF map generation still uses CPU ImageData when shape or map-affecting optics change; map generation is cached by shape key and covered by workload slider scenarios.",
      "Generated and uploaded glass textures are cached in a fixed texture frame; mode and pattern changes are covered by texture workload scenarios.",
      "Uploaded button imagery is cached in a shape-local texture; media import, Position, and Scale scenarios cover the clipped image path without reducing preview render scale.",
      "Glass text is rasterized into a cached shape-local texture; content and FontPicker style changes are covered by text workload scenarios.",
      "Frost blur and 8K export are the heaviest GPU paths and are covered by preview, export, and viewport zoom stress scenarios.",
    ],
    previewExportDifferenceReason:
      "Preview uses the selected runtime render scale; PNG export renders a fresh offscreen WebGL canvas at the selected 2K/4K/8K export size.",
    previewRenderer: "webgl",
    productRepresentation: "pixel",
    referenceRendererChangeReason:
      "The reference DOM/SVG material path is not used because Toolcraft needs deterministic pixel export; the reference WebGL shader path is retained.",
    rendererStrategy: "webgl",
    rendererWorkload: "pixel-output",
    sourceRepresentation: "mixed",
    whyNotAlternativeStrategies: [
      "DOM/backdrop-filter cannot provide cross-browser exportable pixels for the Toolcraft PNG action.",
      "SVG feDisplacementMap is close to the reference DOM path but would not cover uploaded media and high-resolution export as predictably as the reference WebGL shader.",
      "CPU Canvas 2D displacement would run per-pixel on the main thread and would not preserve selected 2x preview scale or 4K/8K export quality under stress.",
    ],
  },
  rendererWorkload: "pixel-output",
  scenarios: [
    {
      automated: true,
      automatedTestName: "perf: stress preview render stays within liquid glass budget",
      browser: true,
      browserTestName: "browser perf: stress preview render stays within liquid glass budget",
      budget: { maxLongTaskMs: 180, maxPreviewMs: 1400 },
      expectedObservable:
        "The largest practical preview state renders visible WebGL glass without long main-thread stalls.",
      fixture: "wide lens, max frost, render scale 2",
      id: "stress-preview-render",
      interaction: "preview-render",
      stress: true,
      stressFixture: {
        kind: "custom",
        reason:
          "This combined state exercises source redraw, displacement map generation, frost blur, and WebGL composite at the selected 2x preview scale.",
        value: {
          frost: 14,
          height: 620,
          renderScale: 2,
          width: 900,
        },
      },
      workload: false,
    },
    ...workloadScenarios,
    ...responsiveScenarios,
    {
      automated: true,
      automatedTestName: "perf: glass-center canvas drag stays responsive",
      browser: true,
      browserTestName: "browser perf: glass-center canvas drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1200, maxLongTaskMs: 180 },
      controlLabel: "Center",
      expectedObservable:
        "Dragging the glass handle moves the lens live at render scale 2 without panning the Toolcraft viewport.",
      fixture: "center handle drag at render scale 2",
      id: "glass-center-canvas-drag",
      interaction: "mask-drag",
      stressFixture: {
        kind: "max-value",
        reason:
          "The drag delta moves the default lens far enough to force visibly different refracted pixels while keeping the handle inside the canvas.",
        value: { x: 260, y: 140 },
      },
      target: "glass.center",
      uiSelector: "[data-liquid-glass-drag-zone][data-testid=\"liquid-glass-drag-zone\"]",
      values: {
        default: { x: 0, y: 0 },
        max: { x: 1, y: 1 },
        min: { x: -1, y: -1 },
      },
      workload: true,
      workloadFixture: renderScaleWorkload,
    },
    {
      automated: true,
      automatedTestName: "perf: text-offset canvas drag stays responsive",
      browser: true,
      browserTestName: "browser perf: text-offset canvas drag stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1200, maxLongTaskMs: 180 },
      controlLabel: "Offset",
      expectedObservable:
        "Dragging the glass while Text drag mode is active moves only the text inside the lens at render scale 2.",
      fixture: "text drag target canvas drag at render scale 2",
      id: "text-offset-canvas-drag",
      interaction: "mask-drag",
      stressFixture: {
        kind: "max-value",
        reason:
          "The drag delta moves the default glass text far enough to force visibly different text pixels while keeping the lens stable.",
        value: { x: 180, y: 90 },
      },
      target: "text.offset",
      uiSelector: "[data-liquid-glass-drag-zone][data-liquid-glass-text-drag=\"true\"]",
      values: {
        default: { x: 0, y: 0 },
        max: { x: 1, y: 1 },
        min: { x: -1, y: -1 },
      },
      workload: true,
      workloadFixture: renderScaleWorkload,
    },
    {
      automated: true,
      automatedTestName: "perf: source image media import stays responsive",
      browser: true,
      browserTestName: "browser perf: source image media import stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1800 },
      expectedObservable:
        "A 1920x1080-equivalent source image imports through FileDrop and updates product pixels.",
      fixture: "1920x1080 source image",
      id: "source-media-import",
      interaction: "media-import",
      stressFixture: {
        kind: "media",
        reason:
          "1920x1080 is the minimum realistic source texture size for this shader playground.",
        value: { height: 1080, width: 1920 },
      },
      target: "source.upload",
      uiSelector: "input[type=\"file\"]",
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: button image media import stays responsive",
      browser: true,
      browserTestName: "browser perf: button image media import stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1800 },
      expectedObservable:
        "A 1920x1080-equivalent button image imports through FileDrop and updates only the glass-clipped button imagery.",
      fixture: "1920x1080 button image",
      id: "button-image-media-import",
      interaction: "media-import",
      stressFixture: {
        kind: "media",
        reason:
          "1920x1080 is the minimum realistic uploaded image size for glass-clipped button imagery.",
        value: { height: 1080, width: 1920 },
      },
      target: "buttonImage.upload",
      uiSelector: "input[type=\"file\"]",
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: texture image media import stays responsive",
      browser: true,
      browserTestName: "browser perf: texture image media import stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1800 },
      expectedObservable:
        "A 1920x1080-equivalent overlay image imports through FileDrop and updates only the glass texture pixels.",
      fixture: "1920x1080 texture image",
      id: "texture-media-import",
      interaction: "media-import",
      stressFixture: {
        kind: "media",
        reason:
          "1920x1080 is the minimum realistic uploaded texture size for the glass overlay path.",
        value: { height: 1080, width: 1920 },
      },
      target: "texture.upload",
      uiSelector: "input[type=\"file\"]",
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: image export stays within liquid glass budget",
      browser: true,
      browserTestName: "browser perf: image export stays within liquid glass budget",
      budget: { maxExportMs: 8000 },
      expectedObservable:
        "Export PNG renders the final WebGL output at the selected resolution and returns bytes.",
      fixture: "4K liquid glass export",
      id: "image-export",
      interaction: "export-copy",
      stress: true,
      stressFixture: {
        kind: "custom",
        reason:
          "The export stress state uses 4K output, strong frost, and a large lens while preserving selected quality.",
        value: {
          frost: 10,
          resolution: "4k",
          width: 760,
        },
      },
      target: "panel.actions",
      uiSelector: "text=Export PNG",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: liquid glass viewport stays stable",
      browser: true,
      browserTestName: "browser perf: liquid glass viewport stays stable",
      budget: { maxFrameGapMs: 90 },
      expectedObservable:
        "Canvas drag and center interactions keep viewport state stable around the WebGL renderer.",
      fixture: "default liquid glass viewport",
      id: "viewport-stability",
      interaction: "viewport-stability",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: liquid glass zoom stress stays responsive",
      browser: true,
      browserTestName: "browser perf: liquid glass zoom stress stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1400, maxLongTaskMs: 180 },
      expectedObservable:
        "Toolbar zoom at render scale 2 does not trigger expensive source or map recomputation.",
      fixture: "render scale 2 zoom stress",
      id: "viewport-zoom-stress",
      interaction: "viewport-zoom-stress",
      stress: true,
      stressFixture: {
        kind: "custom",
        reason:
          "Zoom stress uses render scale 2 plus strong shader settings to exercise viewport responsiveness.",
        value: {
          frost: 12,
          renderScale: 2,
          width: 820,
        },
      },
      uiSelector: "[data-liquid-glass-renderer]",
      workload: false,
    },
  ],
  usesCustomRenderer: true,
  workloadTargets: [
    "canvas.aspectRatio",
    "canvas.size.width",
    "canvas.size.height",
    "canvas.renderScale",
    "texture.mode",
    "texture.preset",
    "text.style",
    "glass.shape",
    "glass.width",
    "glass.height",
    "glass.radius",
    "glass.depth",
    "glass.curvature",
    "glass.splay",
    "glass.bend",
    "glass.bendWidth",
    "glass.frost",
    "glass.sheen",
    "glass.sheenWidth",
    "glass.sheenAngle",
    "glass.glow",
    "glass.glowSpread",
    "shadow.blur",
    "export.image.resolution",
  ],
});
