export const GLOBE_BAND_WIDTH_MAX = 60;
export const GLOBE_LOGO_SCALE = { defaultValue: 100, min: 25, max: 135 } as const;

export const GLOBE_TARGETS = {
  background: "appearance.background",
  band1Position: "bands.band1.position",
  band1Width: "bands.band1.width",
  band2Position: "bands.band2.position",
  band2Width: "bands.band2.width",
  band3Position: "bands.band3.position",
  band3Width: "bands.band3.width",
  band4Position: "bands.band4.position",
  band4Width: "bands.band4.width",
  bandColumnSpacing: "bands.columnSpacing",
  bandDistance: "bands.distance",
  bandDotSize: "bands.dotSize",
  crtIntensity: "effects.crtIntensity",
  includeBackground: "export.includeBackground",
  latitudeCount: "globe.latitudeCount",
  lineColor: "globe.lineColor",
  lineWidth: "globe.lineWidth",
  logoDxcFinalPosition: "logos.dxc.finalPosition",
  logoDxcScale: "logos.dxc.scale",
  logoHoldSeconds: "logos.holdSeconds",
  logoIntroRun: "logos.intro.run",
  logoMetaFinalPosition: "logos.meta.finalPosition",
  logoMetaScale: "logos.meta.scale",
  logoPradaFinalPosition: "logos.prada.finalPosition",
  logoPradaScale: "logos.prada.scale",
  logoSpeed: "logos.speed",
  logoZillowFinalPosition: "logos.zillow.finalPosition",
  logoZillowScale: "logos.zillow.scale",
  meridianCount: "globe.meridianCount",
  orientation: "globe.orientation",
  outline: "globe.outline",
  sphereColor: "globe.sphereColor",
} as const;

export const GLOBE_DEFAULTS = {
  background: "#000000",
  band1Position: 69,
  band1Width: 17,
  band2Position: 6,
  band2Width: 50,
  band3Position: -30,
  band3Width: 16,
  band4Position: 46,
  band4Width: 24,
  bandColumnSpacing: 3.5,
  bandDistance: 1,
  bandDotSize: 1.25,
  crtIntensity: 100,
  includeBackground: true,
  latitudeCount: 8,
  lineColor: "#FFFFFF",
  lineWidth: 1.5,
  logoDxcFinalPosition: 60,
  logoHoldSeconds: 3,
  logoMetaFinalPosition: 71,
  logoPradaFinalPosition: 76,
  logoSpeed: 2.5,
  logoZillowFinalPosition: 68,
  meridianCount: 16,
  orientation: {
    position: [2.2, 1.5, 5],
    up: [0, 1, 0],
  },
  outline: true,
  sphereColor: "#000000",
} as const;

export const GLOBE_SCENE_SIZE = {
  height: 1080,
  width: 1920,
} as const;
